"""Methods for working with model manifests."""

import logging
from typing import Literal

from endo_pipeline.manifests import (
    ModelLocation,
    ModelManifest,
    get_model_manifest_dir,
    load_model_manifest,
)

logger = logging.getLogger(__name__)


def get_model_location_for_run(manifest: ModelManifest, run_name: str) -> ModelLocation:
    """Get the model location for the given run from the manifest, if it exists."""

    if run_name not in manifest.locations:
        logger.error(
            "Run [ %s ] does not have a location in model manifest [ %s ]",
            run_name,
            manifest.name,
        )
        raise KeyError(f"Unable to find run {run_name} in model manifest.")

    return manifest.locations[run_name]


def get_most_recent_run_name(model_manifest: ModelManifest) -> str:
    """Get the most recent run name from the model manifest."""
    available_runs = list(model_manifest.locations.keys())

    if not available_runs:
        logger.error("Model manifest [ %s ] has no runs", model_manifest.name)
        raise IndexError("No runs found in model manifest.")

    return available_runs[-1]


def get_feature_dataframe_manifest_name(
    model_manifest: ModelManifest,
    run_name: str | None,
    crop_pattern: Literal["grid", "tracked"] = "grid",
    feature_type: Literal["latent", "pca"] = "pca",
    is_filtered: bool = True,
) -> str:
    """
    Get the feature dataframe manifest name corresponding to model manifest and
    run name.

    **Crop patterns**

    - Grid-based crops are generated by systematically tiling the field of view
      with non-overlapping crops on a grid.
    - Cell-centric crops are generated by centering crops on segmented and
      tracked cells. These crops may be overlapping and may not cover the entire
      field of view.

    **Feature dataframe types**

    - Latent feature dataframes contain just the features extracted from the
      latent space of a model. These dataframe manifests are named according to
      the pattern
        {model_manifest}_{run_name}_{crop_pattern}.
    - PCA feature dataframes contain features that have been projected into a
      reference PC space. These dataframe manifests are named according to the
      pattern
        {model_manifest}_{run_name}_{crop_pattern}_pca.

    **Dataframe filtering**

    The workflow for generating the PC-projected features for both crop types
    includes options for filtering the dataframes to include only crops that
    meet certain criteria (e.g. include_cell_piling=False). If the dataframes
    have been filtered, then "_filtered" is included in the manifest name to
    distinguish from unfiltered dataframes. The naming pattern for filtered
    dataframe manifests is therefore:
        {model_manifest}_{run_name}_{crop_pattern}_filtered for latent feature
        dataframes and {model_manifest}_{run_name}_{crop_pattern}_filtered_pca
        for PCA feature dataframes.

    Parameters
    ----------
    model_manifest
        Model manifest containing the model run for which to get the feature
        dataframe manifest name.
    run_name
        Name of model run for which to get the feature dataframe manifest name.
    crop_pattern
        Crop pattern for which to get the feature dataframe manifest name.
    feature_type
        Type of features for which to get the dataframe manifest name.
    is_filtered
        If true, return the manifest name for the filtered dataframes. If false,
        return the manifest name for the unfiltered dataframes.

    """

    # Check that selected crop pattern is valid.
    if crop_pattern not in ("grid", "tracked"):
        logger.error("Crop pattern must be 'grid' or 'tracked'")
        raise ValueError(f"Crop pattern '{crop_pattern}' is not supported")

    # Default naming pattern is {model_manifest}_{run_name}_{crop_pattern}
    run_name_ = get_most_recent_run_name(model_manifest) if run_name is None else run_name
    feature_suffix = "_pca" if feature_type == "pca" else ""
    filter_suffix = "_filtered" if is_filtered else ""
    feature_manifest_name = (
        f"{model_manifest.name}_{run_name_}_{crop_pattern}{filter_suffix}{feature_suffix}"
    )

    return feature_manifest_name


def get_model_manifest_with_parameters(
    workflow: str, parameters: dict | None = None
) -> ModelManifest:
    """Load model manifest with matching workflow containing given parameters."""

    manifests = []
    parameters = parameters or {}

    # Iterate through all model manifests to find ones with matching
    # workflow name and containing all given parameters.
    for manifest_file in get_model_manifest_dir().iterdir():
        manifest = load_model_manifest(manifest_file.stem)

        if manifest.workflow != workflow:
            continue

        if parameters.items() <= manifest.parameters.items():
            manifests.append(manifest)

    # If no manifests are found, raise error.
    if len(manifests) == 0:
        logger.error(
            "No model manifests found for workflow '%s' with parameters %s",
            workflow,
            parameters,
        )
        raise LookupError("Unable to find manifest with matching parameters")

    # If multiple manifests are found, then raise error. We could also instead
    # raise a warning and return the first manifest found.
    if len(manifests) > 1:
        logger.error(
            "Multiple model manifests found with given parameters: %s",
            " | ".join([manifest.name for manifest in manifests]),
        )
        raise ValueError("Found multiple manifests with matching parameters")

    return manifests[0]
