name: 20240328_T01_001
date: '20240328'
original_path: //allen/programs/allencell/data/proj0/6a0/ac7/916/880/6c2/0db/a4f/f2b/263/d71/ad/20240328_GE00007384_20X_fixed_sldy/20240328_GE00007384_20X_fixed_SLDY.sldy
zarr_positions: [0, 1, 2, 3, 4]
fmsid: add71263f2ba4f0db6c2880916ac76a0
barcode: GE00007384
cell_lines: [AICS-126 cl. 41]
live_or_fixed_sample: fixed
is_timelapse: false
microscope: 3i
objective: 20X
shear_stress_regime: 'no'
pixel_size_xy_in_um: 0.382
duration: 1
time_interval_in_minutes: null
n_total_positions: 10
original_channel_indices:
  brightfield: 4
  channel_488: 5
  channel_405: 1
  channel_561: null
  channel_640: null
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: 2
  channel_561: null
  channel_640: null
channel_names: [VE-cadherin_mEGFP, Brightfield, Nuclei_DAPI]
flow_conditions:
- start: -288
  stop: 0
  shear_stress: 0.0
include_scenes: [5, 6, 7, 8, 9]
notes: no flow dataset (24 hours)
replicate_number: null
stability_category: null
timepoint_annotations: null
position_annotations: null
center_z_plane: null
