name: 20241203_20X
original_path: //allen/programs/allencell/data/proj0/a61/b0d/e86/6b6/175/2b9/745/3da/73b/b61/9d/20241203_GE00007661_20X_timelapse_sldy/20241203_GE00007661_20X_timelapse_SLDY.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20241203_9db6173b3da7452b91756b6e86b0da61
fmsid: 9db6173b3da7452b91756b6e86b0da61
barcode: none
cell_lines: [AICS-126]
live_or_fixed_sample: live
is_timelapse: true
microscope: 3i
shear_stress_regime: 48hr_low
use_cases: [classic_segmentation, measurement]
pixel_size_xy_in_um: 0.382
duration: 577
time_interval_in_minutes: 5.0
flow: [[0, 576, 5.88]]
n_total_positions: 6
channel_488_index: 0
brightfield_channel_index: 1
channel_405_index: null
channel_561_index: null
channel_640_index: null
nuclear_label_free_seg_path: null
nuclear_stain_seg_path: null
nuclear_seg_manifest_fmsid: f17ac69d490b43d48492332c29e338ee
tracking_integration_fmsid: null
diffae_tracking_integration_fmsid: null
immunofluorescence_manifest_fmsid: null
is_reference: false
valid_timepoints: null
cell_mean_features: null
include_scenes: null
notes: This timelapse has not yet been converted to ZARR.
