name: 20241120_20X
original_path: //allen/programs/allencell/data/proj0/223/29e/308/ce5/8a5/ca8/c44/7ed/88e/73b/15/20241120_GE00007382_20X_timelapse/20241120_20X_timelapse_SLDY.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20241120_1573b88e7edc44ca88a5ce530829e223
zarr_positions: [0, 1, 2, 3, 4, 5]
fmsid: 1573b88e7edc44ca88a5ce530829e223
barcode: GE00007382
cell_lines: [AICS-126]
live_or_fixed_sample: live
is_timelapse: true
microscope: 3i
objective: 20X
shear_stress_regime: 48hr_high
pixel_size_xy_in_um: 0.382
duration: 577
time_interval_in_minutes: 5.0
flow: [[0, 576, 28.83]]
n_total_positions: 6
channel_488_index: 0
brightfield_channel_index: 1
flow_conditions:
- start: -28
  stop: 576
  shear_stress: 28.83
channel_405_index: null
channel_561_index: null
channel_640_index: null
nuclear_label_free_seg_path: //allen/aics/endothelial/morphological_features/segmentations/nuclear_labelfree_seg/20241120_20X
nuclear_stain_seg_path: null
nuclear_seg_manifest_fmsid: a9ef7c8557334f1fb36393f79b582609
cdh5_seg_path: //allen/aics/endothelial/morphological_features/segmentations/cdh5_classic_seg/20241120_20X
tracking_integration_fmsid: f053d3a12e454b109061c0e8ac891548
diffae_tracking_integration_fmsid: be213c4232144ac2b069b4ec52dfbab4
immunofluorescence_manifest_fmsid: null
cdh5_classic_seg_tracking_manifest_fmsid: 87ac11462fc6429783291f7c811ca730
cdh5_classic_seg_manifest_fmsid: ba1ceb2b3fb64d8e8c12093214f18200
nuclei_label_free_seg_manifest_fmsid: 0d55f05c699d4ef29571b7516ed585b2
live_merged_seg_features_manifest_fmsid: 6d5ef6fef5a4484985cb63d690d390ee
valid_timepoints:
  start: [230]
  stop: [450]
cell_mean_features: 320cf8ae34394c72a7397d1c39b7d9e9
include_scenes: null
notes: This is a nice 48hr high flow dataset.
