name: 20241022_20X_mito
original_path: //allen/programs/allencell/data/proj0/17e/558/aad/fa4/9c7/dbb/24a/ac9/f25/950/88/20241022_GE00007380_20X_timelapse_SLDY/20241022_GE00007380_20X_timelapse_SLDY.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20241022_88950f25ac924adbb9c7fa4aad55817e
fmsid: 88950f25ac924adbb9c7fa4aad55817e
barcode: GE00007380
cell_lines: [AICS-120]
live_or_fixed_sample: live
microscope: 3i
shear_stress_regime: 24hr_high-to-24hr_low
use_cases: []
pixel_size_xy_in_um: 0.382
duration: 577
time_interval_in_minutes: 5.0
flow: [[0, 263, 25.13], [264, 576, 6.24]]
n_total_positions: 6
channel_488_index: 1
brightfield_channel_index: 0
channel_405_index: null
channel_561_index: null
channel_640_index: null
nuclear_label_free_seg_path: null
nuclear_stain_seg_path: null
nuclear_seg_manifest_fmsid: 4cc9c9f7be764040b4c0250504ed49a2
cdh5_seg_path: null
tracking_integration_fmsid: null
diffae_tracking_integration_fmsid: null
immunofluorescence_manifest_fmsid: null
cdh5_classic_seg_tracking_manifest_fmsid: null
cdh5_classic_seg_manifest_fmsid: null
nuclei_label_free_seg_manifest_fmsid: null
live_merged_seg_features_manifest_fmsid: null
is_reference: false
valid_timepoints: null
cell_mean_features: null
include_scenes: null
notes: ''
