name: 20240328_T02_001
date: '20240328'
original_path: //allen/programs/allencell/data/proj0/866/cdf/da7/303/188/0e8/642/01e/3a7/aa8/55/20240328_GE00007383_20X_fixed_sldy/20240328_GE00007383_20X_fixed_SLDY.sldy
zarr_positions: [0, 1, 2, 3]
fmsid: 55aa83a701e6420e8188303da7cdf866
barcode: GE00007383
cell_lines: [AICS-126 cl. 41]
live_or_fixed_sample: fixed
is_timelapse: false
microscope: 3i
objective: 20X
shear_stress_regime: high
pixel_size_xy_in_um: 0.382
duration: 1
time_interval_in_minutes: null
n_total_positions: 10
original_channel_indices:
  brightfield: 2
  channel_488: 5
  channel_405: 1
  channel_561: null
  channel_640: null
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: 2
  channel_561: null
  channel_640: null
channel_names: [VE-cadherin_mEGFP, Brightfield, Nuclei_DAPI]
flow_conditions:
- start: -288
  stop: 0
  shear_stress: 13.5
include_scenes: [0, 1, 2, 4]
notes: This is the set flow rate not the actual flow rate. Under flow for 24 hours
  prior to fix.
replicate_number: 2
stability_category: null
timepoint_annotations: null
position_annotations: null
center_z_plane: null
