name: 20240328_T01_001
original_path: //allen/programs/allencell/data/proj0/6a0/ac7/916/880/6c2/0db/a4f/f2b/263/d71/ad/20240328_GE00007384_20X_fixed_sldy/20240328_GE00007384_20X_fixed_SLDY.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20240328_add71263f2ba4f0db6c2880916ac76a0
fmsid: add71263f2ba4f0db6c2880916ac76a0
barcode: GE00007384
cell_lines: [AICS-126]
live_or_fixed_sample: fixed
microscope: 3i
shear_stress_regime: no_flow
use_cases: [nuclear_label_free_predictions]
pixel_size_xy_in_um: 0.382
duration: 1
time_interval_in_minutes: -1.0
flow: [[0, -1, 0.0]]
n_total_positions: 10
channel_488_index: 5
brightfield_channel_index: 4
channel_405_index: 1
channel_561_index: null
channel_640_index: null
nuclear_label_free_seg_path: null
nuclear_stain_seg_path: null
nuclear_seg_manifest_fmsid: ''
cdh5_seg_path: null
tracking_integration_fmsid: null
diffae_tracking_integration_fmsid: null
immunofluorescence_manifest_fmsid: null
cdh5_classic_seg_tracking_manifest_fmsid: null
cdh5_classic_seg_manifest_fmsid: null
nuclei_label_free_seg_manifest_fmsid: null
live_merged_seg_features_manifest_fmsid: null
is_reference: false
valid_timepoints: null
cell_mean_features: null
include_scenes: [5, 6, 7, 8, 9]
notes: no flow dataset (24 hours)
