name: 20250522_20X_IFJ
original_path: //allen/programs/allencell/data/proj0/6c0/ddd/7f3/f6e/802/589/54f/993/282/e8e/fa/20250522_GE00008023_20X_sldy/20250522_GE00008023_20X_sldy.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250522_fae8e28299354f589802f6e7f3ddd6c0
zarr_positions: [0, 1, 2, 3, 4, 5]
fmsid: fae8e28299354f589802f6e7f3ddd6c0
barcode: GE00008023
cell_lines: [AICS-126]
live_or_fixed_sample: fixed
is_timelapse: false
microscope: 3i
objective: 20X
shear_stress_regime: high
pixel_size_xy_in_um: 0.382
duration: 0
time_interval_in_minutes: 0.0
n_total_positions: 6
original_channel_indices:
  brightfield: 4
  channel_488: 1
  channel_405: 0
  channel_561: 2
  channel_640: 3
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: 2
  channel_561: 3
  channel_640: 4
flow_conditions:
- start: -288
  stop: 0
  shear_stress: 19.79
valid_timepoints: null
include_scenes: null
notes: Fix & stain for SMAD1 & SOX17 0h post-flow change in a High SS to Low SS experiment
timepoint_annotations: null
position_annotations: null
center_z_plane: null
