name: 20250131_pairedPostFixation
original_path: //allen/programs/allencell/data/proj0/f29/cf2/6d9/fb5/b26/9fb/24e/c6e/419/d7a/39/20250131_GE00006569_20X_PostFix_sldy/20250131_GE00006569_20X_PostFix_sldy.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250131_39d7a419c6e24e9fbb26fb56d9cf2f29
zarr_positions: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
fmsid: 39d7a419c6e24e9fbb26fb56d9cf2f29
barcode: GE00006570
cell_lines: [AICS-126]
live_or_fixed_sample: fixed-methanol
is_timelapse: false
microscope: 3i
objective: 20X
shear_stress_regime: 48hr_low
pixel_size_xy_in_um: 0.382
duration: 1
time_interval_in_minutes: null
flow: [[0, 576, 5.86]]
n_total_positions: 10
original_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
flow_conditions:
- start: -576
  stop: 0
  shear_stress: 5.86
valid_timepoints: null
include_scenes: null
notes: These cells were fixed with methanol (PFA is for most other datasets if fixed).
timepoint_annotations: null
exclude_positions: null
center_z_plane: null
