name: 20250604_20X
date: '20250604'
original_path: //allen/programs/allencell/data/proj0/7dc/bf1/ae4/52d/633/0d9/e45/2e0/f7a/08e/3f/20250604_GE00008165_sldy/20250604_GE00008165_20X_SLDY.sldy
zarr_positions: [0, 1, 2, 3, 4, 5]
fmsid: 3f08ef7a2e0e450d963352dae4bf17dc
barcode: GE00008165
cell_lines: [AICS-126 cl. 41]
live_or_fixed_sample: live
is_timelapse: true
microscope: 3i
objective: 20X
shear_stress_regime: medium
pixel_size_xy_in_um: 0.382
duration: 577
time_interval_in_minutes: 5.0
n_total_positions: 6
original_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
channel_names: [EGFP, Brightfield]
flow_conditions:
- start: -40
  stop: 576
  shear_stress: 12.32
include_scenes: null
notes: Flow history. Cells exposed to flow for 3h 20min prior to start of imaging.
  Cells show mixed alignment leaning towards more parallel
timepoint_annotations:
  auto_bf_scope_error:
    0: [1, 6, 24, 238, 523, 528, 551]
    1: [25, 235, 523, 529]
    2: [235, 523, 529, 539]
    3: [8, 290, 320, 523, 536, 549]
    4: [234, 302, 523, 546, 575]
    5: [8, 302, 320, 523, 525, 546, 547, 561]
  auto_bf_temp_artifact:
    0: [527, 529]
    1: [529]
    2: [352, 524]
    3: [8, 523]
    4: [523, 525]
    5: [234, 236, 523, 525]
  auto_gfp_scope_error:
    0: []
    1: []
    2: []
    3: []
    4: []
    5: []
  cell_piling:
    0: [[330, 576]]
    1: [[300, 576]]
    2: [[330, 576]]
    3: [[220, 576]]
    4: [[220, 576]]
    5: [[220, 576]]
  not_steady_state:
    0: [[0, 55]]
    1: [[0, 60]]
    2: [[0, 70]]
    3: [[0, 65]]
    4: [[0, 70]]
    5: [[0, 75]]
  xy_shift:
    0: [4, 5]
    1: [4, 5]
    2: [4, 5]
    3: [4, 5]
    4: [4, 5]
    5: [4, 5]
position_annotations: null
center_z_plane:
  0: 12
  1: 11
  2: 11
  3: 11
  4: 11
  5: 12
