name: 20250618_20X
original_path: //allen/programs/allencell/data/proj0/c37/d21/bf5/d7c/755/2e9/e46/048/bdf/1e9/f8/20250618_GE00008206_20X_sldy/20250618_GE00008206_20X_SLDY.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250618_f81e9bdf048e462e9755d7cbf5d21c37
zarr_positions: [0, 1, 2, 3, 4, 5]
fmsid: f81e9bdf048e462e9755d7cbf5d21c37
barcode: GE00008206
cell_lines: [AICS-126]
live_or_fixed_sample: live
is_timelapse: true
microscope: 3i
objective: 20X
shear_stress_regime: 48hr_low
pixel_size_xy_in_um: 0.382
duration: 577
time_interval_in_minutes: 5.0
flow: [[0, 576, 5.82]]
n_total_positions: 6
channel_488_index: 0
brightfield_channel_index: 1
flow_conditions:
- start: -30
  stop: 576
  shear_stress: 5.82
channel_405_index: null
channel_561_index: null
channel_640_index: null
valid_timepoints: null
include_scenes: null
notes: Cells are very overgrown by end of experiment. A small hole appears in the
  timelapse partway through and doesn't close
center_z_plane:
  0: 14
  1: 14
  2: 14
  3: 14
  4: 13
  5: 14
exclude_timepoints:
  transmitted_light_mircroscope_error:
    0: [6, 529, 557]
    1: [6, 529, 540, 563]
    2: [540]
    3: [0, 529, 540]
    4: [529, 540]
    5: [528, 540]
  transmitted_light_temporary_artifact:
    0: [52, 273, 337, 379]
    1: [36, 69, 114, 171, 192, 272, 332]
    2: [304]
    3: [292]
    4: [14, 191, 241, 294]
    5: [89, 356, 554]
  misc: # uneven illumination?
    0: [6, 529]
    1: [6, 36, 529]
    2: [304, 529]
    3: [0, 292, 529]
    4: [294, 529]
    5: [356, 529]
