name: 20250618_20X
original_path: //allen/programs/allencell/data/proj0/c37/d21/bf5/d7c/755/2e9/e46/048/bdf/1e9/f8/20250618_GE00008206_20X_sldy/20250618_GE00008206_20X_SLDY.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250618_f81e9bdf048e462e9755d7cbf5d21c37
zarr_positions: [0, 1, 2, 3, 4, 5]
fmsid: f81e9bdf048e462e9755d7cbf5d21c37
barcode: GE00008206
cell_lines: [AICS-126]
live_or_fixed_sample: live
is_timelapse: true
microscope: 3i
objective: 20X
shear_stress_regime: 48hr_low
pixel_size_xy_in_um: 0.382
duration: 577
time_interval_in_minutes: 5.0
flow: [[0, 576, 5.82]]
n_total_positions: 6
channel_488_index: 0
brightfield_channel_index: 1
flow_conditions:
- start: -30
  stop: 576
  shear_stress: 5.82
channel_405_index: null
channel_561_index: null
channel_640_index: null
nuclear_label_free_seg_path: null
nuclear_stain_seg_path: null
cdh5_seg_path: null
tracking_integration_fmsid: null
diffae_tracking_integration_fmsid: null
cdh5_classic_seg_tracking_manifest_fmsid: null
cdh5_classic_seg_manifest_fmsid: null
nuclei_label_free_seg_manifest_fmsid: null
live_merged_seg_features_manifest_fmsid: null
valid_timepoints: null
cell_mean_features: null
include_scenes: null
notes: Cells are very overgrown by end of experiment. A small hole appears in the
  timelapse partway through and doesn't close
