name: 20250228_paired20X
original_path: //allen/programs/allencell/data/proj0/6e0/d20/c72/ff0/6b7/96b/04e/55e/88d/eca/56/20250228_GE00006610_ZSTACK_20X/20250228_GE00006610_20x_zstacks_sldy.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250228_56eca88d55e04e96b6b7ff0c72d206e0
zarr_positions: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
fmsid: 56eca88d55e04e96b6b7ff0c72d206e0
barcode: GE00006610
cell_lines: [AICS-126]
live_or_fixed_sample: fixed
is_timelapse: false
microscope: 3i
objective: 20X
shear_stress_regime: 24hr_low
pixel_size_xy_in_um: 0.382
duration: 1
time_interval_in_minutes: null
flow: [[0, 0, 0.0]]
n_total_positions: 10
channel_488_index: 0
brightfield_channel_index: 1
flow_conditions:
- start: -288
  stop: 0
  shear_stress: 5.71
channel_405_index: null
channel_561_index: null
channel_640_index: null
nuclear_stain_seg_path: null
cdh5_seg_path: null
valid_timepoints: null
include_scenes: null
notes: ''
