name: 20250522_20X_IFI
original_path: //allen/programs/allencell/data/proj0/c1e/ab4/0d4/d69/708/298/64a/c9c/ae3/b95/56/20250522_GE00007989_20X_sldy/20250522_GE00007989_20X_sldy.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250522_56b95ae3c9c64a298708d690d4ab4c1e
zarr_positions: [0, 1, 2, 3, 4, 5]
fmsid: 56b95ae3c9c64a298708d690d4ab4c1e
barcode: GE00007989
cell_lines: [AICS-126]
live_or_fixed_sample: fixed
is_timelapse: false
microscope: 3i
objective: 20X
shear_stress_regime: no_flow
pixel_size_xy_in_um: 0.382
duration: 1
time_interval_in_minutes: null
n_total_positions: 6
original_channel_indices:
  brightfield: 4
  channel_488: 1
  channel_405: 0
  channel_561: 2
  channel_640: 3
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: 2
  channel_561: 3
  channel_640: 4
flow_conditions:
- start: -576
  stop: 0
  shear_stress: 0.0
valid_timepoints: null
include_scenes: null
notes: Cells were only fed 2x during 48h experiment
timepoint_annotations:
  auto_bf_scope_error:
    0: []
    1: []
    2: [0]
    3: []
    4: []
    5: []
  auto_bf_temp_artifact:
    0: []
    1: []
    2: []
    3: []
    4: []
    5: []
position_annotations: null
center_z_plane:
  0: 8
  1: 9
  2: 9
  3: 9
  4: 8
  5: 8
