name: 20251021_20X_IF4
original_path: //allen/programs/allencell/data/proj0/5b2/71a/db8/80f/e05/a0a/e43/fbd/a93/1ca/3b/20251021_GE00009357_4_SLDY/20251021_GE00009357_4_SLDY.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20251021_3b1caa93fbde43a0ae0580fdb871a5b2
zarr_positions: [0, 1, 2, 3, 4, 5]
fmsid: 3b1caa93fbde43a0ae0580fdb871a5b2
barcode: GE00009357
cell_lines: [AICS-126]
live_or_fixed_sample: live
is_timelapse: false
microscope: 3i
objective: 20X
shear_stress_regime: max_to_min
pixel_size_xy_in_um: 0.382
duration: 1
time_interval_in_minutes: null
n_total_positions: 6
original_channel_indices:
  brightfield: 4
  channel_488: 1
  channel_405: 0
  channel_561: 2
  channel_640: 3
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: 2
  channel_561: 3
  channel_640: 4
flow_conditions:
- start: -337
  stop: -49
  shear_stress: 18.54
- start: -48
  stop: 0
  shear_stress: 6.02
include_scenes: null
notes: Fix & stain cells for SMAD1 and SOX17 after 24h High SS + 4h Low SS
timepoint_annotations:
  auto_bf_scope_error:
    0: []
    1: []
    2: []
    3: []
    4: []
    5: []
  auto_bf_temp_artifact:
    0: []
    1: []
    2: []
    3: []
    4: []
    5: []
  auto_gfp_scope_error:
    0: []
    1: []
    2: []
    3: []
    4: []
    5: []
position_annotations: null
center_z_plane:
  0: 11
  1: 11
  2: 11
  3: 9
  4: 10
  5: 9
