name: 20250415_SlideH_20X
date: '20250415'
original_path: //allen/programs/allencell/data/proj0/655/ee7/c58/80c/e02/60a/c44/308/307/a3c/eb/20250415_GE00006885_slideH_20X_sldy/20250415_GE00006885_slideH_20X_sldy.sldy
zarr_positions: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
  19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
  39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]
fmsid: eba3c307308c4460ae0280cc58ee7655
barcode: GE00006885
cell_lines: [AICS-126 cl. 41]
live_or_fixed_sample: fixed
is_timelapse: false
microscope: 3i
objective: 20X
shear_stress_regime: min
pixel_size_xy_in_um: 0.382
duration: 1
time_interval_in_minutes: null
n_total_positions: 50
original_channel_indices:
  brightfield: 2
  channel_488: 1
  channel_405: 0
  channel_561: null
  channel_640: null
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: 2
  channel_561: null
  channel_640: null
channel_names: [VE-cadherin_mEGFP, Brightfield, Nuclei_NucViolet]
flow_conditions:
- start: -576
  stop: 0
  shear_stress: 5.47
include_scenes: null
notes: NucViolet + BF only (acquired for nuclear segmentation ground truth). Sample
  was also used to test Sox17 antibody optimization and NR2F2 detection.
timepoint_annotations: null
position_annotations: null
center_z_plane: null
