name: 20250304_paired3iNikon_3i1st
original_path: //allen/programs/allencell/data/proj0/83d/701/9bb/733/bbd/b6a/047/d43/787/5c7/d5/20250304_GE00006610_20X_SLDY/20250304_GE00006610_20X_pairedNikon.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250304_d55c7787d43047b6abbd7339bb70183d
fmsid: d55c7787d43047b6abbd7339bb70183d
barcode: GE00006610
cell_lines: [AICS-126]
live_or_fixed_sample: fixed
is_timelapse: false
microscope: 3i
shear_stress_regime: 24hr_low
use_cases: []
pixel_size_xy_in_um: 0.382
duration: 1
time_interval_in_minutes: -1.0
flow: [[0, 0, 0.0]]
n_total_positions: 50
channel_488_index: 0
brightfield_channel_index: 1
channel_405_index: null
channel_561_index: null
channel_640_index: null
nuclear_label_free_seg_path: null
nuclear_stain_seg_path: null
nuclear_seg_manifest_fmsid: ''
tracking_integration_fmsid: null
diffae_tracking_integration_fmsid: null
immunofluorescence_manifest_fmsid: null
is_reference: false
valid_timepoints: null
cell_mean_features: null
include_scenes: null
notes: ''
