name: 20251103_20X_IF9
date: '20251103'
original_path: //allen/programs/allencell/data/proj0/65b/bc7/31c/f7d/52b/128/b45/69e/797/25e/50/20251103_GE00009362_9_SLDY/20251103_GE00009362_9_SLDY.sldy
zarr_positions: [0, 1, 2, 3, 4, 5]
fmsid: 5025e79769eb4512852bf7d31cbc765b
barcode: GE00009362
cell_lines: [AICS-126]
live_or_fixed_sample: fixed
is_timelapse: false
microscope: 3i
objective: 20X
shear_stress_regime: 'no'
pixel_size_xy_in_um: 0.382
duration: 1
time_interval_in_minutes: null
n_total_positions: 6
original_channel_indices:
  brightfield: 4
  channel_488: 1
  channel_405: 0
  channel_561: 2
  channel_640: 3
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: 2
  channel_561: 3
  channel_640: 4
channel_names: [EGFP, BF, NucViolet, SOX17, SMAD1]
flow_conditions:
- start: -577
  stop: 0
  shear_stress: 0.0
include_scenes: null
notes: Fix & use cells as a no primary control after 48h no SS
timepoint_annotations:
  auto_bf_scope_error:
    0: []
    1: []
    2: []
    3: []
    4: []
    5: []
  auto_bf_temp_artifact:
    0: []
    1: []
    2: []
    3: []
    4: []
    5: []
  auto_gfp_scope_error:
    0: []
    1: []
    2: []
    3: []
    4: []
    5: []
position_annotations: null
center_z_plane:
  0: 9
  1: 8
  2: 9
  3: 8
  4: 9
  5: 8
