name: 20250326_20X
original_path: //allen/programs/allencell/data/proj0/353/acc/1d4/7ad/611/c5a/c44/262/ddf/97a/eb/20250326_GE00007488_20X_timelapse_sldy/20250326_GE00007488_20X_timelapse_sldy.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250326_eb97addf262c44c5a6117ad1d4acc353
zarr_positions: [0, 1, 2, 3, 4, 5]
fmsid: eb97addf262c44c5a6117ad1d4acc353
barcode: GE00007488
cell_lines: [AICS-126]
live_or_fixed_sample: live
is_timelapse: true
microscope: 3i
objective: 20X
shear_stress_regime: intermediate
pixel_size_xy_in_um: 0.382
duration: 577
time_interval_in_minutes: 5.0
flow: [[0, 576, 15.74]]
n_total_positions: 6
channel_488_index: 0
brightfield_channel_index: 1
flow_conditions:
- start: -16
  stop: 576
  shear_stress: 15.74
channel_405_index: null
channel_561_index: null
channel_640_index: null
nuclear_stain_seg_path: null
cdh5_seg_path: //allen/aics/endothelial/morphological_features/segmentations/cdh5_classic_seg/20250326_20X
valid_timepoints:
  start: [129]
  stop: [345]
include_scenes: null
notes: ''
