name: 20250509_20X_IF11
date: '20250509'
original_path: //allen/programs/allencell/data/proj0/c49/e0a/d24/790/d6e/f5b/44d/1bf/7a5/378/1d/20250509_GE00007882_20X_sldy/20250509_GE00007882_20X_sldy.sldy
zarr_positions: [0, 1]
fmsid: 1d3787a51bf44df5bd6e790d24e0ac49
barcode: GE00007882
cell_lines: [AICS-126 cl. 41]
live_or_fixed_sample: fixed
is_timelapse: false
microscope: 3i
objective: 20X
shear_stress_regime: 'no'
pixel_size_xy_in_um: 0.382
duration: 1
time_interval_in_minutes: null
n_total_positions: 2
original_channel_indices:
  brightfield: 4
  channel_488: 1
  channel_405: 0
  channel_561: 2
  channel_640: 3
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: 2
  channel_561: 3
  channel_640: 4
channel_names: [EGFP, BF, NucViolet, SOX17, NR2F2]
flow_conditions:
- start: -288
  stop: 0
  shear_stress: 0.0
include_scenes: null
notes: Secondary only immunofluorescence control
timepoint_annotations:
  auto_bf_scope_error:
    0: []
    1: []
  auto_bf_temp_artifact:
    0: [0]
    1: [0]
position_annotations: null
center_z_plane:
  0: 9
  1: 10
