name: 20251001_20X
date: '20251001'
original_path: //allen/programs/allencell/data/proj0/b15/30c/b00/a84/9e8/949/640/3a1/4f0/112/27/20251001_GE00009220_20X_sldy/20251001_GE00009220_20X_sldy.sldy
zarr_positions: [0, 1, 2, 3, 4, 5]
fmsid: 271124f03a16409499e8a84b0030cb15
barcode: GE00009220
cell_lines: [AICS-126 cl. 41]
live_or_fixed_sample: live
is_timelapse: true
microscope: 3i
objective: 20X
shear_stress_regime: max
pixel_size_xy_in_um: 0.382
duration: 577
time_interval_in_minutes: 5.0
n_total_positions: 6
original_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
channel_names: [VE-cadherin_mEGFP, Brightfield]
flow_conditions:
- start: -18
  stop: 576
  shear_stress: 20.87
include_scenes: null
notes: ''
replicate_number: 1
stability_category: monostable
timepoint_annotations:
  auto_bf_scope_error:
    0: [225, 238, 485, 549, 550]
    1: [199, 485, 550, 566]
    2: [237, 485, 550]
    3: [199, 237, 485, 549, 550]
    4: [237, 485, 493, 548, 550]
    5: []
  auto_bf_temp_artifact:
    0: [198, 199, 200, 485, 549, 564]
    1: [198, 199, 200]
    2: [198, 200, 548]
    3: [198, 199, 200, 219, 549]
    4: [199, 549, 550, 570]
    5: [199, 200]
  auto_gfp_scope_error:
    0: []
    1: []
    2: []
    3: []
    4: []
    5: []
  cell_piling:
    5: [502, 576]
  not_steady_state:
    0: [[0, 98]]
    1: [[0, 87]]
    2: [[0, 71]]
    3: [[0, 126]]
    4: [[0, 69]]
    5: [[0, 97]]
position_annotations:
  dust_artifact: [2, 3, 4]
center_z_plane:
  0: 12
  1: 11
  2: 11
  3: 11
  4: 11
  5: 11
