name: 20250214_pairedPreFixation
original_path: //allen/programs/allencell/data/proj0/dbc/19a/8ae/2e6/8df/a28/a40/355/2c7/0e3/07/20250214_GE00006747_20X_PRE_FIX_sldy/20250214_GE00006747_20X_PRE_FIX_SLDY.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250214_070e32c7355a40a288df2e68ae19adbc
zarr_positions: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
fmsid: 070e32c7355a40a288df2e68ae19adbc
barcode: GE00006747
cell_lines: [AICS-126]
live_or_fixed_sample: fixed
is_timelapse: false
microscope: 3i
objective: 20X
shear_stress_regime: no_flow
pixel_size_xy_in_um: 0.382
duration: 1
time_interval_in_minutes: null
flow: [[0, 0, 0.0]]
n_total_positions: 10
channel_488_index: 0
brightfield_channel_index: 1
flow_conditions:
- start: -576
  stop: 0
  shear_stress: 0.0
channel_405_index: null
channel_561_index: null
channel_640_index: null
cdh5_seg_path: null
valid_timepoints: null
include_scenes: null
notes: ''
