name: 20250509_20X_IF3
original_path: //allen/programs/allencell/data/proj0/2e3/bbb/8a1/840/3ab/929/846/318/ae1/38e/f1/20250509_GE00007874_20X_sldy/20250509_GE00007874_20X_sldy.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250509_f138eae13188469293ab8408a1bbb2e3
zarr_positions:
- 0
- 1
fmsid: f138eae13188469293ab8408a1bbb2e3
barcode: GE00007874
cell_lines:
- AICS-126
live_or_fixed_sample: fixed
is_timelapse: false
microscope: 3i
shear_stress_regime: 24hr_no_flow
pixel_size_xy_in_um: 0.382
duration: 1
time_interval_in_minutes: null
flow:
- - 0
  - 0
  - 0.0
n_total_positions: 2
channel_488_index: 1
brightfield_channel_index: 4
flow_conditions:
- start: -288
  stop: 0
  shear_stress: 0.0
channel_405_index: 0
channel_561_index: 2
channel_640_index: 3
nuclear_label_free_seg_path: null
nuclear_stain_seg_path: //allen/aics/endothelial/morphological_features/segmentations/nuclear_stain_seg/20250509_20X_IF3
nuclear_seg_manifest_fmsid: ''
cdh5_seg_path: null
tracking_integration_fmsid: null
diffae_tracking_integration_fmsid: ''
immunofluorescence_manifest_fmsid: 03fed0bd0a4b45ec95549f0f2adcf274
cdh5_classic_seg_tracking_manifest_fmsid: null
cdh5_classic_seg_manifest_fmsid: null
nuclei_label_free_seg_manifest_fmsid: null
live_merged_seg_features_manifest_fmsid: null
valid_timepoints: null
cell_mean_features: null
include_scenes: null
notes: image content NucViolet,EGFP_CDH5,SOX17,SMAD1,BF
