name: 20251126_pairedPreFixation
date: '20251126'
original_path: //allen/programs/allencell/data/proj0/606/8f0/021/f0c/306/8ba/f4e/eb5/082/52e/d6/20251126_GE00009676_20X_PreFix_SLDY/20251126_GE00009676_20X_PreFix_SLDY.sldy
zarr_positions: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
fmsid: d652e082eb5f4e8ba306f0c0218f0606
barcode: GE00009676
cell_lines: [AICS-126]
live_or_fixed_sample: live
is_timelapse: false
microscope: 3i
objective: 20X
shear_stress_regime: max
pixel_size_xy_in_um: 0.382
duration: 1
time_interval_in_minutes: null
n_total_positions: 10
original_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
channel_names: [EGFP, BF]
flow_conditions:
- start: -282
  stop: 0
  shear_stress: 21.56
include_scenes: null
notes: Collect high SS 24h live/fixed paired data after 24h high SS to match live
  imaging to fixed
timepoint_annotations:
  auto_bf_scope_error:
    0: [0]
    1: []
    2: []
    3: []
    4: []
    5: []
    6: []
    7: [0]
    8: [0]
    9: []
  auto_bf_temp_artifact:
    0: []
    1: []
    2: []
    3: []
    4: [0]
    5: []
    6: []
    7: []
    8: []
    9: []
  auto_gfp_scope_error:
    0: []
    1: []
    2: []
    3: []
    4: []
    5: []
    6: []
    7: []
    8: []
    9: []
position_annotations: null
center_z_plane:
  0: 11
  1: 12
  2: 9
  3: 8
  4: 9
  5: 9
  6: 9
  7: 9
  8: 9
  9: 9
