name: 20250929_IF7
original_path: //allen/programs/allencell/data/proj0/8ee/758/72a/204/46c/c58/345/6e2/e2e/f3f/a7/20250929_GE00009113_7_20X_SLDY/20250929_GE00009113_7_20X_SLDY.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250929_a7f3fe2e6e2345c5846c20472a7588ee
zarr_positions: [0, 1, 2, 3, 4, 5, 6]
fmsid: a7f3fe2e6e2345c5846c20472a7588ee
barcode: GE00009113
cell_lines: [AICS-126]
live_or_fixed_sample: fixed
is_timelapse: false
microscope: 3i
objective: 20X
shear_stress_regime: medium
pixel_size_xy_in_um: 0.382
duration: 1
time_interval_in_minutes: null
n_total_positions: 7
original_channel_indices:
  brightfield: 4
  channel_488: 1
  channel_405: 0
  channel_561: 2
  channel_640: 3
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: 2
  channel_561: 3
  channel_640: 4
flow_conditions:
- start: -432
  stop: 0
  shear_stress: 11.91
include_scenes: null
notes: Fix & stain cells for SMAD1 and SOX17 after 36h Intermediate SS (goal SS 12
  dyn/cm2)
timepoint_annotations: null
position_annotations: null
center_z_plane: null
