name: 20250304_paired3iNikon_Nikon2nd
original_path: //allen/programs/allencell/data/proj0/165/a2e/91e/ce8/062/1a8/942/77d/f2e/51c/8d/20250304_20X_paired3iNikon_GE00006610.nd2
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250304_8d51cf2e77d9421a8062ce891ea2e165
zarr_positions: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
  19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
  39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]
fmsid: 8d51cf2e77d9421a8062ce891ea2e165
barcode: GE00006610
cell_lines: [AICS-126]
live_or_fixed_sample: fixed
is_timelapse: false
microscope: Nikon
objective: 20X
shear_stress_regime: 24hr_low
pixel_size_xy_in_um: 0.392
duration: 1
time_interval_in_minutes: null
flow: [[0, 0, 0.0]]
n_total_positions: 50
channel_488_index: 0
brightfield_channel_index: 1
flow_conditions:
- start: -288
  stop: 0
  shear_stress: 0.0
channel_405_index: null
channel_561_index: null
channel_640_index: null
valid_timepoints: null
include_scenes: null
notes: ''
timepoint_annotations: null
exclude_positions: null
center_z_plane: null
