name: 20250326_20X
date: '20250326'
original_path: //allen/programs/allencell/data/proj0/353/acc/1d4/7ad/611/c5a/c44/262/ddf/97a/eb/20250326_GE00007488_20X_timelapse_sldy/20250326_GE00007488_20X_timelapse_sldy.sldy
zarr_positions: [0, 1, 2, 3, 4, 5]
fmsid: eb97addf262c44c5a6117ad1d4acc353
barcode: GE00007488
cell_lines: [AICS-126 cl. 41]
live_or_fixed_sample: live
is_timelapse: true
microscope: 3i
objective: 20X
shear_stress_regime: high
pixel_size_xy_in_um: 0.382
duration: 577
time_interval_in_minutes: 5.0
n_total_positions: 6
original_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
channel_names: [VE-cadherin_mEGFP, Brightfield]
flow_conditions:
- start: -12
  stop: 576
  shear_stress: 15.74
include_scenes: null
notes: ''
replicate_number: 5
stability_category: monostable
timepoint_annotations:
  auto_bf_scope_error:
    0: [529, 531]
    1: [8]
    2: [529, 531]
    3: [527]
    4: [527, 529]
    5: [527, 529, 544]
  auto_bf_temp_artifact:
    0: [531]
    1: [531, 533]
    2: []
    3: [8]
    4: [527, 529, 531]
    5: [527, 529]
  auto_gfp_scope_error:
    0: []
    1: []
    2: []
    3: []
    4: []
    5: []
  bf_scope_error:
    0: [527]
    1: [527]
    2: [527]
    3: [527]
    4: [527]
    5: [527]
  cell_piling:
    0: [[494, 576]]
    1: [[508, 576]]
    2: [[438, 576]]
    3: [[400, 576]]
    4: [[497, 576]]
    5: [[458, 576]]
  not_steady_state:
    0: [[0, 53]]
    1: [[0, 107]]
    2: [[0, 88]]
    3: [[0, 102]]
    4: [[0, 99]]
    5: [[0, 67]]
position_annotations: null
center_z_plane:
  0: 11
  1: 10
  2: 10
  3: 11
  4: 10
  5: 10
