name: 20251103_20X_IF8
date: '20251103'
original_path: //allen/programs/allencell/data/proj0/68d/5bd/e67/bc8/349/1a9/a48/af0/f80/f9f/ba/20251103_GE00009361_8_SLDY/20251103_GE00009361_8_SLDY.sldy
zarr_positions: [0, 1, 2, 3, 4, 5]
fmsid: baf9ff80af0a481a9349bc8e675bd68d
barcode: GE00009361
cell_lines: [AICS-126]
live_or_fixed_sample: fixed
is_timelapse: false
microscope: 3i
objective: 20X
shear_stress_regime: max_to_min
pixel_size_xy_in_um: 0.382
duration: 1
time_interval_in_minutes: null
n_total_positions: 6
original_channel_indices:
  brightfield: 4
  channel_488: 1
  channel_405: 0
  channel_561: 2
  channel_640: 3
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: 2
  channel_561: 3
  channel_640: 4
channel_names: [EGFP, BF, NucViolet, SOX17, SMAD1]
flow_conditions:
- start: -577
  stop: -289
  shear_stress: 21.71
- start: -288
  stop: 0
  shear_stress: 6.03
include_scenes: null
notes: Fix & stain cells for SMAD1 and SOX17 after 24h High SS + 24h Low SS
timepoint_annotations:
  auto_bf_scope_error:
    0: []
    1: []
    2: []
    3: []
    4: []
    5: []
  auto_bf_temp_artifact:
    0: []
    1: []
    2: []
    3: []
    4: []
    5: []
  auto_gfp_scope_error:
    0: []
    1: []
    2: []
    3: []
    4: []
    5: []
position_annotations: null
center_z_plane:
  0: 10
  1: 8
  2: 9
  3: 8
  4: 8
  5: 8
