name: 20250522_20X_IFH
original_path: //allen/programs/allencell/data/proj0/880/d07/85a/594/c0f/cc9/c44/5bd/a25/c4d/e3/20250522_GE00007988_20X_sldy/20250522_GE00007988_20X_sldy.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250522_e3c4da255bdc44cc9c0f59485ad07880
zarr_positions: [0, 1, 2, 3, 4, 5]
fmsid: e3c4da255bdc44cc9c0f59485ad07880
barcode: GE00007988
cell_lines: [AICS-126]
live_or_fixed_sample: fixed
is_timelapse: false
microscope: 3i
objective: 20X
shear_stress_regime: low
pixel_size_xy_in_um: 0.382
duration: 0
time_interval_in_minutes: 0.0
n_total_positions: 6
original_channel_indices:
  brightfield: 4
  channel_488: 1
  channel_405: 0
  channel_561: 2
  channel_640: 3
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: 2
  channel_561: 3
  channel_640: 4
flow_conditions:
- start: -288
  stop: 0
  shear_stress: 5.23
valid_timepoints: null
include_scenes: null
notes: Fix & stain for SMAD1 & SOX17 0h post-flow change in a Low SS to High SS experiment
timepoint_annotations: null
position_annotations: null
center_z_plane: null
