name: 20251103_20X_IF10
date: '20251103'
original_path: //allen/programs/allencell/data/proj0/0b2/931/910/7e1/3e6/8aa/64e/8de/358/7b5/d3/20251103_GE00009363_10_SLDY/20251103_GE00009363_10_SLDY.sldy
zarr_positions: [0, 1, 2, 3, 4, 5]
fmsid: d37b53588de64e8aa3e67e19109310b2
barcode: GE00009363
cell_lines: [AICS-126]
live_or_fixed_sample: fixed
is_timelapse: false
microscope: 3i
objective: 20X
shear_stress_regime: medium
pixel_size_xy_in_um: 0.382
duration: 1
time_interval_in_minutes: null
n_total_positions: 6
original_channel_indices:
  brightfield: 4
  channel_488: 1
  channel_405: 0
  channel_561: 2
  channel_640: 3
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: 2
  channel_561: 3
  channel_640: 4
channel_names: [EGFP, BF, NucViolet, SOX17, SMAD1]
flow_conditions:
- start: -577
  stop: 0
  shear_stress: 11.8
include_scenes: null
notes: Fix & stain cells for SMAD1 and SOX17 after 48h Intermediate SS (goal 12 dyn/cm2)
timepoint_annotations:
  auto_bf_scope_error:
    0: []
    1: []
    2: []
    3: []
    4: []
    5: []
  auto_bf_temp_artifact:
    0: []
    1: []
    2: []
    3: []
    4: []
    5: []
  auto_gfp_scope_error:
    0: []
    1: []
    2: []
    3: []
    4: []
    5: []
position_annotations: null
center_z_plane:
  0: 8
  1: 8
  2: 7
  3: 8
  4: 6
  5: 7
