name: 20250319_20X
original_path: //allen/programs/allencell/data/proj0/798/774/d92/07d/9af/8c9/e4e/054/8d3/94f/0d/20250319_GE00007419_20X_SLDY/20250319_GE00007419_20X_Timelapsee.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250319_0d94f8d3054e4e8c99af07dd92774798
fmsid: 0d94f8d3054e4e8c99af07dd92774798
barcode: GE00007419
cell_lines:
- AICS-126
live_or_fixed_sample: live
is_timelapse: true
microscope: 3i
shear_stress_regime: intermediate
use_cases: []
pixel_size_xy_in_um: 0.382
duration: 542
time_interval_in_minutes: 5.0
flow:
- - 0
  - 576
  - 12.2
n_total_positions: 6
channel_488_index: 0
brightfield_channel_index: 1
flow_condition:
- start: 0
  stop: 576
  shear_stress: 12.2
channel_405_index: null
channel_561_index: null
channel_640_index: null
nuclear_label_free_seg_path: //allen/aics/endothelial/morphological_features/segmentations/nuclear_labelfree_seg/20250319_20X
nuclear_stain_seg_path: null
nuclear_seg_manifest_fmsid: ''
tracking_integration_fmsid: null
diffae_tracking_integration_fmsid: null
immunofluorescence_manifest_fmsid: null
is_reference: false
valid_timepoints:
  start:
  - 117
  stop:
  - 336
cell_mean_features: c79efb6d0f754e719b71221d7ea3c17f
include_scenes: null
notes: Stopped imaging prior to 48 hours because cells were very packed
