name: 20250110_paired20X
original_path: //allen/programs/allencell/data/proj0/030/79c/609/5c6/ec5/d9b/047/4ff/376/5cc/d9/20250110_GE00006323_20X_zstacks_SLDY/20250110_GE00006323_20X_zstacks_SLDY.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250110_d95cc3764ff047d9bec55c660979c030
fmsid: d95cc3764ff047d9bec55c660979c030
barcode: GE00006323
cell_lines: [AICS-126]
live_or_fixed_sample: live
microscope: 3i
shear_stress_regime: 24hr_low-to-24hr_high
use_cases: [model_training]
pixel_size_xy_in_um: 0.382
duration: 1
time_interval_in_minutes: -1.0
flow: [[0, 288, 6.02], [289, 576, 35.0]]
n_total_positions: 10
channel_488_index: 0
brightfield_channel_index: 1
channel_405_index: null
channel_561_index: null
channel_640_index: null
nuclear_label_free_seg_path: null
nuclear_stain_seg_path: null
nuclear_seg_manifest_fmsid: ''
diffae_manifest_fmsid: e7f3e9715e254bd7a89b956d7db304d2
tracking_integration_fmsid: null
diffae_tracking_integration_fmsid: null
immunofluorescence_manifest_fmsid: null
is_reference: false
valid_timepoints: null
cell_mean_features: null
include_scenes: [1, 2, 3, 4, 5, 6, 7, 8, 9]
notes: ''
