name: 20250319_20X
date: '20250319'
original_path: //allen/programs/allencell/data/proj0/798/774/d92/07d/9af/8c9/e4e/054/8d3/94f/0d/20250319_GE00007419_20X_SLDY/20250319_GE00007419_20X_Timelapsee.sldy
zarr_positions: [0, 1, 2, 3, 4, 5]
fmsid: 0d94f8d3054e4e8c99af07dd92774798
barcode: GE00007419
cell_lines: [AICS-126 cl. 41]
live_or_fixed_sample: live
is_timelapse: true
microscope: 3i
objective: 20X
shear_stress_regime: medium
pixel_size_xy_in_um: 0.382
duration: 543
time_interval_in_minutes: 5.0
n_total_positions: 6
original_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
channel_names: [VE-cadherin_mEGFP, Brightfield]
flow_conditions:
- start: -16
  stop: 576
  shear_stress: 12.2
include_scenes: null
notes: Stopped imaging prior to 48 hours because cells were very packed
stability_category: bistable
replicate_number: 5
timepoint_annotations:
  auto_bf_scope_error:
    0: [248, 252]
    1: [243]
    2: [8, 299]
    3: []
    4: [8, 240]
    5: [240, 513]
  auto_bf_temp_artifact:
    0: []
    1: []
    2: [7, 8]
    3: [5, 8]
    4: [8, 240]
    5: [532]
  auto_gfp_scope_error:
    0: [490]
    1: []
    2: []
    3: []
    4: []
    5: []
  bf_scope_error:
    0: []
    1: []
    2: [7, 8]
    3: [5, 8]
    4: [8, 240]
    5: []
  cell_piling:
    0: [[336, 576]]
    1: [[309, 576]]
    2: [[389, 576]]
    3: [[317, 576]]
    4: [[311, 576]]
    5: [[244, 576]]
  gfp_scope_error:
    0: [490]
  not_steady_state:
    0: [[0, 106]]
    1: [[0, 102]]
    2: [[0, 83]]
    3: [[0, 101]]
    4: [[0, 98]]
    5: [[0, 115]]
position_annotations:
  dust_artifact: [4, 5]
center_z_plane:
  0: 11
  1: 10
  2: 10
  3: 10
  4: 10
  5: 10
