name: 20250227_paired40X
original_path: //allen/programs/allencell/data/proj0/508/752/011/de2/c25/46a/84f/fe2/278/535/1b/20250227_GE00007101_40X_ZSTACK_SLDY/20250227_GE00007101_40X_zstacks_SLDY.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250227_1b535278fe284f46ac25de2011752508
zarr_positions: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
fmsid: 1b535278fe284f46ac25de2011752508
barcode: GE00007101
cell_lines: [AICS-126]
live_or_fixed_sample: live
is_timelapse: false
microscope: 3i
objective: 40X
shear_stress_regime: 24hr_low
pixel_size_xy_in_um: 0.191
duration: 1
time_interval_in_minutes: null
flow: [[0, 0, 0.0]]
n_total_positions: 10
channel_488_index: 0
brightfield_channel_index: 1
flow_conditions:
- start: -288
  stop: 0
  shear_stress: 5.71
channel_405_index: null
channel_561_index: null
channel_640_index: null
nuclear_label_free_seg_path: null
nuclear_stain_seg_path: null
cdh5_seg_path: null
tracking_integration_fmsid: null
diffae_tracking_integration_fmsid: null
cdh5_classic_seg_tracking_manifest_fmsid: null
cdh5_classic_seg_manifest_fmsid: null
nuclei_label_free_seg_manifest_fmsid: null
live_merged_seg_features_manifest_fmsid: null
valid_timepoints: null
cell_mean_features: null
include_scenes: null
notes: ''
