name: 20250409_20X
original_path: //allen/programs/allencell/data/proj0/ac1/24e/dd5/23a/579/6f9/94c/bbc/a02/6b2/df/20250409_GE00007696_20X_timelapse_sldy/20250409_GE00007696_20X_timelapse_sldy.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250409_df6b2a02bbc94c6f957923add524eac1
fmsid: df6b2a02bbc94c6f957923add524eac1
barcode: GE00007696
cell_lines:
- AICS-126
live_or_fixed_sample: live
is_timelapse: true
microscope: 3i
shear_stress_regime: 48hr_low
use_cases: []
pixel_size_xy_in_um: 0.382
duration: 544
time_interval_in_minutes: 5.0
flow:
- - 0
  - 543
  - 5.24
n_total_positions: 6
channel_488_index: 0
brightfield_channel_index: 1
flow_condition:
- start: 0
  stop: 543
  shear_stress: 5.24
channel_405_index: null
channel_561_index: null
channel_640_index: null
nuclear_label_free_seg_path: //allen/aics/endothelial/morphological_features/segmentations/nuclear_labelfree_seg/20250409_20X
nuclear_stain_seg_path: null
nuclear_seg_manifest_fmsid: ''
tracking_integration_fmsid: 2d95d16b473d4c849c6cf744c7dc6486
diffae_tracking_integration_fmsid: 3e7dd9a9e4a040f8afb1bef774abb04b
immunofluorescence_manifest_fmsid: null
is_reference: true
valid_timepoints:
  start:
  - 190
  stop:
  - 410
cell_mean_features: ddfe344afade4031ad4e2cff70c77748
include_scenes: null
notes: cells become very crowded near end of timelapse
