name: 20250227_40X
original_path: //allen/programs/allencell/data/proj0/f44/fef/364/e57/2ea/148/c4b/d74/165/d49/0e/20250227_GE00007101_40X_timelapse_sldy/20250227_GE00007101_40X_timelapse_SLDY.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250227_0ed49165d74c4b1482eae57364feff44
fmsid: 0ed49165d74c4b1482eae57364feff44
barcode: GE00007101
cell_lines: [AICS-126]
live_or_fixed_sample: live
microscope: 3i
shear_stress_regime: 24hr_low
use_cases: [feasibility]
pixel_size_xy_in_um: 0.191
duration: 481
time_interval_in_minutes: 1.0
flow: [[0, 30, 6.16], [31, 480, 21.7]]
n_total_positions: 1
brightfield_channel_index: 1
channel_405_index: null
channel_488_index: 0
channel_561_index: null
channel_640_index: null
nuclear_label_free_seg_path: null
nuclear_stain_seg_path: null
nuclear_seg_manifest_fmsid: ''
diffae_manifest_fmsid: ''
tracking_integration_fmsid: null
diffae_tracking_integration_fmsid: null
is_reference: false
valid_timepoints: null
cell_mean_features: null
include_scenes: null
notes: USE WITH CAUTION, cell health concern
