name: 20250304_paired3iNikon_Nikon2nd
original_path: //allen/programs/allencell/data/proj0/165/a2e/91e/ce8/062/1a8/942/77d/f2e/51c/8d/20250304_20X_paired3iNikon_GE00006610.nd2
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250304_8d51cf2e77d9421a8062ce891ea2e165
fmsid: 8d51cf2e77d9421a8062ce891ea2e165
barcode: GE00006610
cell_lines: [AICS-126]
live_or_fixed_sample: fixed
microscope: Nikon
shear_stress_regime: 24hr_low
use_cases: []
pixel_size_xy_in_um: 0.392
duration: 1
time_interval_in_minutes: -1.0
flow: [[0, -1, 0.0]]
n_total_positions: 50
channel_488_index: 0
brightfield_channel_index: 1
channel_405_index: null
channel_561_index: null
channel_640_index: null
nuclear_label_free_seg_path: null
nuclear_stain_seg_path: null
nuclear_seg_manifest_fmsid: ''
diffae_manifest_fmsid: ''
tracking_integration_fmsid: null
diffae_tracking_integration_fmsid: null
immunofluorescence_manifest_fmsid: null
is_reference: false
valid_timepoints: null
cell_mean_features: null
include_scenes: null
notes: ''
