name: 20250604_20X
original_path: //allen/programs/allencell/data/proj0/7dc/bf1/ae4/52d/633/0d9/e45/2e0/f7a/08e/3f/20250604_GE00008165_sldy/20250604_GE00008165_20X_SLDY.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250604_3f08ef7a2e0e450d963352dae4bf17dc
zarr_positions: [0, 1, 2, 3, 4, 5]
fmsid: 3f08ef7a2e0e450d963352dae4bf17dc
barcode: GE00008165
cell_lines: [AICS-126]
live_or_fixed_sample: live
is_timelapse: true
microscope: 3i
objective: 20X
shear_stress_regime: 48hr_intermediate
pixel_size_xy_in_um: 0.382
duration: 577
time_interval_in_minutes: 5.0
flow: [[0, 576, 12.32]]
n_total_positions: 6
original_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
flow_conditions:
- start: -40
  stop: 576
  shear_stress: 12.32
valid_timepoints: null
include_scenes: null
notes: Flow history. Cells exposed to flow for 3h 20min prior to start of imaging.
  Cells show mixed alignment leaning towards more parallel
timepoint_annotations:
  xy_shift:
    0: [4, 5]
    1: [4, 5]
    2: [4, 5]
    3: [4, 5]
    4: [4, 5]
    5: [4, 5]
position_annotations: null
center_z_plane:
  0: 12
  1: 11
  2: 11
  3: 11
  4: 11
  5: 12
