name: 20250224_20X_Nikon
original_path: //allen/programs/allencell/data/proj0/8c9/a46/343/900/268/3e9/348/54f/81b/c69/0c/20250224_GE00006992_endo_low_to_high.nd2
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250224_0cc6981b54f3483e9268900343a468c9
fmsid: 0cc6981b54f3483e9268900343a468c9
barcode: GE00006992
cell_lines: [AICS-126]
live_or_fixed_sample: live
is_timelapse: true
microscope: Nikon
shear_stress_regime: 24hr_low-to-24hr_high
use_cases: [feasibility]
pixel_size_xy_in_um: 0.392
duration: 97
time_interval_in_minutes: 5.0
flow: [[0, 277, 5.62], [278, 576, 25.91]]
n_total_positions: 6
channel_488_index: 0
brightfield_channel_index: 1
flow_condition: [{start: 0, stop: 277, shear_stress: 5.62}, {start: 278, stop: 576,
    shear_stress: 25.91}]
channel_405_index: null
channel_561_index: null
channel_640_index: null
nuclear_label_free_seg_path: null
nuclear_stain_seg_path: null
nuclear_seg_manifest_fmsid: ''
tracking_integration_fmsid: null
diffae_tracking_integration_fmsid: null
immunofluorescence_manifest_fmsid: null
is_reference: false
valid_timepoints: null
cell_mean_features: null
include_scenes: null
notes: ''
