name: 20251022_20X
original_path: //allen/programs/allencell/data/proj0/4c8/d12/754/54e/378/bca/446/cd1/a65/c97/26/20251022_GE00009432_20X_SLDY/20251022_GE00009432_20X_SLDY.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20251022_26c97a65cd1446bca37854e754d124c8
zarr_positions: []
fmsid: 26c97a65cd1446bca37854e754d124c8
barcode: GE00009432
cell_lines: [AICS-177]
live_or_fixed_sample: live
is_timelapse: true
microscope: 3i
objective: 20X
shear_stress_regime: min
pixel_size_xy_in_um: 0.382
duration: 577
time_interval_in_minutes: 5.0
n_total_positions: 6
original_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
flow_conditions:
- start: -16
  stop: 576
  shear_stress: 6.02
include_scenes: null
notes: Timelapse imaging of isogenic control clone AICS-177 cl.12 under low SS for
  48h, Migration maybe slightly less/slower than AICS-126, Otherwise cells look good!
timepoint_annotations: null
position_annotations: null
center_z_plane: null
