name: 20250509_20X_IF1
original_path: //allen/programs/allencell/data/proj0/c9e/b8e/a12/f7a/386/5fa/648/04e/3c7/9e4/62/20250509_GE00007807_20X_sldy/20250509_GE00007807_20X_sldy.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250509_629e43c704e6485fa386f7aa12b8ec9e
zarr_positions: [0, 1]
fmsid: 629e43c704e6485fa386f7aa12b8ec9e
barcode: GE00007807
cell_lines: [AICS-126]
live_or_fixed_sample: fixed
is_timelapse: false
microscope: 3i
objective: 20X
shear_stress_regime: 24hr_high
pixel_size_xy_in_um: 0.382
duration: 1
time_interval_in_minutes: null
flow: [[0, 0, 20.8]]
n_total_positions: 2
original_channel_indices:
  brightfield: 4
  channel_488: 1
  channel_405: 0
  channel_561: 2
  channel_640: 3
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: 2
  channel_561: 3
  channel_640: 4
flow_conditions:
- start: -288
  stop: 0
  shear_stress: 20.8
valid_timepoints: null
include_scenes: null
notes: image content NucViolet,EGFP_CDH5,SOX17,SMAD1,BF
