name: 20250509_20X_IF2
original_path: //allen/programs/allencell/data/proj0/cb6/ba2/cb5/e9d/ebb/9fb/947/6e1/736/d87/82/20250509_GE00007808_20X_sldy/20250509_GE00007808_20X_sldy.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250509_82d877366e19479fbebbe9dcb5ba2cb6
zarr_positions: [0, 1]
fmsid: 82d877366e19479fbebbe9dcb5ba2cb6
barcode: GE00007808
cell_lines: [AICS-126]
live_or_fixed_sample: fixed
is_timelapse: false
microscope: 3i
objective: 20X
shear_stress_regime: 24hr_no_flow
pixel_size_xy_in_um: 0.382
duration: 1
time_interval_in_minutes: null
flow: [[0, 0, 0.0]]
n_total_positions: 2
original_channel_indices:
  brightfield: 4
  channel_488: 1
  channel_405: 0
  channel_561: 2
  channel_640: 3
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: 2
  channel_561: 3
  channel_640: 4
flow_conditions:
- start: -288
  stop: 0
  shear_stress: 0.0
valid_timepoints: null
include_scenes: null
notes: image content NucViolet,EGFP_CDH5,SOX17,SMAD1,BF
