name: 20250402_20X
date: '20250402'
original_path: //allen/programs/allencell/data/proj0/269/7fb/469/95b/849/efa/440/8f1/b7d/e37/90/20250402_GE00007594_20X_timelapse_sldy/20250402_GE00007594_20X_timelapse_sldy.sldy
zarr_positions: [0, 1, 2, 3, 4, 5]
fmsid: 90e37b7d8f1440efa84995b4697fb269
barcode: GE00007594
cell_lines: [AICS-126 cl. 41]
live_or_fixed_sample: live
is_timelapse: true
microscope: 3i
objective: 20X
shear_stress_regime: min
pixel_size_xy_in_um: 0.382
duration: 571
time_interval_in_minutes: 5.0
n_total_positions: 6
original_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
channel_names: [VE-cadherin_mEGFP, Brightfield]
flow_conditions:
- start: -22
  stop: 570
  shear_stress: 5.85
include_scenes: null
notes: cells become extremely crowded at end of video
replicate_number: 2
timepoint_annotations:
  auto_bf_scope_error:
    0: [146, 208]
    1: [56, 179, 210, 277, 288, 537, 546, 552, 556]
    2: [235, 330, 346, 486, 512, 552]
    3: [0, 191, 208, 544, 552, 559]
    4: [554]
    5: [1, 37, 80, 136, 495, 511, 554, 559]
  auto_bf_temp_artifact:
    0: [3, 100, 210, 495, 541]
    1: [8, 96, 372, 511, 556, 560]
    2: [7, 98, 515]
    3: [0, 11, 167, 237, 266, 272, 555]
    4: [1, 536, 559]
    5: [1, 7, 399, 495, 541]
  auto_gfp_scope_error:
    0: []
    1: []
    2: []
    3: []
    4: []
    5: []
  bf_temp_artifact:
    0: [46, 495, 541]
    1: [556]
    2: []
    3: []
    4: [308]
    5: [1]
  cell_piling:
    0: [[281, 570]]
    1: [[254, 570]]
    2: [[274, 570]]
    3: [[293, 570]]
    4: [[223, 570]]
    5: [[215, 570]]
  not_steady_state:
    0: [[0, 70]]
    1: [[0, 52]]
    2: [[0, 69]]
    3: [[0, 48]]
    4: [[0, 24]]
    5: [[0, 54]]
position_annotations:
  dust_artifact: [5]
center_z_plane:
  0: 11
  1: 10
  2: 10
  3: 10
  4: 10
  5: 9
