name: 20250428_20X
original_path: //allen/programs/allencell/data/proj0/edd/2f7/355/756/836/cd9/f4c/ba9/027/6aa/05/20250428_GE00007803_20X_sldy/20250428_GE00007803_20X_sldy.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250428_056aa027ba9f4ccd98367563552f7edd
zarr_positions: [0, 1, 2, 3, 4, 5]
fmsid: 056aa027ba9f4ccd98367563552f7edd
barcode: GE00007803
cell_lines: [AICS-126]
live_or_fixed_sample: live
is_timelapse: true
microscope: 3i
objective: 20X
shear_stress_regime: intermediate
pixel_size_xy_in_um: 0.382
duration: 577
time_interval_in_minutes: 5.0
flow: [[0, 577, 8.6]]
n_total_positions: 6
channel_488_index: 0
brightfield_channel_index: 1
flow_conditions:
- start: -14
  stop: 577
  shear_stress: 8.6
channel_405_index: null
channel_561_index: null
channel_640_index: null
nuclear_label_free_seg_path: //allen/aics/endothelial/morphological_features/segmentations/nuclear_labelfree_seg/20250428_20X
nuclear_stain_seg_path: null
cdh5_seg_path: //allen/aics/endothelial/morphological_features/segmentations/cdh5_classic_seg/20250428_20X
valid_timepoints:
  start: [217]
  stop: [351]
include_scenes: null
notes: This is an intermediate flow dataset. There cells are very crowded by the end
  of the movie.
