name: 20250716_20X
date: '20250716'
original_path: //allen/programs/allencell/data/proj0/53e/924/468/8e5/226/eab/248/c91/2ec/8c6/32/20250716_GE00008450_20X_SLDY_2/20250716_GE00008450_20X_SLDY.sldy
zarr_positions: [0, 1, 2, 3, 4, 5]
fmsid: 328c62ecc91248eab2268e546892453e
barcode: GE00008450
cell_lines: [AICS-126 cl. 41]
live_or_fixed_sample: live
is_timelapse: true
microscope: 3i
objective: 20X
shear_stress_regime: low
pixel_size_xy_in_um: 0.382
duration: 577
time_interval_in_minutes: 5.0
n_total_positions: 6
original_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
channel_names: [VE-cadherin_mEGFP, Brightfield]
flow_conditions:
- start: -15
  stop: 576
  shear_stress: 9.01
include_scenes: null
notes: timelapse imaging of CDH5 endos under 9 dyn/cm2 shear stress. Small gap in
  monolayer appears in position 0 at ~ TP 153.
replicate_number: 2
timepoint_annotations:
  auto_bf_scope_error:
    0: [12, 13, 56, 59, 93, 226, 233, 238, 268, 278, 279, 336, 517, 524, 541, 560,
      561, 563, 568, 570]
    1: [0, 238, 278, 279, 353, 561, 563]
    2: [0, 50, 217, 268, 278, 279, 561, 563, 575]
    3: [3, 278, 279, 528, 541, 557, 576]
    4: [3, 226, 269, 278, 279, 289, 557, 561, 562]
    5: [226, 245, 246, 278, 279, 487, 560, 561]
  auto_bf_temp_artifact:
    0: [517, 538, 560]
    1: [0, 279, 560, 574]
    2: [278, 279, 561, 567]
    3: [3, 257, 278, 279, 557]
    4: [78, 278, 557]
    5: [0, 3, 557, 562]
  auto_gfp_scope_error:
    0: []
    1: []
    2: []
    3: []
    4: []
    5: []
  bf_scope_error:
    2: [0]
  cell_piling:
    0: [[332, 576]]
    1: [[319, 576]]
    2: [[317, 576]]
    3: [[370, 576]]
    4: [[316, 576]]
    5: [[411, 576]]
  not_steady_state:
    0: [[0, 163]]
    1: [[0, 92]]
    2: [[0, 104]]
    3: [[0, 90]]
    4: [[0, 117]]
    5: [[0, 113]]
position_annotations: null
center_z_plane:
  0: 13
  1: 12
  2: 12
  3: 12
  4: 12
  5: 13
