name: 20251125_20X_live
date: '20251125'
original_path: //allen/programs/allencell/data/proj0/311/06e/d9d/431/73e/f88/54f/ce5/289/117/b7/20251125_GE00009675_PreFix_SLDY/20251125_GE00009675_PreFix_SLDY.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20251125_b7117289ce554ff8873e431d9d06e311
zarr_positions: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
fmsid: b7117289ce554ff8873e431d9d06e311
barcode: GE00009675
cell_lines: [AICS-126]
live_or_fixed_sample: live
is_timelapse: false
microscope: 3i
objective: 20X
shear_stress_regime: min
pixel_size_xy_in_um: 0.382
duration: 1
time_interval_in_minutes: null
n_total_positions: 10
original_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
channel_names: [EGFP, BF]
flow_conditions:
- start: -298
  stop: 0
  shear_stress: 5.7
include_scenes: null
notes: Collect high SS 24h live/fixed paired data after 24h high SS to match live
  imaging to fixed
timepoint_annotations:
  auto_bf_scope_error:
    0: []
    1: []
    2: []
    3: []
    4: []
    5: []
    6: []
    7: []
    8: []
    9: []
  auto_bf_temp_artifact:
    0: []
    1: []
    2: []
    3: []
    4: []
    5: []
    6: []
    7: []
    8: []
    9: []
  auto_gfp_scope_error:
    0: []
    1: []
    2: []
    3: []
    4: []
    5: []
    6: []
    7: []
    8: []
    9: []
position_annotations: null
center_z_plane:
  0: 12
  1: 11
  2: 10
  3: 10
  4: 11
  5: 11
  6: 10
  7: 11
  8: 11
  9: 10
