name: 20250428_20X
date: '20250428'
original_path: //allen/programs/allencell/data/proj0/edd/2f7/355/756/836/cd9/f4c/ba9/027/6aa/05/20250428_GE00007803_20X_sldy/20250428_GE00007803_20X_sldy.sldy
zarr_positions: [0, 1, 2, 3, 4, 5]
fmsid: 056aa027ba9f4ccd98367563552f7edd
barcode: GE00007803
cell_lines: [AICS-126 cl. 41]
live_or_fixed_sample: live
is_timelapse: true
microscope: 3i
objective: 20X
shear_stress_regime: low
pixel_size_xy_in_um: 0.382
duration: 577
time_interval_in_minutes: 5.0
n_total_positions: 6
original_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
channel_names: [VE-cadherin_mEGFP, Brightfield]
flow_conditions:
- start: -14
  stop: 577
  shear_stress: 8.6
include_scenes: null
notes: Caution, some patchiness occurs after TP489 & cells are very crowded by the
  end of the movie. No other artifacts noted.
timepoint_annotations:
  auto_bf_scope_error:
    0: [24, 114, 240, 275]
    1: [23, 316, 556, 564]
    2: [77]
    3: [50, 81, 148]
    4: [12, 43, 60, 80, 160, 262, 551]
    5: [52, 85, 120, 262, 381, 469, 551]
  auto_bf_temp_artifact:
    0: [265]
    1: []
    2: [330, 556]
    3: []
    4: [258, 259, 301]
    5: [3, 201, 319]
  auto_gfp_scope_error:
    0: []
    1: []
    2: []
    3: []
    4: []
    5: []
  cell_piling:
    0: [[472, 576]]
    1: [[403, 576]]
    2: [[482, 576]]
    3: [[475, 576]]
    4: [[315, 576]]
    5: [[340, 576]]
  not_steady_state:
    0: [[0, 172]]
    1: [[0, 150]]
    2: [[0, 180]]
    3: [[0, 202]]
    4: [[0, 159]]
    5: [[0, 182]]
position_annotations: null
center_z_plane:
  0: 11
  1: 12
  2: 12
  3: 12
  4: 12
  5: 12
