name: 20250929_20X_IF6
original_path: //allen/programs/allencell/data/proj0/dc0/139/921/d59/370/368/640/158/0a4/8c6/69/20250929_GE00009112_6_20X_SLDY/20250929_GE00009112_6_20X_SLDY.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250929_698c60a4158640368370d59921139dc0
zarr_positions: [0, 1, 2, 3, 4, 5]
fmsid: 698c60a4158640368370d59921139dc0
barcode: GE00009112
cell_lines: [AICS-126]
live_or_fixed_sample: fixed
is_timelapse: false
microscope: 3i
objective: 20X
shear_stress_regime: min_to_max
pixel_size_xy_in_um: 0.382
duration: 1
time_interval_in_minutes: null
n_total_positions: 7
original_channel_indices:
  brightfield: 4
  channel_488: 1
  channel_405: 0
  channel_561: 2
  channel_640: 3
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: 2
  channel_561: 3
  channel_640: 4
flow_conditions:
- start: -433
  stop: -145
  shear_stress: 5.97
- start: -144
  stop: 0
  shear_stress: 22.07
include_scenes: null
notes: Fix & stain cells for SMAD1 and SOX17 after 24h Low SS and 12h High SS
timepoint_annotations: null
position_annotations: null
center_z_plane: null
