name: 20250415_SlideE_20X
original_path: //allen/programs/allencell/data/proj0/653/104/f43/da2/33f/5aa/e46/507/826/cfe/db/20250416_GE00007101_slideE_20X_sldy/20250416_GE00007101_slideE_20X_sldy.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250415_dbcfe826507e465aa33fda2f43104653
fmsid: dbcfe826507e465aa33fda2f43104653
barcode: GE00007101
cell_lines: [AICS-126]
live_or_fixed_sample: fixed
microscope: 3i
shear_stress_regime: low-to-high
use_cases: []
pixel_size_xy_in_um: 0.382
duration: 1
time_interval_in_minutes: -1.0
flow: [[0, -1, 0.0]]
n_total_positions: 50
channel_488_index: 1
brightfield_channel_index: 2
channel_405_index: 0
channel_561_index: null
channel_640_index: null
nuclear_label_free_seg_path: null
nuclear_stain_seg_path: null
nuclear_seg_manifest_fmsid: ''
tracking_integration_fmsid: null
diffae_tracking_integration_fmsid: null
immunofluorescence_manifest_fmsid: null
cdh5_classic_seg_tracking_manifest_fmsid: null
cdh5_classic_seg_manifest_fmsid: null
nuclei_label_free_seg_manifest_fmsid: null
live_merged_seg_features_manifest_fmsid: null
is_reference: false
valid_timepoints: null
cell_mean_features: null
include_scenes: null
notes: ''
