name: 20250509_20X_IF12
original_path: //allen/programs/allencell/data/proj0/b7c/31f/492/453/0be/f3b/54a/f74/4f8/688/d8/20250509_GE00007806_20X_sldy_/20250509_GE00007806_20X_sldy.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250509_d86884f8f7454af3b0be45349231fb7c
zarr_positions: [0, 1]
fmsid: d86884f8f7454af3b0be45349231fb7c
barcode: GE00007806
cell_lines: [AICS-126]
live_or_fixed_sample: fixed
is_timelapse: false
microscope: 3i
objective: 20X
shear_stress_regime: 24hr_low
pixel_size_xy_in_um: 0.382
duration: 1
time_interval_in_minutes: null
flow: [[0, 0, 5.82]]
n_total_positions: 2
channel_488_index: 1
brightfield_channel_index: 4
flow_conditions:
- start: -288
  stop: 0
  shear_stress: 5.82
channel_405_index: 0
channel_561_index: 2
channel_640_index: 3
nuclear_label_free_seg_path: null
nuclear_stain_seg_path: //allen/aics/endothelial/morphological_features/segmentations/nuclear_stain_seg/20250509_20X_IF12
cdh5_seg_path: null
valid_timepoints: null
include_scenes: null
notes: image content NucViolet,EGFP_CDH5,SOX17,SMAD1,BF
