name: 20250509_20X_IF2
original_path: //allen/programs/allencell/data/proj0/cb6/ba2/cb5/e9d/ebb/9fb/947/6e1/736/d87/82/20250509_GE00007808_20X_sldy/20250509_GE00007808_20X_sldy.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250509_82d877366e19479fbebbe9dcb5ba2cb6
fmsid: 82d877366e19479fbebbe9dcb5ba2cb6
barcode: GE00007808
cell_lines: [AICS-126]
live_or_fixed_sample: fixed
microscope: 3i
shear_stress_regime: 24hr_no_flow
use_cases: [immunofluorescence]
pixel_size_xy_in_um: 0.382
duration: 1
time_interval_in_minutes: -1.0
flow: [[0, -1, 0.0]]
n_total_positions: 2
channel_488_index: 1
brightfield_channel_index: 4
channel_405_index: 0
channel_561_index: 2
channel_640_index: 3
nuclear_label_free_seg_path: null
nuclear_stain_seg_path: //allen/aics/endothelial/morphological_features/segmentations/nuclear_stain_seg/20250509_20X_IF2
nuclear_seg_manifest_fmsid: ''
diffae_manifest_fmsid: 8ce1d2ba8c7a41ac914dca2f1ca28a8f
tracking_integration_fmsid: null
diffae_tracking_integration_fmsid: ''
immunofluorescence_manifest_fmsid: cd1e43f0ef744cb7be42d271de3c0055
is_reference: false
valid_timepoints: null
cell_mean_features: null
include_scenes: null
notes: image content NucViolet,EGFP_CDH5,SOX17,SMAD1,BF
