name: 20250611_20X
original_path: //allen/programs/allencell/data/proj0/879/601/058/9cc/d15/c29/e42/30a/5d5/261/a3/20250611_GE00008200_20X_sldy/20250611_GE00008200_20X_SLDY_2.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250611_a32615d530ae42c29d159cc058601879
zarr_positions: [0, 1, 2, 3, 4, 5]
fmsid: a32615d530ae42c29d159cc058601879
barcode: GE00008200
cell_lines: [AICS-126]
live_or_fixed_sample: live
is_timelapse: true
microscope: 3i
objective: 20X
shear_stress_regime: 48hr_high
pixel_size_xy_in_um: 0.382
duration: 577
time_interval_in_minutes: 5.0
flow: [[0, 576, 21.35]]
n_total_positions: 6
channel_488_index: 0
brightfield_channel_index: 1
flow_conditions:
- start: -15
  stop: 576
  shear_stress: 21.35
channel_405_index: null
channel_561_index: null
channel_640_index: null
cdh5_seg_path: //allen/aics/endothelial/morphological_features/segmentations/cdh5_classic_seg/20250611_20X
valid_timepoints: null
include_scenes: null
notes: Flow history. Under flow for 1h 15min prior to start of imaging. Cells become
  overgrown earlier than in previous timelapse experiments (~25h)
