name: 20250929_IF3
original_path: //allen/programs/allencell/data/proj0/e94/e38/834/352/7fb/e7a/545/efd/70d/a45/dd/20250929_GE00009109_3_20X_SLDY/20250929_GE00009109_3_20X_SLDY.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250929_dda4570defd545e7a7fb352834e38e94
zarr_positions: [0, 1, 2, 3, 4, 5, 6]
fmsid: dda4570defd545e7a7fb352834e38e94
barcode: GE00009109
cell_lines: [AICS-126]
live_or_fixed_sample: fixed
is_timelapse: false
microscope: 3i
objective: 20X
shear_stress_regime: medium
pixel_size_xy_in_um: 0.382
duration: 1
time_interval_in_minutes: null
n_total_positions: 7
original_channel_indices:
  brightfield: 4
  channel_488: 1
  channel_405: 0
  channel_561: 2
  channel_640: 3
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: 2
  channel_561: 3
  channel_640: 4
flow_conditions:
- start: -288
  stop: 0
  shear_stress: 11.74
include_scenes: null
notes: Fix & stain for SMAD1 and SOX17 Intermediate SS (goal 12 dyn/cm2) for 24h prior
  to fixation
timepoint_annotations: null
position_annotations: null
center_z_plane: null
