name: 20250115_paired3iNikon_3i1st
original_path: //allen/programs/allencell/data/proj0/61a/26d/0a1/572/3e8/f08/14d/4b7/926/e36/51/20250115_GE00006392_20X_pairedNikon_sldy/20250115_GE00006392_20X_paired_sldy.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250115_51e369264b714df083e85720a126d61a
fmsid: 51e369264b714df083e85720a126d61a
barcode: GE00006392
cell_lines: [AICS-126]
live_or_fixed_sample: live
microscope: 3i
shear_stress_regime: 24hr_low-to-24hr_high
use_cases: [model_training]
pixel_size_xy_in_um: 0.382
duration: 1
time_interval_in_minutes: -1.0
flow: [[0, 288, 6.37], [289, 576, 27.83], [576, 579, 0.0]]
n_total_positions: 12
brightfield_channel_index: 1
channel_405_index: null
channel_488_index: 0
channel_561_index: null
channel_640_index: null
nuclear_label_free_seg_path: null
nuclear_stain_seg_path: null
nuclear_seg_manifest_fmsid: ''
diffae_manifest_fmsid: ''
tracking_integration_fmsid: null
diffae_tracking_integration_fmsid: null
immunofluorescence_manifest_fmsid: null
is_reference: false
valid_timepoints: null
cell_mean_features: null
include_scenes: null
notes: Due to complications with Z focus when trying to get a 4x3 tiled region, 3
  positions each consisting of 4x1 tilings were taken instead.
