name: 20250227_paired20X
original_path: //allen/programs/allencell/data/proj0/40a/c58/7ca/53c/c3c/178/c48/155/684/78a/35/20250227_GE00007101_20X_ZSTACK_SLDY/20250227_GE00007101_20X_zstacks_SLDY.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250227_3578a684155c48178c3c53c7cac5840a
zarr_positions: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
fmsid: 3578a684155c48178c3c53c7cac5840a
barcode: GE00007101
cell_lines: [AICS-126]
live_or_fixed_sample: live
is_timelapse: false
microscope: 3i
objective: 20X
shear_stress_regime: 24hr_low
pixel_size_xy_in_um: 0.382
duration: 1
time_interval_in_minutes: null
n_total_positions: 10
original_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
flow_conditions:
- start: -288
  stop: 0
  shear_stress: 5.71
valid_timepoints: null
include_scenes: null
notes: ''
