name: 20250509_20X_IF4
date: '20250509'
original_path: //allen/programs/allencell/data/proj0/686/cdc/936/d32/2f4/139/a4b/bdd/b5f/9ce/b2/20250509_GE00007875_20X_sldy/20250509_GE00007875_20X_sldy.sldy
zarr_positions: [0, 1]
fmsid: b29ceb5fbdda4b1392f4d32936cdc686
barcode: GE00007875
cell_lines: [AICS-126 cl. 41]
live_or_fixed_sample: fixed
is_timelapse: false
microscope: 3i
objective: 20X
shear_stress_regime: 'no'
pixel_size_xy_in_um: 0.382
duration: 1
time_interval_in_minutes: null
n_total_positions: 2
original_channel_indices:
  brightfield: 4
  channel_488: 1
  channel_405: 0
  channel_561: 2
  channel_640: 3
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: 2
  channel_561: 3
  channel_640: 4
channel_names: [VE-cadherin_mEGFP, Brightfield, Nuclei_NucViolet, SOX17_Alexa555,
  NR2F2_Alexa647]
flow_conditions:
- start: -288
  stop: 0
  shear_stress: 0.0
include_scenes: null
notes: image content NucViolet,EGFP_CDH5,SOX17,NR2F2,BF
replicate_number: null
stability_category: null
timepoint_annotations:
  auto_bf_scope_error:
    0: [0]
    1: []
  auto_bf_temp_artifact:
    0: []
    1: []
position_annotations: null
center_z_plane:
  0: 11
  1: 11
