name: 20250331_20X
original_path: //allen/programs/allencell/data/proj0/edc/ed9/2ac/52b/a30/c1a/b40/027/33e/c86/92/20250331_GE00007559_20X_timelapse_sldy/20250331_GE00007559_20X_timelapse_sldy.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250331_92c8633e027b40c1aa3052b2aced9edc
zarr_positions: [0, 1, 2, 3, 4, 5]
fmsid: 92c8633e027b40c1aa3052b2aced9edc
barcode: GE00007559
cell_lines: [AICS-126]
live_or_fixed_sample: live
is_timelapse: true
microscope: 3i
objective: 20X
shear_stress_regime: 24hr_high-to-24hr_low
pixel_size_xy_in_um: 0.382
duration: 577
time_interval_in_minutes: 5.0
flow: [[0, 275, 24.39], [276, 577, 5.83]]
n_total_positions: 6
channel_488_index: 0
brightfield_channel_index: 1
flow_conditions:
- start: -19
  stop: 275
  shear_stress: 24.39
- start: 276
  stop: 577
  shear_stress: 5.83
channel_405_index: null
channel_561_index: null
channel_640_index: null
nuclear_label_free_seg_path: //allen/aics/endothelial/morphological_features/segmentations/nuclear_labelfree_seg/20250331_20X
nuclear_stain_seg_path: null
cdh5_seg_path: //allen/aics/endothelial/morphological_features/segmentations/cdh5_classic_seg/20250331_20X
valid_timepoints: null
include_scenes: null
notes: Frame of flow switch was ~275.
