name: 20250716_20X
original_path: //allen/programs/allencell/data/proj0/53e/924/468/8e5/226/eab/248/c91/2ec/8c6/32/20250716_GE00008450_20X_SLDY_2/20250716_GE00008450_20X_SLDY.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250716_328c62ecc91248eab2268e546892453e
zarr_positions: [0, 1, 2, 3, 4, 5]
fmsid: 328c62ecc91248eab2268e546892453e
barcode: GE00008450
cell_lines: [AICS-126]
live_or_fixed_sample: live
is_timelapse: true
microscope: 3i
objective: 20X
shear_stress_regime: intermediate
pixel_size_xy_in_um: 0.382
duration: 577
time_interval_in_minutes: 0.0
n_total_positions: 6
original_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
flow_conditions:
- start: 15
  stop: 576
  shear_stress: 9.01
valid_timepoints: null
include_scenes: null
notes: timelapse imaging of CDH5 endos under 9 dyn/cm2 shear stress
