name: 20250204_pairedPostFixation
original_path: //allen/programs/allencell/data/proj0/1d2/d22/95a/5e2/a5c/718/64f/7b9/2ee/c98/62/20250204_GE00006610_20X_POST_FIX_sldy/GE00006610_20250204_20X_POST_FIX_sldy.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250204_62c982ee7b964f718a5c5e295ad221d2
fmsid: 62c982ee7b964f718a5c5e295ad221d2
barcode: GE00006610
cell_lines: [AICS-126]
live_or_fixed_sample: fixed
microscope: 3i
shear_stress_regime: 24hr_low
use_cases: [model_training]
pixel_size_xy_in_um: 0.382
duration: 1
time_interval_in_minutes: -1.0
flow: [[0, 288, 5.71]]
n_total_positions: 10
channel_488_index: 0
brightfield_channel_index: 1
channel_405_index: null
channel_561_index: null
channel_640_index: null
nuclear_label_free_seg_path: null
nuclear_stain_seg_path: null
nuclear_seg_manifest_fmsid: ''
diffae_manifest_fmsid: ''
tracking_integration_fmsid: null
diffae_tracking_integration_fmsid: null
immunofluorescence_manifest_fmsid: null
is_reference: false
valid_timepoints: null
cell_mean_features: null
include_scenes: null
notes: ''
