name: 20251103_20X_IF5
original_path: //allen/programs/allencell/data/proj0/655/dc7/1b4/af1/17b/69b/646/b7a/4ba/fd4/5c/20251103_GE00009358_5_SLDY/20251103_GE00009358_5_SLDY.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20251103_5cfd44bab7a64669b17baf11b4dc7655
zarr_positions: [0, 1, 2, 3, 4, 5]
fmsid: 5cfd44bab7a64669b17baf11b4dc7655
barcode: GE00009358
cell_lines: [AICS-126]
live_or_fixed_sample: live
is_timelapse: false
microscope: 3i
objective: 20X
shear_stress_regime: max_to_min
pixel_size_xy_in_um: 0.382
duration: 1
time_interval_in_minutes: null
n_total_positions: 6
original_channel_indices:
  brightfield: 4
  channel_488: 1
  channel_405: 0
  channel_561: 2
  channel_640: 3
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: 2
  channel_561: 3
  channel_640: 4
flow_conditions:
- start: -385
  stop: -97
  shear_stress: 18.54
- start: -96
  stop: 0
  shear_stress: 6.02
include_scenes: null
notes: Fix & stain cells for SMAD1 and SOX17 after 24h High SS + 8h Low SS
timepoint_annotations:
  auto_bf_scope_error:
    0: []
    1: []
    2: []
    3: []
    4: []
    5: []
  auto_bf_temp_artifact:
    0: []
    1: []
    2: []
    3: []
    4: []
    5: [0]
  auto_gfp_scope_error:
    0: []
    1: []
    2: []
    3: []
    4: []
    5: []
position_annotations: null
center_z_plane:
  0: 8
  1: 8
  2: 8
  3: 7
  4: 6
  5: 6
