name: 20250509_20X_IF10
original_path: //allen/programs/allencell/data/proj0/d16/695/e41/afb/adf/21b/e43/497/3c6/75c/89/20250509_GE00007881_20X_sldy/20250509_GE00007881_20X_sldy.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250509_8975c3c6497e4321badfafbe41695d16
fmsid: 8975c3c6497e4321badfafbe41695d16
barcode: GE00007881
cell_lines: [AICS-126]
live_or_fixed_sample: fixed
is_timelapse: false
microscope: 3i
shear_stress_regime: 24hr_high
use_cases: [immunofluorescence]
pixel_size_xy_in_um: 0.382
duration: 1
time_interval_in_minutes: null
flow: [[0, 0, 23.67]]
n_total_positions: 2
channel_488_index: 1
brightfield_channel_index: 4
channel_405_index: 0
channel_561_index: 2
channel_640_index: 3
nuclear_label_free_seg_path: null
nuclear_stain_seg_path: //allen/aics/endothelial/morphological_features/segmentations/nuclear_stain_seg/20250509_20X_IF10
nuclear_seg_manifest_fmsid: ''
tracking_integration_fmsid: null
diffae_tracking_integration_fmsid: ''
immunofluorescence_manifest_fmsid: 6ffdd784c8544cbdba6c60c6b0f027e5
is_reference: false
valid_timepoints: null
cell_mean_features: null
include_scenes: null
notes: image content NucViolet,EGFP_CDH5,SOX17,NR2F2,BF
