name: '20250730_4'
original_path: //allen/aics/endothelial/img_data/20250730_BF_Variation/BF_Variations_20250730_4_sldy/BF_Variations_20250730_4_sldy.sldy
zarr_path: //allen/aics/users/chantelle.leveille/repos/cellsmap2/cellsmap/results/zarr_conversion/20250730_4
zarr_positions: [0, 1, 2, 3, 4, 5]
fmsid: '4'
barcode: GE00008553
cell_lines: [AICS-126]
live_or_fixed_sample: live
is_timelapse: false
microscope: 3i
objective: 20X
shear_stress_regime: no_flow
pixel_size_xy_in_um: 0.382
duration: 1
time_interval_in_minutes: 0.0
flow: [[0, 0, 0.0]]
n_total_positions: 6
channel_488_index: 0
brightfield_channel_index: 1
flow_conditions: []
channel_405_index: null
channel_561_index: null
channel_640_index: null
nuclear_label_free_seg_path: null
nuclear_stain_seg_path: null
nuclear_seg_manifest_fmsid: null
cdh5_seg_path: null
tracking_integration_fmsid: null
diffae_tracking_integration_fmsid: null
immunofluorescence_manifest_fmsid: null
cdh5_classic_seg_tracking_manifest_fmsid: null
cdh5_classic_seg_manifest_fmsid: null
nuclei_label_free_seg_manifest_fmsid: null
live_merged_seg_features_manifest_fmsid: null
valid_timepoints: null
cell_mean_features: null
include_scenes: null
notes: ''
