name: 20250115_paired3iNikon_Nikon2nd
original_path: //allen/programs/allencell/data/proj0/70f/715/e49/48d/5f0/1e8/c49/2b0/c0a/9e8/ec/GE00006392_20250115_endo_from_3i_imaged_on_nikon_piezo.nd2
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250115_ec9e8c0a2b0c491e85f048de4971570f
fmsid: ec9e8c0a2b0c491e85f048de4971570f
barcode: GE00006392
cell_lines: [AICS-126]
live_or_fixed_sample: live
microscope: Nikon
shear_stress_regime: 24hr_low-to-24hr_high
pixel_size_xy_in_um: 0.325
duration: 1
time_interval_in_minutes: -1.0
flow: [[0, 288, 6.37], [289, 576, 27.83], [576, 579, 0.0]]
n_total_positions: 1
channel_488_index: 0
brightfield_channel_index: 1
channel_405_index: null
channel_561_index: null
channel_640_index: null
nuclear_label_free_seg_path: null
nuclear_stain_seg_path: null
nuclear_seg_manifest_fmsid: ''
tracking_integration_fmsid: null
diffae_tracking_integration_fmsid: null
immunofluorescence_manifest_fmsid: null
valid_timepoints: null
cell_mean_features: null
include_scenes: null
notes: ''
