name: 20250509_20X_IF6
date: '20250509'
original_path: //allen/programs/allencell/data/proj0/650/03c/090/038/d21/7eb/742/89d/ca2/c9f/b5/20250509_GE00007877_20X_sldy/20250509_GE00007877_20X_sldy.sldy
zarr_positions: [0, 1]
fmsid: b5c9fca289d7427ebd2103809003c650
barcode: GE00007877
cell_lines: [AICS-126 cl. 41]
live_or_fixed_sample: fixed
is_timelapse: false
microscope: 3i
objective: 20X
shear_stress_regime: min
pixel_size_xy_in_um: 0.382
duration: 1
time_interval_in_minutes: null
n_total_positions: 2
original_channel_indices:
  brightfield: 4
  channel_488: 1
  channel_405: 0
  channel_561: 2
  channel_640: 3
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: 2
  channel_561: 3
  channel_640: 4
channel_names: [VE-cadherin_mEGFP, Brightfield, NucViolet, SOX17, NR2F2]
flow_conditions:
- start: -288
  stop: 0
  shear_stress: 5.98
include_scenes: null
notes: image content NucViolet,EGFP_CDH5,SOX17,NR2F2,BF
timepoint_annotations:
  auto_bf_scope_error:
    0: [0]
    1: []
  auto_bf_temp_artifact:
    0: []
    1: []
position_annotations: null
center_z_plane:
  0: 8
  1: 9
