name: 20260302_20X
date: '20260302'
original_path: //allen/programs/allencell/data/proj0/427/012/f3b/00a/ba0/f7b/447/b24/3b0/cfa/e9/20260302_GE00010391_20X_SLDY/20260302_GE00010391_20X_SLDY.sldy
zarr_positions: [0, 1, 2, 3, 4, 5]
fmsid: e9cfa3b0b24447f7bba000af3b012427
barcode: GE00010391
cell_lines: [AICS-126 cl. 41]
live_or_fixed_sample: live
is_timelapse: true
microscope: 3i
objective: 20X
shear_stress_regime: high
pixel_size_xy_in_um: 0.382
duration: 577
time_interval_in_minutes: 5.0
n_total_positions: 6
original_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
channel_names: [VE-cadherin_mEGFP, Brightfield]
flow_conditions:
- start: -19
  stop: 576
  shear_stress: 15.6
include_scenes: null
notes: Debris in FOVs 1, 2, 5, bottom-right FOV 4, bottom FOV 6 (1-indexed) stuck
  to monolayer. No brightness flickering or bubbles. GFP looks good, no gaps.
replicate_number: 9
timepoint_annotations:
  auto_bf_scope_error:
    0: [52, 249, 250, 260, 333]
    1: [250]
    2: [250, 277]
    3: [250, 542]
    4: [21]
    5: [250, 287]
  auto_bf_temp_artifact:
    0: [260]
    1: []
    2: []
    3: []
    4: []
    5: []
  auto_gfp_scope_error:
    0: []
    1: []
    2: []
    3: []
    4: []
    5: []
  cell_piling:
    0: [[384, 576]]
    1: [[384, 576]]
    2: [[384, 576]]
    3: [[384, 576]]
    4: [[384, 576]]
    5: [[384, 576]]
  not_steady_state:
    0: [[0, 144]]
    1: [[0, 144]]
    2: [[0, 168]]
    3: [[0, 168]]
    4: [[0, 144]]
    5: [[0, 144]]
position_annotations: null
center_z_plane:
  0: 11
  1: 10
  2: 10
  3: 10
  4: 10
  5: 10
