name: 20260330_20X
date: '20260330'
original_path: //allen/programs/allencell/data/proj0/298/fa8/c58/0c2/417/fb8/846/b95/490/97e/9a/20260330_GE00010724_20X_sldy_2/20260330_GE00010724_20X_sldy.sldy
zarr_positions: [0, 1, 2, 3, 4, 5]
fmsid: 9a97e490b95846fb84170c2c58fa8298
barcode: GE00010724
cell_lines: [AICS-177 cl. 12]
live_or_fixed_sample: live
is_timelapse: true
microscope: 3i
objective: 20X
shear_stress_regime: min
pixel_size_xy_in_um: 0.382
duration: 577
time_interval_in_minutes: 5.0
n_total_positions: 6
original_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
channel_names: [EGFP, BF]
flow_conditions:
- start: -23
  stop: 576
  shear_stress: 6.07
include_scenes: null
notes: AICS-177 cl.12 isogenic control, low SS 48h. GFP looks good. FOV 5 and 6 (1-indexed)
  have notable debris on slide persisting throughout timelapse. FOV 4 darkens at TP184
  just for that timepoint.
timepoint_annotations:
  auto_bf_scope_error:
    0: [43, 45, 235, 405, 441, 487, 520]
    1: [10, 45, 191, 307, 525, 556, 574]
    2: [45, 104, 177, 307, 405, 455, 574]
    3: [0, 39, 45, 181, 183, 318, 351, 567, 574]
    4: [45, 306, 318, 562]
    5: [0, 42, 45, 89, 306]
  auto_bf_temp_artifact:
    0: [87, 552]
    1: [23, 84, 144, 248, 452]
    2: [39, 96, 307, 313, 429, 482, 522, 523]
    3: [0, 52, 146, 408, 414, 446, 452, 478, 521]
    4: [36, 53, 235, 306, 403, 448, 451]
    5: [84, 185, 306, 404, 407, 446]
  auto_gfp_scope_error:
    0: []
    1: []
    2: []
    3: []
    4: []
    5: []
  bf_scope_error:
    3: [183]
  cell_piling:
    0: []
    1: []
    2: []
    3: []
    4: []
    5: []
  not_steady_state:
    0: []
    1: []
    2: []
    3: []
    4: []
    5: []
position_annotations: null
center_z_plane:
  0: 10
  1: 9
  2: 9
  3: 9
  4: 10
  5: 10
