name: 20260218_20X
date: '20260218'
original_path: //allen/programs/allencell/data/proj0/1cf/e7b/cd4/ce6/7a6/f89/443/e3e/692/87a/e3/20260218_GE00010323_20X_SLDY/20260218_GE00010323_20X_SLDY.sldy
zarr_positions: [0, 1, 2, 3, 4, 5]
fmsid: e387a692e3e443f897a6ce6cd4e7b1cf
barcode: GE00010323
cell_lines: [AICS-126 cl. 41]
live_or_fixed_sample: live
is_timelapse: true
microscope: 3i
objective: 20X
shear_stress_regime: high
pixel_size_xy_in_um: 0.382
duration: 577
time_interval_in_minutes: 5.0
n_total_positions: 6
original_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
channel_names: [EGFP, BF]
flow_conditions:
- start: -19
  stop: 576
  shear_stress: 15.72
include_scenes: null
notes: Possible early piling FOVs 1-2, cells may be stressed from high SS and low
  density. Persistent hole in monolayer right side FOV 3. BF progressively darker
  TP 200-240.
timepoint_annotations:
  auto_bf_scope_error:
    0: []
    1: []
    2: []
    3: [576]
    4: []
    5: []
  auto_bf_temp_artifact:
    0: []
    1: []
    2: []
    3: []
    4: []
    5: []
  auto_gfp_scope_error:
    0: []
    1: []
    2: []
    3: []
    4: []
    5: []
  not_steady_state:
    0: [[0, 144]]
    1: [[0, 144]]
    2: [[0, 144]]
    3: [[0, 144]]
    4: [[0, 144]]
    5: [[0, 144]]
  cell_piling:
    0: [[264, 576]]
    1: [[300, 576]]
    2: [[240, 576]]
    3: [[240, 576]]
    4: [[240, 576]]
    5: [[240, 576]]
position_annotations: null
center_z_plane:
  0: 11
  1: 10
  2: 10
  3: 10
  4: 10
  5: 11
