name: 20260128_20X
date: YYYYMMDD
original_path: //allen/programs/allencell/data/proj0/89d/de5/e35/a55/c16/46b/e4b/6d7/4ea/bd9/00/20260128_GE00009979_20X_sldy/20260128_GE00009979_20X_sldy.sldy
zarr_positions: [0, 1, 2, 3, 4, 5]
fmsid: 00bd94ea6d7e4b46bc16a55e35de589d
barcode: GE00009979
cell_lines: [AICS-126]
live_or_fixed_sample: live
is_timelapse: true
microscope: 3i
objective: 20X
shear_stress_regime: high
pixel_size_xy_in_um: 0.382
duration: 577
time_interval_in_minutes: 5.0
n_total_positions: 6
original_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
channel_names: [EGPF, BF]
flow_conditions:
- start: -18
  stop: 576
  shear_stress: 14.96
include_scenes: null
notes: ''
timepoint_annotations: null
position_annotations: null
center_z_plane: null
