name: 20260316_20X
date: '20260316'
original_path: //allen/programs/allencell/data/proj0/eaf/65b/515/afd/8ce/b58/048/008/5c2/3bd/78/20260316_GE00010557_20X_sldy/20260316_GE00010557_20X_sldy.sldy
zarr_positions: [0, 1, 2, 3, 4, 5]
fmsid: 783bd5c2008048b588ceafd51565beaf
barcode: GE00010557
cell_lines: [AICS-126 cl. 41]
live_or_fixed_sample: live
is_timelapse: true
microscope: 3i
objective: 20X
shear_stress_regime: max_to_min
pixel_size_xy_in_um: 0.382
duration: 577
time_interval_in_minutes: 5.0
n_total_positions: 6
original_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
channel_names: [EGFP, BF]
flow_conditions:
- start: -17
  stop: 269
  shear_stress: 20.94
- start: 270
  stop: 576
  shear_stress: 6.28
include_scenes: null
notes: FLAGGED CAUTION - notable gaps in monolayer in FOV 2, 4, and 5 (1-indexed).
  High to low SS 48h. Mostly perpendicular at high SS, then mostly parallel after
  low SS change. Debris bottom-right FOV 1 from start. FOV 1 flickers dark at TP22.
  FOV 2 flickers dark at TP239. FOV 4 flickers dark at TP241. FOV 2 flickers dark
  top at TP292 and TP405.
timepoint_annotations:
  auto_bf_scope_error:
    0: [13, 16, 21, 31, 498, 537]
    1: [15, 21, 29, 238, 291, 431, 537]
    2: [11, 275, 276, 500]
    3: [31, 240, 276, 532, 539]
    4: [32, 240, 275, 383, 471, 494, 539]
    5: [30, 275, 390, 413]
  auto_bf_temp_artifact:
    0: [0, 10, 537]
    1: [537]
    2: [238, 275]
    3: [240]
    4: [240]
    5: []
  auto_gfp_scope_error:
    0: []
    1: []
    2: []
    3: []
    4: []
    5: []
  cell_piling:
    0: []
    1: []
    2: []
    3: []
    4: []
    5: []
  not_steady_state:
    0: []
    1: []
    2: []
    3: []
    4: []
    5: []
position_annotations: null
center_z_plane:
  0: 8
  1: 8
  2: 8
  3: 8
  4: 9
  5: 10
