name: 20260225_20X
date: '20260225'
original_path: //allen/programs/allencell/data/proj0/ae4/7a4/47f/44e/9dc/e09/f4b/17c/3cb/afe/50/20260225_GE00010358_20X_SLDY/20260225_GE00010358_20X_sldy.sldy
zarr_positions: [0, 1, 2, 3, 4, 5]
fmsid: 50afe3cb17cf4be099dc44e47f7a4ae4
barcode: GE00010358
cell_lines: [AICS-126 cl. 41]
live_or_fixed_sample: live
is_timelapse: true
microscope: 3i
objective: 20X
shear_stress_regime: high
pixel_size_xy_in_um: 0.382
duration: 577
time_interval_in_minutes: 5.0
n_total_positions: 6
original_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
channel_names: [VE-cadherin_mEGFP, Brightfield]
flow_conditions:
- start: -15
  stop: 576
  shear_stress: 15.6
include_scenes: null
notes: Minimal early piling (some ~TP 330 FOV 3, 1-indexed), no membrane gaps. GFP
  and BF look good.

stability_category: monostable
replicate_number: 4
timepoint_annotations:
  auto_bf_scope_error:
    0: []
    1: []
    2: []
    3: [284]
    4: []
    5: []
  auto_bf_temp_artifact:
    0: [319, 554]
    1: []
    2: [263]
    3: []
    4: []
    5: []
  auto_gfp_scope_error:
    0: []
    1: []
    2: []
    3: []
    4: []
    5: []
  cell_piling:
    0: [[336, 576]]
    1: [[336, 576]]
    2: [[336, 576]]
    3: [[336, 576]]
    4: [[336, 576]]
    5: [[336, 576]]
  not_steady_state:
    0: [[0, 108]]
    1: [[0, 108]]
    2: [[0, 108]]
    3: [[0, 108]]
    4: [[0, 108]]
    5: [[0, 108]]
position_annotations: null
center_z_plane:
  0: 11
  1: 11
  2: 11
  3: 11
  4: 11
  5: 11
