name: 20260323_20X
date: '20260323'
original_path: //allen/programs/allencell/data/proj0/699/c52/bd4/57f/556/e1b/d48/89e/509/a3e/e6/20260323_GE00010625_20X_sldy/20260323_GE00010625_20X_sldy.sldy
zarr_positions: [0, 1, 2, 3, 4, 5]
fmsid: e6a3e50989ed48e1b55657fbd4c52699
barcode: GE00010625
cell_lines: [AICS-126 cl. 41]
live_or_fixed_sample: live
is_timelapse: true
microscope: 3i
objective: 20X
shear_stress_regime: max_to_min
pixel_size_xy_in_um: 0.382
duration: 577
time_interval_in_minutes: 5.0
n_total_positions: 6
original_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
channel_names: [EGFP, BF]
flow_conditions:
- start: -13
  stop: 275
  shear_stress: 19.85
- start: 276
  stop: 576
  shear_stress: 6.41
include_scenes: null
notes: High to low SS 48h. GFP looks good, perpendicular at high SS then more parallel
  at low SS. BF looks good, no flickering. Some localized crowding after transition
  to low SS but large regions go parallel.
timepoint_annotations:
  auto_bf_scope_error:
    0: [576]
    1: [560]
    2: [546, 560, 576]
    3: [548, 576]
    4: []
    5: []
  auto_bf_temp_artifact:
    0: []
    1: []
    2: [576]
    3: []
    4: []
    5: []
  auto_gfp_scope_error:
    0: []
    1: []
    2: []
    3: []
    4: []
    5: []
  cell_piling:
    0: []
    1: []
    2: []
    3: []
    4: []
    5: []
  not_steady_state:
    0: []
    1: []
    2: []
    3: []
    4: []
    5: []
position_annotations: null
center_z_plane:
  0: 11
  1: 9
  2: 9
  3: 10
  4: 10
  5: 11
