name: 20260126_20X
date: '20260126'
original_path: //allen/programs/allencell/data/proj0/c45/424/393/fa8/25c/079/347/c1a/d79/d19/ae/20260126_GE00009944_20X_SLDY/20260126_GE00009944_20X_sldy.sldy
zarr_positions: [0, 1, 2, 3, 4, 5]
fmsid: aed19d79c1a34707925cfa8393424c45
barcode: GE00009944
cell_lines: [AICS-126 cl. 41]
live_or_fixed_sample: live
is_timelapse: true
microscope: 3i
objective: 20X
shear_stress_regime: medium
pixel_size_xy_in_um: 0.382
duration: 577
time_interval_in_minutes: 5.0
n_total_positions: 6
original_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
channel_names: [VE-cadherin_mEGFP, Brightfield]
flow_conditions:
- start: -17
  stop: 576
  shear_stress: 12.04
include_scenes: null
notes: ''

stability_category: null
replicate_number: 1
timepoint_annotations:
  auto_bf_scope_error:
    0: [14, 83, 268, 276, 547, 548, 549]
    1: [14, 15, 136, 269, 283, 548]
    2: [12, 102, 548]
    3: [12, 15, 16, 265, 268]
    4: [6, 12, 15, 72, 82, 222, 264, 268]
    5: [2, 6, 12, 15, 98, 265, 268, 282]
  auto_bf_temp_artifact:
    0: [269, 547]
    1: [265, 269, 284, 548]
    2: [15, 35, 265, 269]
    3: [6, 35, 265, 269, 313]
    4: [35, 264, 265, 268]
    5: [35, 264, 265, 268, 548]
  auto_gfp_scope_error:
    0: []
    1: []
    2: []
    3: []
    4: []
    5: []
  cell_piling:
    0: [[252, 576]]
    1: [[252, 576]]
    2: [[252, 576]]
    3: [[240, 576]]
    4: [[312, 576]]
    5: [[192, 576]]
  not_steady_state:
    0: [[0, 75]]
    1: [[0, 120]]
    2: [[0, 120]]
    3: [[0, 110]]
    4: [[0, 110]]
    5: [[0, 75]]
position_annotations:
  hole_in_monolayer: [1]
center_z_plane:
  0: 11
  1: 10
  2: 10
  3: 10
  4: 10
  5: 11
