name: 20260311_20X
date: '20260311'
original_path: //allen/programs/allencell/data/proj0/c15/4b1/76c/e42/77d/f68/24a/c67/26b/53c/57/20260311_GE00010491_20X_sldy/20260311_GE00010491_20X_sldy.sldy
zarr_positions: [0]
fmsid: 5753c26bc6724af6877de4276c4b1c15
barcode: GE00010491
cell_lines: [AICS-126 cl. 41]
live_or_fixed_sample: live
is_timelapse: true
microscope: 3i
objective: 20X
shear_stress_regime: min
pixel_size_xy_in_um: 0.382
duration: 577
time_interval_in_minutes: 5.0
n_total_positions: 1
original_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
channel_names: [EGFP, BF]
flow_conditions:
- start: -20
  stop: 576
  shear_stress: 5.98
include_scenes: null
notes: Only 1 FOV timelapsed instead of 6 due to microscopy settings error. Takedown
  between TP560 and TP561. CD31-sorted AICS-126 cl.41 low SS 48h. GFP looks good,
  parallel alignment. FOV flickers dark at TP238.
timepoint_annotations:
  auto_bf_scope_error:
    0: []
  auto_bf_temp_artifact:
    0: []
  auto_gfp_scope_error:
    0: []
  not_steady_state:
    0: []
  cell_piling:
    0: []
position_annotations: null
center_z_plane: null
