name: 20260121_20X
date: '20260121'
original_path: //allen/programs/allencell/data/proj0/25f/ced/a05/025/035/3aa/b4a/720/124/75e/ff/20260121_GE00009776_20X_SLDY/20260121_GE00009776_20X_sldy.sldy
zarr_positions: [0, 1, 2, 3, 4, 5]
fmsid: ff75e124720b4a3aa035025a05ced25f
barcode: GE00009776
cell_lines: [AICS-126 cl. 41]
live_or_fixed_sample: live
is_timelapse: true
microscope: 3i
objective: 20X
shear_stress_regime: medium
pixel_size_xy_in_um: 0.382
duration: 577
time_interval_in_minutes: 5.0
n_total_positions: 6
original_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
zarr_channel_indices:
  brightfield: 1
  channel_488: 0
  channel_405: null
  channel_561: null
  channel_640: null
channel_names: [VE-cadherin_mEGFP, Brightfield]
flow_conditions:
- start: -20
  stop: 576
  shear_stress: 12.13
include_scenes: null
notes: intermediate shear stress condition 12 dyn/cm2 for 48h
replicate_number: 3
timepoint_annotations:
  auto_bf_scope_error:
    0: [0, 184]
    1: [0]
    2: [0, 266]
    3: [0, 267]
    4: []
    5: []
  auto_bf_temp_artifact:
    0: [0, 16]
    1: []
    2: []
    3: [538]
    4: []
    5: []
  auto_gfp_scope_error:
    0: []
    1: []
    2: []
    3: []
    4: []
    5: []
  cell_piling:
    5: [[456, 576]]
  not_steady_state:
    0: [[0, 175]]
    1: [[0, 170]]
    2: [[0, 165]]
    3: [[0, 180]]
    4: [[0, 148]]
    5: [[0, 150]]
position_annotations: null
center_z_plane:
  0: 10
  1: 10
  2: 10
  3: 11
  4: 12
  5: 12
