name: 20250219_40X
original_path: //allen/programs/allencell/data/proj0/cdd/e37/8a2/ad3/52d/75b/a48/3ce/9a7/6c9/57/20250219_GE00006885_40X_sldy/20250219_GE00006885_40X_sldy.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250219_576c99a73cea4875b52dad38a2e37cdd
fmsid: 576c99a73cea4875b52dad38a2e37cdd
barcode: GE00006885
live_or_fixed_sample: live
cell_lines: [AICS-126]
microscope: 3i
shear_stress_regime: 48hr_low
use_cases: []
pixel_size_xy_in_um: 0.191
duration: 1
time_interval_in_minutes: -1.0
flow: [[0, -1, 0]]
channel_488_index: 0
brightfield_channel_index: 1
n_total_positions: 32
notes: 48 hour timelapse flow was 5.6 but then slowly dropped to 3 did not keep 48
  hour timelapse
nuclear_label_free_seg_path: null
nuclear_seg_manifest_fmsid: ''
diffae_manifest_fmsid: ''
