name: 20250415_SlideA_20X
original_path: //allen/programs/allencell/data/proj0/af5/a86/27d/d28/ffd/319/b4d/ee9/0b6/9a4/80/20250415_GE00007488_slideA_20X_sldy/20250415_GE00007488_slideA_20X_sldy.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250415_809a40b6ee9b4d319ffdd2827da86af5
fmsid: 809a40b6ee9b4d319ffdd2827da86af5
barcode: GE00007488
cell_lines: [AICS-126]
live_or_fixed_sample: fixed
microscope: 3i
shear_stress_regime: intermediate
use_cases: []
pixel_size_xy_in_um: 0.382
duration: 1
time_interval_in_minutes: -1.0
flow: [[0, -1, 0]]
channel_488_index: 1
brightfield_channel_index: 2
channel_405_index: 0
nuclear_seg_manifest_fmsid: ''
n_total_positions: 50
nuclear_label_free_seg_path: null
diffae_manifest_fmsid: ''
