import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
import pandas as pd

pd.options.mode.chained_assignment = None  # default='warn'

# input type should be columns of pd.DataFrame
def simple_linear_classifier(X: pd.Series, Y: pd.Series) -> pd.Series:
  Z = 3/2. * X - 0.6
  return Z > Y

def get_outliers(data: pd.DataFrame) -> pd.DataFrame:
    # find outlier crops
    data['outlier'] = simple_linear_classifier(data['1'], data['4'])
    return data

def remove_outliers(data:pd.DataFrame) -> pd.DataFrame:
    # we know the low flow dataset has lots of bubbles, fit a bubble prediction model here and apply on other movies
    data = data[~data.outlier]
    return data

def get_pca_reference(df:pd.DataFrame) -> pd.DataFrame:
    '''Select reference timepoints for PCA based on the following criteria:
    - 20241120: all timepoints
    - 20241203: all timepoints
    - 20241210 (no-flow data): timepoints right after feeding
    '''
    if 'dataset_name' not in df.columns:
        raise ValueError('Data must have a column for dataset_name')
    df['pca_ref'] = df.dataset_name.str.contains('20241120') | df.dataset_name.str.contains('20241203')
    # select no flow timepoints right after feeding
    df.loc[df.dataset_name.str.contains('20241210') & (df['T'] > 300) & (df['T'] < 450), 'pca_ref'] = True
    df.loc[df.dataset_name.str.contains('20241217') & (df['T'] < 100), 'pca_ref'] = True
    df.loc[df.dataset_name.str.contains('20241217') & (df['T'] >300) & (df['T'] < 420), 'pca_ref'] = True
    return df[df.pca_ref]

def fit_pca(data: pd.DataFrame, num_pcs: int, scale:bool = True, verbose:bool=True) -> Pipeline:
    """
    Helper function for fitting PCA pipeline. NOTE that this is 
        - based off of the current format of processing the movies (i.e. based on lots of .npy arrays) and must be updated when we move to zarrs
        - assuming the use of the 8-dimensional latent model
    Lots of hacks, but better to have shared hacks than everyone having their own...

    Args:
        data (pd.DataFrame): DataFrame containing the data to fit PCA on
        num_pcs (int): Number of principal components to keep

    Returns:
        pipe (Pipeline): Fitted PCA pipeline (may include scaling)
    """

    if 'filename_or_obj' not in data.columns and 'dataset_name' not in data.columns and 'FOV_ID' not in data.columns and 'T' not in data.columns:
        raise ValueError('Data must have at metadata identifying dataset, FOV, and timepoint')
              
    feature_cols = [str(i) for i in range(8)]
    if not np.all([f in data.columns for f in feature_cols]):
        raise ValueError('Data must have columns for all 8 latent dimensions')

    if '9' in data.columns:
        raise ValueError('Please check your dataset to make sure it was generated by a model with 8 latent dimensions')

    datasets_present = data.dataset_name.unique()
    for ds_date in ['20241120', '20241203', '20241217']:
        assert np.any([ds_date in dataset for dataset in datasets_present]), f'Expected group {ds_date} to be present in data. Datasets present: {datasets_present}'

    data_ref = get_pca_reference(data)
    if 'outlier' not in data_ref.columns:
        data_ref = get_outliers(data_ref)
    data_ref = remove_outliers(data_ref)

    if scale:
        pipe = Pipeline([
            ('scaler', StandardScaler()),
            ('pca', PCA(n_components=num_pcs, svd_solver='full'))
        ])
    else:
        pipe = Pipeline([
            ('pca', PCA(n_components=num_pcs, svd_solver='full'))
        ])
    pipe.fit(data_ref[feature_cols].values)

    if verbose:
        print(f'Cumulative Explained Variance: {np.round(np.cumsum(pipe["pca"].explained_variance_ratio_),4)}')

    return data, pipe