import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
import pandas as pd

# this is to suppress the SettingWithCopyWarning
pd.options.mode.chained_assignment = None  # default='warn'

def simple_linear_classifier(X: pd.Series, Y: pd.Series) -> pd.Series:
    '''
    Simple linear classifier to identify outliers based on the following rule:
        Z = 3/2 * X - 0.6
        Outlier if Z > Y
    where X is the first latent dimension and Y is the fourth latent dimension of
    the 8-dimensional latent space of the Diffusion Autoencoder model.

    This was a simple rule that was found to work well for the datasets with persistent bubbles.

    Inputs:
    - X: pd.Series (column of pd.DataFrame), first latent dimension of the 8-dimensional latent space
    - Y: pd.Series (column of pd.DataFrame), fourth latent dimension of the 8-dimensional latent space

    Outputs:
    - Z>Y: pd.Series, boolean column indicating whether the point is an outlier
    '''
    Z = 3/2. * X - 0.6
    return Z > Y

def get_outliers(data: pd.DataFrame) -> pd.DataFrame:
    '''
    Find outlier crops based on a linear classifier (detection of bubbles in low flow datasets).
    The classifier is based on the first and fourth latent dimensions of the 8-dimensional latent space

    Inputs:
    - data: pd.DataFrame, containing the 8-dimensional latent space

    Outputs:
    - data: pd.DataFrame, with an additional column 'outlier' indicating whether the crop is an outlier
    '''
    data['outlier'] = simple_linear_classifier(data['1'], data['4'])
    return data

def remove_outliers(data:pd.DataFrame) -> pd.DataFrame:
    '''
    Remove outlier crops from the dataset.

    Inputs:
    - data: pd.DataFrame, containing the 8-dimensional latent space
        - must have a column 'outlier' indicating whether the crop is an outlier
    
    Outputs:
    - data: pd.DataFrame, with the outliers removed
    '''
    data = data[~data.outlier]
    return data

def get_pca_reference(df:pd.DataFrame) -> pd.DataFrame:
    '''
    Select reference timepoints for fitting PCA based on the following criteria:
    - 20241120 (48hr high flow): all timepoints
    - 20241203 (48hr low flow): all timepoints
    - 20241210 & 20241217 (no-flow data): timepoints right after feeding
    All other datasets and timepoints are excluded.

    Inputs:
    - df: pd.DataFrame, containing the metadata for the dataset name and timepoints

    Outputs:
    - df: pd.DataFrame, with an additional column 'pca_ref' indicating whether the timepoint is a reference timepoint
    '''
    if 'dataset_name' not in df.columns:
        raise ValueError('Data must have a column for dataset_name')
    df['pca_ref'] = df.dataset_name.str.contains('20241120') | df.dataset_name.str.contains('20241203')
    # select no flow timepoints right after feeding
    df.loc[df.dataset_name.str.contains('20241210') & (df['T'] > 300) & (df['T'] < 450), 'pca_ref'] = True
    df.loc[df.dataset_name.str.contains('20241217') & (df['T'] < 100), 'pca_ref'] = True
    df.loc[df.dataset_name.str.contains('20241217') & (df['T'] >300) & (df['T'] < 420), 'pca_ref'] = True
    return df[df.pca_ref]

def fit_pca(data: pd.DataFrame, num_pcs: int, scale:bool = False, verbose:bool=True) -> Pipeline:
    """
    Helper function for fitting PCA pipeline. Note that this is 
        - based off of the current format of processing the movies (i.e. based on lots of .npy arrays) and must be updated when we move to zarrs
        - assuming the use of the 8-dimensional latent model
    Lots of hacks, but better to have shared hacks than everyone having their own...

    Args:
        data (pd.DataFrame): DataFrame containing the data to fit PCA on
        num_pcs (int): Number of principal components to keep

    Returns:
        pipe (Pipeline): Fitted PCA pipeline (may include scaling)
    """

    # check that the data has the necessary columns
    if 'filename_or_obj' not in data.columns and 'dataset_name' not in data.columns and 'FOV_ID' not in data.columns and 'T' not in data.columns:
        raise ValueError('Data must have at metadata identifying dataset, FOV, and timepoint')
              
    feature_cols = [str(i) for i in range(8)]
    if not np.all([f in data.columns for f in feature_cols]):
        raise ValueError('Data must have columns for all 8 latent dimensions')

    if '9' in data.columns:
        raise ValueError('Please check your dataset to make sure it was generated by a model with 8 latent dimensions')

    # check that the necessary datasets are present for fitting PCA
    datasets_present = data.dataset_name.unique()
    for ds_date in ['20241120', '20241203', '20241217']:
        assert np.any([ds_date in dataset for dataset in datasets_present]), f'Expected group {ds_date} to be present in data. Datasets present: {datasets_present}'

    # get reference timepoints for fitting PCA
    data_ref = get_pca_reference(data)

    # get and remove outliers
    if 'outlier' not in data_ref.columns:
        data_ref = get_outliers(data_ref)
    data_ref = remove_outliers(data_ref)

    # fit PCA
    if scale: # scale the data before fitting PCA
        pipe = Pipeline([
            ('scaler', StandardScaler()),
            ('pca', PCA(n_components=num_pcs, svd_solver='full'))
        ])
    else: # don't scale the data before fitting PCA
        pipe = Pipeline([
            ('pca', PCA(n_components=num_pcs, svd_solver='full'))
        ])
    pipe.fit(data_ref[feature_cols].values) # fit PCA

    if verbose: # print explained variance ratios
        print(f'Cumulative Explained Variance: {np.round(np.cumsum(pipe["pca"].explained_variance_ratio_),4)}')

    # return the fit PCA pipeline
    return pipe