from pathlib import Path
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
import pandas as pd

pd.options.mode.chained_assignment = None  # default='warn'

# input type should be columns of pd.DataFrame
def simple_linear_classifier(X: pd.Series, Y: pd.Series) -> pd.Series:
  Z = 3/2. * X - 0.6
  return Z > Y

def _get_group(s:str) -> str:
    return Path(s).parent.parent.stem

def _get_tp(s:str,n_fovs = 6):
    return int(s.split('/')[-1].split('_')[-1][2:-4])//n_fovs

def _get_fov(s,n_fovs = 6):
    return int(s.split('/')[-1].split('_')[-1][2:-4])%n_fovs

def get_outliers(data: pd.DataFrame):
    # find outlier crops
    data['outlier'] = simple_linear_classifier(data['1'], data['4'])
    return data

def remove_outliers(data:pd.DataFrame) -> pd.DataFrame:
    # we know the low flow dataset has lots of bubbles, fit a bubble prediction model here and apply on other movies
    data = data[~data.outlier]
    return data

def get_pca_reference(df:pd.DataFrame) -> pd.DataFrame:
    df['pca_ref'] = df.group.str.contains('20241120') | df.group.str.contains('20241203')
    # select no flow timepoints right after feeding
    df.loc[df.group.str.contains('20241210') & (df['T'] > 300) & (df['T'] < 450), 'pca_ref'] = True
    df.loc[df.group.str.contains('20241217') & (df['T'] < 100), 'pca_ref'] = True
    df.loc[df.group.str.contains('20241217') & (df['T'] >300) & (df['T'] < 420), 'pca_ref'] = True
    return df[df.pca_ref]

def get_pca(data: pd.DataFrame, num_pcs: int, scale = True) -> Pipeline:
    """
    Helper function for fitting PCA pipeline. NOTE that this is 
        - based off of the current format of processing the movies (i.e. based on lots of .npy arrays) and must be updated when we move to zarrs
        - assuming the use of the 8-dimensional latent model
    Lots of hacks, but better to have shared hacks than everyone having their own...

    Args:
        data (pd.DataFrame): DataFrame containing the data to fit PCA on
        num_pcs (int): Number of principal components to keep

    Returns:
        pipe (Pipeline): Fitted PCA pipeline
    """
    if 'filename_or_obj' in data.columns:
        if not data.filename_or_obj.str.endswith('.npy').all():
            raise ValueError('Expected data for fitting PCA to come from .npy files. Calculating group and timepoint depends on this.')
        if 'group' not in data.columns:
            data['group'] = data.filename_or_obj.apply(_get_group)
        if 'FOV_ID' not in data.columns:
            data['FOV_ID'] = data.filename_or_obj.apply(_get_fov)
        if 'T' not in data.columns:
            data['T'] = data.filename_or_obj.apply(_get_tp)
    elif 'filename_or_obj' not in data.columns and 'group' not in data.columns and 'FOV_ID' not in data.columns and 'T' not in data.columns:
        raise ValueError('Data must have at filename_or_obj column')
              
    feature_cols = [str(i) for i in range(8)]
    if not np.all([f in data.columns for f in feature_cols]):
        raise ValueError('Data must have columns for all 8 latent dimensions')

    if '9' in data.columns:
        raise ValueError('Please check your dataset to make sure it was generated by a model with 8 latent dimensions')

    groups_present = data.group.unique()
    for group_date in ['20241120', '20241203', '20241210', '20241217']:
        assert np.any([group_date in g for g in groups_present]), f'Expected group {group_date} to be present in data. Groups present: {groups_present}'

    data_ref = get_pca_reference(data)
    data_ref = remove_outliers(get_outliers(data_ref))

    if scale:
        pipe = Pipeline([
            ('scaler', StandardScaler()),
            ('pca', PCA(n_components=num_pcs, svd_solver='full'))
        ])
    else:
        pipe = Pipeline([
            ('pca', PCA(n_components=num_pcs, svd_solver='full'))
        ])
    pipe.fit(data_ref[feature_cols].values)

    print(f'Cumulative Explained Variance: {np.round(np.cumsum(pipe["pca"].explained_variance_ratio_),4)}')

    return data, pipe