experiment_name: endo_time
run_name: mae
task_name: train
tags:
- dev
train: true
test: false
checkpoint:
  ckpt_path: "//allen/aics/assay-dev/users/Benji/CurrentProjects/im2im_dev/cyto-dl/logs/train/runs/endo_time/mae/2024-07-09_15-37-27/checkpoints/epoch_909.ckpt"
  strict: True
  weights_only: null
seed: 12345
data:
  _target_: cyto_dl.datamodules.array.make_array_dataloader
  data:
  num_workers: 1
  batch_size: 1
  source_key: raw
  transforms:
    - _target_: monai.transforms.NormalizeIntensityd
      keys: raw
    - _target_: monai.transforms.ToTensord
      keys: raw
      dtype: float16

model:
  _target_: cyto_dl.models.contrastive.Contrastive
  anchor_key: raw
  backbone:
    _target_: cyto_dl.nn.vits.MAE_ViT
    spatial_dims: 2
    # base_patch_size* num_patches should be your patch shape
    base_patch_size: [16, 16]
    num_patches: [32, 32]
    emb_dim: 256
    encoder_layer: 16
    encoder_head: 8
    decoder_layer: 4
    decoder_dim: 128
    mask_ratio: 0
    use_crossmae: True
    features_only: True
  task_head:
  optimizer:
    generator:
      _partial_: True
      _target_: torch.optim.AdamW
      weight_decay: 0.05
  lr_scheduler:
    generator:
      _partial_: True
      _target_: torch.optim.lr_scheduler.OneCycleLR
      max_lr: 0.0001
      epochs: ${trainer.max_epochs}
      steps_per_epoch: 1
      pct_start: 0.1
callbacks:
logger:
trainer:
  _target_: lightning.Trainer
  default_root_dir: ${paths.output_dir}
  min_epochs: 1
  max_epochs: 1000
  accelerator: gpu
  devices:
  - 0
  precision: 16
  check_val_every_n_epoch: 10
  deterministic: false
  detect_anomaly: false
  max_time: null
  gradient_clip_val: 5
paths:
  root_dir: ${oc.env:PROJECT_ROOT, './'}
  data_dir: ${paths.root_dir}/data/
  log_dir: ${paths.root_dir}/logs/
  output_dir: './'
extras:
  ignore_warnings: true
  enforce_tags: false
  print_config: false
  precision:
    _target_: torch.set_float32_matmul_precision
    precision: medium
persist_cache: true
