from endo_pipeline.settings import DEFAULT_MODEL_MANIFEST_NAME, DEFAULT_MODEL_RUN_NAME

TAGS = ["dynamical_systems", "diffae_features", "2d_feature_space"]


def main(
    dynamics_config_name: str = "default",
    model_manifest_name: str = DEFAULT_MODEL_MANIFEST_NAME,
    run_name: str | None = DEFAULT_MODEL_RUN_NAME,
) -> None:
    """
    Fit SINDy (polynomial regression) models for drift and diffusion terms.

    Regression is performed on the training data generated by :code:`build_sde_train_test.py`.

    Parameters
    ----------
    dynamics_config_name
        Name of the configuration to load from dynamics_config.yaml.
    model_manifest_name
        Name of the model manifest containing the run to load features from.
    run_name
        Name of the specific model run to load featuref for. If None, uses the most recent run.
    """
    import logging

    import pysindy as ps

    from endo_pipeline.configs import dynamics_io
    from endo_pipeline.io import get_output_path
    from endo_pipeline.library.analyze.dynamics_utils import (
        build_diff_lib,
        build_drift_lib,
        load_train_test,
        save_sde_model,
    )
    from endo_pipeline.manifests import get_feature_dataframe_manifest_name, load_model_manifest

    logger = logging.getLogger(__name__)

    ################### Load configs from dynamics_config ###################
    logger.info("*** Running workflow using workflow input config: [ %s ]", dynamics_config_name)
    dynamics_config = dynamics_io.load_dynamics_config(dynamics_config_name)

    # get output subdirectory for intermediate workflow outputs
    # (set in config file dynamics_config.yaml)
    # if directory does not exist, get_output_path function will create it
    model_manifest = load_model_manifest(model_manifest_name)
    dataframe_manifest_name = get_feature_dataframe_manifest_name(
        model_manifest, run_name, crop_pattern="grid"
    )
    savedir = get_output_path(
        "stochastic_dynamics", dynamics_config_name, dataframe_manifest_name, "outputs"
    )

    # get inputs for regression from config
    pcs = dynamics_config["pcs_to_analyze"]
    dt = dynamics_config["dt"]
    drift_deg = dynamics_config["polynomial_lib"]["drift_feats"]
    diff_deg = dynamics_config["polynomial_lib"]["diffusion_feats"]
    param_deg_drift = dynamics_config["polynomial_lib"]["drift_param"]
    param_deg_diff = dynamics_config["polynomial_lib"]["diffusion_param"]

    ################### Load train test data from file ###################
    logger.debug(
        "Loading train and test data for regression from precomputed file [ %s ]",
        savedir / "train_test_data.npz",
    )
    train_test_dict = load_train_test(savedir / "train_test_data.npz")

    ################### Build SINDy libraries ###################
    # for fitting model of drift and diffusion terms
    drift_lib = build_drift_lib(ndim=len(pcs), drift_deg=drift_deg, param_deg=param_deg_drift)

    diff_lib = build_diff_lib(ndim=len(pcs), diff_deg=diff_deg, param_deg=param_deg_diff)
    ################### Fit SINDy models ###################

    # fit model for drift term - SINDy based regression
    drift_model = ps.SINDy(feature_library=drift_lib, optimizer=ps.SSR())
    drift_model.fit(
        train_test_dict["x_train"],
        t=dt,
        x_dot=train_test_dict["y_train"],
        u=train_test_dict["u_train"],
    )

    # score on test set
    drift_r2 = drift_model.score(
        train_test_dict["x_test"],
        x_dot=train_test_dict["y_test"],
        u=train_test_dict["u_test"],
    )
    # how to redirect these print statements to logger?
    drift_model.print()

    logger.info("Coefficient of determination (R^2) for model of drift term: [ %.4f ]", drift_r2)

    # fit model for diffusion term - SINDy based regression
    diff_model = ps.SINDy(feature_library=diff_lib, optimizer=ps.SSR())
    diff_model.fit(
        train_test_dict["x_train"],
        t=dt,
        x_dot=train_test_dict["v_train"],
        u=train_test_dict["u_train"],
    )

    # score on test set
    diff_r2 = diff_model.score(
        train_test_dict["x_test"],
        x_dot=train_test_dict["v_test"],
        u=train_test_dict["u_test"],
    )
    diff_model.print()

    logger.info("Coefficient of determination (R^2) for model of diffusion term: [ %.4f ]", diff_r2)

    ################### Save trained models ###################
    model_dict = {"drift_model": drift_model, "diff_model": diff_model}
    save_sde_model(model_dict, savedir)


if __name__ == "__main__":
    from endo_pipeline.__main__ import workflow_cli

    workflow_cli(main)
