TAGS = ["diffae_model_training"]


def main(
    resolution_level: int = 1,
    crop_size: int = 128,
) -> None:
    """
    Train a DiffAE model using the provided configuration.

    **Workflow testing**

    If testing mode is enabled, the training and validation datasets used willduring training will
    be the ones with only one entry each as generated by the `create_diffae_training_dataframe`
    script with the ``--testing-mode`` (or ``-x``) flag. Furthermore, the model will only be trained
    for one epoch.

    Parameters
    ----------
    resolution_level
        The resolution level of the zarr files to be used for training.
    crop_size
        The length of the 2D image crop in pixels to use for model training.

    Returns
    -------
    :
        The function creates and saves a ModelConfig object with the trained model's
        MLflow run ID and the list of datasets used for training.
    """
    import datetime
    import logging

    from omegaconf import OmegaConf

    from src.endo_pipeline import TESTING_MODE
    from src.endo_pipeline.configs import CytoDLModelConfig, save_model_config
    from src.endo_pipeline.io import get_output_path
    from src.endo_pipeline.library.model import (
        get_dataset_names_used_for_training,
        get_model_dir,
        get_valid_csv_path_for_training,
        initialize_diffae_model,
    )
    from src.endo_pipeline.manifests import load_dataframe_manifest

    logger = logging.getLogger(__name__)

    # get training and validation datasets based on zarr resolution
    # by loading the DataframeManifest from the model directory
    # and using the DatasetLocation objects to get the paths
    manifest_name = f"diffae_training_dataframe_resolution_{resolution_level}"
    if TESTING_MODE:
        manifest_name += "_test_workflow"
    try:
        dataframe_manifest = load_dataframe_manifest(manifest_name)
    except FileNotFoundError:
        logger.error(
            "Dataframe manifest [ %s ] for resolution_level [ %s ] not found. "
            "Please run the create_diffae_training_dataframe script first "
            "with the appropriate resolution_level.",
            manifest_name,
            resolution_level,
        )
        raise
    train_csv_location = dataframe_manifest.locations["training"]
    val_csv_location = dataframe_manifest.locations["validation"]

    # get csv paths from the DataframeLocation objects
    # to pass into the DiffAE model training script
    # (need csv paths for training config setup and CytoDL dataloaders)
    train_csv_path = get_valid_csv_path_for_training(train_csv_location)
    val_csv_path = get_valid_csv_path_for_training(val_csv_location)

    # load template training config
    template_training_config = OmegaConf.load(get_model_dir() / "diffae_training.yaml")

    # set model name via zarr resolution, crop size, and current timestamp
    timestamp = datetime.datetime.now(tz=datetime.UTC).strftime("%Y-%m-%d_%H-%M-%S")
    model_name = f"diffae_resolution_{resolution_level}_patch_{crop_size}x{crop_size}_{timestamp}"
    logger.info("Model name: [ %s ]", model_name)

    # initialize DiffAE model: generates config overrides and sets up output directories
    model = initialize_diffae_model(
        template_training_config,
        crop_size,
        model_name,
        train_csv_path,
        val_csv_path,
        max_num_epochs=1 if TESTING_MODE else 1000,  # for testing mode, train for 1 epoch
        log_every_n_steps=(
            1 if TESTING_MODE else 50
        ),  # deafult 50, need to set to 1 for testing mode
    )
    local_config_save_path = get_output_path("models", "training_configs")
    model.save_config(local_config_save_path / f"{model_name}_train.yaml")
    logger.info(
        "Training config saved to [ %s ]",
        local_config_save_path / f"{model_name}_train.yaml",
    )
    _, object_dict = model.train()

    # retrive MLflow run ID
    mlflow_logger = object_dict["logger"][0]
    run_id = mlflow_logger.run_id
    logger.info("MLflow run ID: [ %s ]", run_id)
    # get list of datasets used for training
    # based on content of train and val dataframes
    list_of_training_datasets = get_dataset_names_used_for_training(
        train_csv_path,
        val_csv_path,
        "live_20X_objective_3i_microscope",
    )
    # add run ID to model config
    model_config = CytoDLModelConfig(
        name=model_name if not TESTING_MODE else f"{model_name}_test_workflow",
        mlflow_run_id=run_id,
        training_datasets=list_of_training_datasets,
        train_dataframe=train_csv_location,
        test_dataframe=val_csv_location,
    )
    # save the model config
    save_model_config(model_config)


if __name__ == "__main__":
    from src.endo_pipeline.__main__ import workflow_cli

    workflow_cli(main)
