name: cdh5_classic_segmentation
workflow: get_cdh5_measured_features
parameters: {}
columns:
  dataset: Name of dataset
  position: Zarr file position (FOV) of the corresponding segmentation or patch (crop)
  frame_number: Timepoint [frames]
  label: Cell segmentation ID (different from track ID, and may change between timepoints)
  centroid: Centroid of cell segmentation in (Y,X) [pixels]
  area_px_squared: Area of cell segmentation [pixels^2]
  perimeter_px: Perimeter of cell segmentation [pixels]
  solidity: Solidity of cell (ratio of cell area to area of its convex hull)
  major_axis_length: Length of minor axis of an ellipse fit to cell segmentation
  minor_axis_length: Length of minor axis of an ellipse fit to cell segmentation
  eccentricity: Eccentricity of ellipse fit to cell segmentation (focal distance divided
    by major axis)
  orientation: Orientation of cell [radians] from 0 (along +x axis) to pi (along -x
    axis)
  cell_fluorescence_mean_au: Mean of mEGFP-tagged VE-cadherin fluorescence [a.u.]
    in cytoplasmic region of cell segmentation
  cell_fluorescence_std_au: Standard deviation of mEGFP-tagged VE-cadherin fluorescence
    [a.u.] in cytoplasmic region of cell segmentation
  cell_fluorescence_median_au: Median of mEGFP-tagged VE-cadherin fluorescence [a.u.]
    in cytoplasmic region of cell segmentation
  cell_fluorescence_min_au: Minimum of mEGFP-tagged VE-cadherin fluorescence [a.u.]
    in cytoplasmic region of cell segmentation
  cell_fluorescence_pct25_au: 25th percentile of mEGFP-tagged VE-cadherin fluorescence
    [a.u.] in cytoplasmic region of cell segmentation
  cell_fluorescence_pct75_au: 75th percentile of mEGFP-tagged VE-cadherin fluorescence
    [a.u.] in cytoplasmic region of cell segmentation
  cell_fluorescence_max_au: Maximum of mEGFP-tagged VE-cadherin fluorescence [a.u.]
    in cytoplasmic region of cell segmentation
  neighboring_cell_labels: Cell segmentation labels of adjacent cell segmentations
  edge_labels: Label IDs of each edge of a segmentation boundary
  node_labels: Label IDs for each tricellular junction
  node_pair_labels: Pair of node label IDs that form each edge of a segmentation boundary
  edge_fluorescence_au: Fluorescence values [a.u.] along boundary between 2 cell segmentations
    (excluding pixels at nodes)
  node_fluorescence_au: Fluorescence values [a.u.] at junctions between 3 or more
    cell segmentations
  is_edge_segmentation: True if segmentation touches edge of the image, False otherwise
locations:
  20250319_20X:
    fmsid: b56d6b0e892f423eae6bdd02171910d2
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/cdh5_classic_segmentation/20250319_0d94f8d3054e4e8c99af07dd92774798.parquet
  20250326_20X:
    fmsid: 9776c60b54254d18a616aab2b158fc8f
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/cdh5_classic_segmentation/20250326_eb97addf262c44c5a6117ad1d4acc353.parquet
  20250409_20X:
    fmsid: ff00750de82f44478f25ca427aafa65f
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/cdh5_classic_segmentation/20250409_df6b2a02bbc94c6f957923add524eac1.parquet
  20250428_20X:
    fmsid: 900a2327033b462f94d33b4cdf78232b
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/cdh5_classic_segmentation/20250428_056aa027ba9f4ccd98367563552f7edd.parquet
  20250604_20X:
    fmsid: bf058e9ec41f4c98b033ebd60aae9315
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/cdh5_classic_segmentation/20250604_3f08ef7a2e0e450d963352dae4bf17dc.parquet
  20250611_20X:
    fmsid: a967e29b88ef4d4ca562d315a3c67f07
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/cdh5_classic_segmentation/20250611_a32615d530ae42c29d159cc058601879.parquet
  20250618_20X:
    fmsid: bb8ef38b00ba4821821ade9fc2d13dfa
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/cdh5_classic_segmentation/20250618_f81e9bdf048e462e9755d7cbf5d21c37.parquet
  20250714_20X:
    fmsid: 3ac7d5ff795d40b9bbb8793b2ce122bf
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/cdh5_classic_segmentation/20250714_0a0462b7d33848c8826105ab6f78787d.parquet
  20250716_20X:
    fmsid: 313fbd743f8b4c779d055e3fa82913de
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/cdh5_classic_segmentation/20250716_328c62ecc91248eab2268e546892453e.parquet
  20250728_20X:
    fmsid: c7f5db79965045cd97dc338b757e5ffd
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/cdh5_classic_segmentation/20250728_b07652734b1b43178f4bc704abd7b95b.parquet
  20250813_20X:
    fmsid: c75f13ff2b4448e4927d68347c4eec0a
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/cdh5_classic_segmentation/20250813_6ab0f70bd43f4de987a789905dbfb95c.parquet
  20250818_20X:
    fmsid: 317ac7eaa4e04052a664392a429fad94
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/cdh5_classic_segmentation/20250818_1f895d9188df43e0a10b379cf23a879c.parquet
  20250827_20X:
    fmsid: 927fe979691746f89958b3381704fee7
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/cdh5_classic_segmentation/20250827_c96180b30a224a48bac3b6d8fe1ffbb4.parquet
  20251001_20X:
    fmsid: 26de696568d74708b2b5b2da358e4bcb
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/cdh5_classic_segmentation/20251001_271124f03a16409499e8a84b0030cb15.parquet
  20250402_20X:
    fmsid: aaae2e58c0834af09974d4561eb81af4
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/cdh5_classic_segmentation/20250402_90e37b7d8f1440efa84995b4697fb269.parquet
  20260114_20X:
    fmsid: aa9c2480ce104023bc80c5404c4dccb2
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/cdh5_classic_segmentation/20260114_4b693bb8eedb4e0ba0cb9ab4ae07b1a2.parquet
  20260121_20X:
    fmsid: d0bbbde8d6014b62ba5bfd01642ed128
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/cdh5_classic_segmentation/20260121_ff75e124720b4a3aa035025a05ced25f.parquet
  20260126_20X:
    fmsid: 15d1162bda83418ca1a44e10272e4e2a
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/cdh5_classic_segmentation/20260126_aed19d79c1a34707925cfa8393424c45.parquet
  20260128_20X:
    fmsid: 35297ee718834d3189adb35f5d837790
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/cdh5_classic_segmentation/20260128_00bd94ea6d7e4b46bc16a55e35de589d.parquet
  20260202_20X:
    fmsid: b540e4b20b724875b48d11ab3ce3468d
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/cdh5_classic_segmentation/20260202_fcb18a65bb734ff6ae718e1eee4894d6.parquet
  20260204_20X:
    fmsid: 04d92e3995994cc0a4b1f8ca79f3719b
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/cdh5_classic_segmentation/20260204_ac1fddfd7452481e83317c8fbdd59dd6.parquet
  20260209_20X:
    fmsid: 7240046799ca46da9dd9e06a4e9e3be7
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/cdh5_classic_segmentation/20260209_3700e11f893e4f378db450ea91bd92d6.parquet
  20260211_20X:
    fmsid: 79feba8c02564705b108172459c306c3
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/cdh5_classic_segmentation/20260211_20b76dc8d0ca488ba88816793830f6ec.parquet
  20260216_20X:
    fmsid: 6eed48956e134d29a5ff748e0dd1677f
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/cdh5_classic_segmentation/20260216_ed3743a1ee4c4cb096f5af90e3ebb9bd.parquet
  20260225_20X:
    fmsid: 9695afcc5ed14be2b6a4b302f630335b
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/cdh5_classic_segmentation/20260225_50afe3cb17cf4be099dc44e47f7a4ae4.parquet
  20260302_20X:
    fmsid: a7b38e6f689f4beebc01cdcbf9cb02b0
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/cdh5_classic_segmentation/20260302_e9cfa3b0b24447f7bba000af3b012427.parquet
  20260304_20X:
    fmsid: c763c45d857f4f5f9af0e48d7009676f
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/cdh5_classic_segmentation/20260304_56c81f459d8e46eabd74cc2147b85f49.parquet
