name: diffae_training_dataframe
workflow: create_diffae_training_dataframe
parameters:
  z_slice_offsets: [4, 11]
locations:
  training:
    fmsid: aa3a82d4b4004b35ad64021247a729ae
    path: null
    s3uri: null
  validation:
    fmsid: c7511fd701134011b790a60e58bc3833
    path: null
    s3uri: null
