name: diffae_training_dataframe_resolution_2
workflow: generate_diffae_training_dataframe
parameters:
  resolution_level: 2
locations:
  training:
    fmsid: 38ae810b04f94d628eca09eaa07206a0
    s3uri: null
  validation:
    fmsid: d7bd819c202b41308044240855a55b9a
    s3uri: null
