name: diffae_model_comparison_metrics_diffae_cdh5_conditioned
workflow: calculate_model_comparison_metrics
parameters:
  model_manifest_name: diffae_cdh5_conditioned
  random_seeds: [42, 43, 44, 45, 46, 47, 48, 49, 50, 51]
  examples_groups: [replicate, training, validation]
columns:
  model_manifest_name: Manifest name of model used to generate latent vectors
  run_name: Run name of model used to generate latent vectors
  example_key: Key representing example image dataset name, position, timepoint, and
    crop start
  random_seed: Random number generator seed
  example_group: Name of group of model comparison example images
  baseline_correlations: Pearson correlation between ground truth and next timepoint
  baseline_ssim: Structural Similarity Index (SSIM) between ground truth and next
    timepoint
  baseline_lpips: Learned Perceptual Image Patch Similarity (LPIPS) between ground
    truth and next timepoint
  denoised_correlations: Pearson correlation between input and denoised image
  denoised_ssim: Structural Similarity Index (SSIM) between input and denoised image
  denoised_lpips: Learned Perceptual Image Patch Similarity (LPIPS) between input
    and denoised image
locations:
  latent_512:
    fmsid: 843045a09ded49e6842cd41a5d16d35f
    path: null
    s3uri: null
  latent_1024:
    fmsid: 7900f6511abc464bbd357de8e1a3e569
    path: null
    s3uri: null
