name: diffae_training_dataframe_resolution_1_exclude_cell_piling
workflow: create_diffae_training_dataframe
parameters:
  resolution_level: 1
locations:
  training:
    fmsid: 98e7ed05914d4f8cbede17c0ce34d111
    s3uri: null
  validation:
    fmsid: 736f20a6c1e748a9972f9a4e042a4748
    s3uri: null
