name: diffae_training_dataframe_resolution_1_include_cell_piling_test_workflow
workflow: create_diffae_training_dataframe
parameters:
  resolution_level: 1
  z_slice_offsets:
  - 4
  - 11
  include_cell_piling: true
locations:
  training:
    fmsid: 66be040fa92e4be59890a862ac059ce1
    s3uri: null
  validation:
    fmsid: 769e0ad67bde46b2a96a56ad29bc55cc
    s3uri: null
