name: diffae_finetuning_dataframe_resolution_1_test_workflow
workflow: create_diffae_finetuning_dataframe
parameters:
  resolution_level: 1
locations:
  training:
    fmsid: d2a95af8cc85426d9a6d8d08c05970ea
    s3uri: null
  validation:
    fmsid: 6b01dbf6cd7e4430a15c46541f5f78e3
    s3uri: null
