name: diffae_finetuning_dataframe_resolution_1
workflow: create_diffae_finetuning_dataframe
parameters:
  resolution_level: 1
  z_slice_offsets:
  - 4
  - 11
  exclude_cell_piling: false
locations:
  training:
    fmsid: 46e6c877a3ff4262a0180a99cb16fe1a
    s3uri: null
  validation:
    fmsid: b2080696b3a84d0499b8350ab0d4add7
    s3uri: null
