name: diffae_finetuning_dataframe
workflow: create_diffae_finetuning_dataframe
parameters:
  z_slice_offsets:
  - 4
  - 11
  include_cell_piling: false
locations:
  training:
    fmsid: 3fdc0ba1063e4c9098ed0ae9f4355ba2
    s3uri: null
  validation:
    fmsid: 1c72b8f37cc4403f8aebbd399e6d3085
    s3uri: null
