name: diffae_finetuning_dataframe
workflow: create_diffae_finetuning_dataframe
parameters:
  z_slice_offsets:
  - 4
  - 11
  include_cell_piling: false
locations:
  training:
    fmsid: 91a80c2676224578b4d695b8d710be00
    path: null
    s3uri: null
  validation:
    fmsid: 73747dbf4d384a759ced028a02a4aea5
    path: null
    s3uri: null
