name: diffae_finetuning_dataframe_resolution_1_test_workflow
workflow: create_diffae_finetuning_dataframe
parameters:
  resolution_level: 1
locations:
  training:
    fmsid: e3234de2aeb840568f6b1879f2f3ebbb
    s3uri: null
  validation:
    fmsid: 367bae9a973545b98674ca1a3896a7ef
    s3uri: null
