name: diffae_training_dataframe_exclude_cell_piling
workflow: create_diffae_training_dataframe
parameters:
  include_cell_piling: false
  z_slice_offsets:
  - 4
  - 11
locations:
  training:
    fmsid: null
    path: /allen/aics/users/fatwir.mohammed/cellsmap/results/2026-05-18/model_train_dataframes/training_resolution_1_z_stack_4_11_exclude_cell_piling.parquet
    s3uri: null
  validation:
    fmsid: null
    path: /allen/aics/users/fatwir.mohammed/cellsmap/results/2026-05-18/model_val_dataframes/validation_resolution_1_z_stack_4_11_exclude_cell_piling.parquet
    s3uri: null
