name: diffae_model_comparison_metrics_diffae_baseline_exclude_cell_piling
workflow: calculate_model_comparison_metrics
parameters:
  num_seeds: 10
  seeds: [42, 43, 44, 45, 46, 47, 48, 49, 50, 51]
  random_seed: 47
  example_sets: [rep_2_positions, validation_positions]
  noise_levels: [0.25, 0.5, 0.75]
  manifest_name: diffae_baseline_exclude_cell_piling
locations:
  latent_8:
    fmsid: cd4790bcf2564581b28098638507ddfc
    path: null
    s3uri: null
  latent_16:
    fmsid: d79c989760a44903b5051efb03f8817d
    path: null
    s3uri: null
  latent_32:
    fmsid: e963d81652864b56aae04d9bcc453cf9
    path: null
    s3uri: null
  latent_64:
    fmsid: 929b7c89df8a4834b2b88b96cdb9493f
    path: null
    s3uri: null
  latent_128:
    fmsid: 47d625161bfe4a62bdd2ffb900df3493
    path: null
    s3uri: null
  latent_256:
    fmsid: 09c7666087fd4ad78d0e9427d98ce37b
    path: null
    s3uri: null
  latent_512:
    fmsid: fc829663584c4bddaaac9c5594839dac
    path: null
    s3uri: null
  latent_1024:
    fmsid: 64ca85c1d63543acb40c91cd37053670
    path: null
    s3uri: null
