name: diffae_model_comparison_metrics_diffae_baseline
workflow: calculate_model_comparison_metrics
parameters:
  model_manifest_name: diffae_baseline
  random_seeds: [42, 43, 44, 45, 46, 47, 48, 49, 50, 51]
  examples_groups: [replicate, training, validation]
locations:
  latent_8:
    fmsid: 61f96ed0a02b4498acb0fbe90d3c6249
    path: null
    s3uri: null
  latent_16:
    fmsid: 9b6cbe38a63645e99643379fb10f6525
    path: null
    s3uri: null
  latent_32:
    fmsid: fb15c75d2cd846fda97c0b41d3de1bc8
    path: null
    s3uri: null
  latent_64:
    fmsid: 6ca49249d2634ec3bfdeeb9f0f59a3bc
    path: null
    s3uri: null
  latent_128:
    fmsid: 77a2d1196fa4400d9159baaf5166bf5e
    path: null
    s3uri: null
  latent_256:
    fmsid: db9cc9bb4d334d3dbf15e2317a4a843e
    path: null
    s3uri: null
  latent_512:
    fmsid: df980f117c6546a6a7889f1dbbba1e8b
    path: null
    s3uri: null
  latent_1024:
    fmsid: 8fed0573891d45b480de09789e8d408d
    path: null
    s3uri: null
