name: diffae_training_csv_resolution_1
workflow: generate_diffae_training_csv
parameters:
  zarr_resolution: 1
locations:
  training:
    fmsid: a0d1c6c596f94be3980ff4a1157a0bc5
    s3uri: null
  validation:
    fmsid: 9b174a7640a44daea27b273566a9d2fb
    s3uri: null
