name: diffae_finetuning_dataframe_resolution_1_test_workflow
workflow: create_diffae_finetuning_dataframe
parameters:
  resolution_level: 1
locations:
  training:
    fmsid: 403e3dc322074c7aa2402f6e5ac875bb
    s3uri: null
  validation:
    fmsid: 7b2d6f35a00848f994e3fd2067272e35
    s3uri: null
