name: diffae_training_dataframe_resolution_1_test_workflow
workflow: create_diffae_training_dataframe
parameters:
  resolution_level: 1
  z_slice_offsets:
  - 4
  - 11
  exclude_cell_piling: false
locations:
  training:
    fmsid: b154313b4c4a4d79b912f67bda1f38de
    s3uri: null
  validation:
    fmsid: 1ea2b85c701c468a953d2115e046a119
    s3uri: null
