name: diffae_training_dataframe_resolution_2_exclude_cell_piling
workflow: create_diffae_training_dataframe
parameters:
  resolution_level: 2
  z_slice_offsets:
  - 4
  - 11
  include_cell_piling: false
locations:
  training:
    fmsid: ed91de3f95dd4a3db4c8f8731de13011
    s3uri: null
  validation:
    fmsid: c1e4aed9ffd94d7cac51cc5c03586e25
    s3uri: null
