name: diffae_evaluation_dataframe_grid
workflow: create_diffae_eval_dataframe
parameters:
  crop_pattern: grid
  z_slice_offsets:
  - 4
  - 11
locations:
  20251001_20X:
    fmsid: 32f7545c2b9f43e39cfbe48dc636e400
    path: null
    s3uri: null
