name: diffae_baseline_exclude_cell_piling_20251110_latent_512_tracked
workflow: eval_diffae_tracked
parameters:
  crop_pattern: tracked
locations:
  20250319_20X:
    fmsid: null
    path: null
    s3uri: null
  20250428_20X:
    fmsid: null
    path: null
    s3uri: null
  20250611_20X:
    fmsid: null
    path: null
    s3uri: null
  20250618_20X:
    fmsid: null
    path: null
    s3uri: null
  20250714_20X:
    fmsid: null
    path: null
    s3uri: null
  20250813_20X:
    fmsid: null
    path: null
    s3uri: null
  20250818_20X:
    fmsid: null
    path: null
    s3uri: null
  20250827_20X:
    fmsid: null
    path: null
    s3uri: null
  20250224_20X:
    fmsid: null
    path: null
    s3uri: null
  20250326_20X:
    fmsid: null
    path: null
    s3uri: null
  20250409_20X:
    fmsid: null
    path: null
    s3uri: null
  20250604_20X:
    fmsid: null
    path: null
    s3uri: null
  20250716_20X:
    fmsid: null
    path: null
    s3uri: null
  20250728_20X:
    fmsid: null
    path: null
    s3uri: null
  20250806_20X:
    fmsid: null
    path: null
    s3uri: null
  20250825_20X:
    fmsid: null
    path: null
    s3uri: null
  20251001_20X:
    fmsid: null
    path: null
    s3uri: null
  20250402_20X:
    fmsid: null
    path: null
    s3uri: null
  20260114_20X:
    fmsid: null
    path: null
    s3uri: null
  20260121_20X:
    fmsid: null
    path: null
    s3uri: null
  20260126_20X:
    fmsid: null
    path: null
    s3uri: null
  20260128_20X:
    fmsid: null
    path: null
    s3uri: null
  20260202_20X:
    fmsid: null
    path: null
    s3uri: null
  20260204_20X:
    fmsid: null
    path: null
    s3uri: null
