name: diffae_training_dataframe_exclude_cell_piling
workflow: create_diffae_training_dataframe
parameters:
  z_slice_offsets: [4, 11]
  include_cell_piling: false
columns:
  path: ''
  resolution_level: ''
  channel: ''
  include_frames: ''
  z_start: ''
  z_stop: ''
  z_step: ''
locations:
  training:
    fmsid: aa3a82d4b4004b35ad64021247a729ae
    path: null
    s3uri: null
  validation:
    fmsid: c7511fd701134011b790a60e58bc3833
    path: null
    s3uri: null
