name: diffae_training_csv_resolution_1_test_workflow
workflow: generate_diffae_training_csv
parameters:
  zarr_resolution: 1
locations:
  training:
    fmsid: 4bebd788985d4ac68ba4815fa82aa4ea
    s3uri: null
  validation:
    fmsid: 66bd457fa1b84eab99fe0ce674c1a346
    s3uri: null
