name: diffae_training_dataframe_resolution_1
workflow: create_diffae_training_dataframe
parameters:
  resolution_level: 1
  z_stack_offsets: null
  exclude_cell_piling: false
locations:
  training:
    fmsid: d9349312ecde46e590f1b9f682103ac9
    s3uri: null
  validation:
    fmsid: 6d2702bb79bc4a65bb4ad5e8c390a831
    s3uri: null
