name: diffae_training_dataframe_include_cell_piling
workflow: create_diffae_training_dataframe
parameters:
  z_slice_offsets: [4, 11]
  include_cell_piling: true
locations:
  training:
    fmsid: d9898ed4c3724e3ea10f0e7c40c9d789
    path: null
    s3uri: null
  validation:
    fmsid: 2e426d2a680e41a99988838b530a5d8a
    path: null
    s3uri: null
