name: diffae_baseline_exclude_cell_piling_20251110_latent_512_grid
workflow: eval_diffae_grid
parameters:
  crop_pattern: grid
columns:
  feat_0: ''
  feat_1: ''
  feat_2: ''
  feat_3: ''
  feat_4: ''
  feat_5: ''
  feat_6: ''
  feat_7: ''
  feat_8: ''
  feat_9: ''
  feat_10: ''
  feat_11: ''
  feat_12: ''
  feat_13: ''
  feat_14: ''
  feat_15: ''
  feat_16: ''
  feat_17: ''
  feat_18: ''
  feat_19: ''
  feat_20: ''
  feat_21: ''
  feat_22: ''
  feat_23: ''
  feat_24: ''
  feat_25: ''
  feat_26: ''
  feat_27: ''
  feat_28: ''
  feat_29: ''
  feat_30: ''
  feat_31: ''
  feat_32: ''
  feat_33: ''
  feat_34: ''
  feat_35: ''
  feat_36: ''
  feat_37: ''
  feat_38: ''
  feat_39: ''
  feat_40: ''
  feat_41: ''
  feat_42: ''
  feat_43: ''
  feat_44: ''
  feat_45: ''
  feat_46: ''
  feat_47: ''
  feat_48: ''
  feat_49: ''
  feat_50: ''
  feat_51: ''
  feat_52: ''
  feat_53: ''
  feat_54: ''
  feat_55: ''
  feat_56: ''
  feat_57: ''
  feat_58: ''
  feat_59: ''
  feat_60: ''
  feat_61: ''
  feat_62: ''
  feat_63: ''
  feat_64: ''
  feat_65: ''
  feat_66: ''
  feat_67: ''
  feat_68: ''
  feat_69: ''
  feat_70: ''
  feat_71: ''
  feat_72: ''
  feat_73: ''
  feat_74: ''
  feat_75: ''
  feat_76: ''
  feat_77: ''
  feat_78: ''
  feat_79: ''
  feat_80: ''
  feat_81: ''
  feat_82: ''
  feat_83: ''
  feat_84: ''
  feat_85: ''
  feat_86: ''
  feat_87: ''
  feat_88: ''
  feat_89: ''
  feat_90: ''
  feat_91: ''
  feat_92: ''
  feat_93: ''
  feat_94: ''
  feat_95: ''
  feat_96: ''
  feat_97: ''
  feat_98: ''
  feat_99: ''
  feat_100: ''
  feat_101: ''
  feat_102: ''
  feat_103: ''
  feat_104: ''
  feat_105: ''
  feat_106: ''
  feat_107: ''
  feat_108: ''
  feat_109: ''
  feat_110: ''
  feat_111: ''
  feat_112: ''
  feat_113: ''
  feat_114: ''
  feat_115: ''
  feat_116: ''
  feat_117: ''
  feat_118: ''
  feat_119: ''
  feat_120: ''
  feat_121: ''
  feat_122: ''
  feat_123: ''
  feat_124: ''
  feat_125: ''
  feat_126: ''
  feat_127: ''
  feat_128: ''
  feat_129: ''
  feat_130: ''
  feat_131: ''
  feat_132: ''
  feat_133: ''
  feat_134: ''
  feat_135: ''
  feat_136: ''
  feat_137: ''
  feat_138: ''
  feat_139: ''
  feat_140: ''
  feat_141: ''
  feat_142: ''
  feat_143: ''
  feat_144: ''
  feat_145: ''
  feat_146: ''
  feat_147: ''
  feat_148: ''
  feat_149: ''
  feat_150: ''
  feat_151: ''
  feat_152: ''
  feat_153: ''
  feat_154: ''
  feat_155: ''
  feat_156: ''
  feat_157: ''
  feat_158: ''
  feat_159: ''
  feat_160: ''
  feat_161: ''
  feat_162: ''
  feat_163: ''
  feat_164: ''
  feat_165: ''
  feat_166: ''
  feat_167: ''
  feat_168: ''
  feat_169: ''
  feat_170: ''
  feat_171: ''
  feat_172: ''
  feat_173: ''
  feat_174: ''
  feat_175: ''
  feat_176: ''
  feat_177: ''
  feat_178: ''
  feat_179: ''
  feat_180: ''
  feat_181: ''
  feat_182: ''
  feat_183: ''
  feat_184: ''
  feat_185: ''
  feat_186: ''
  feat_187: ''
  feat_188: ''
  feat_189: ''
  feat_190: ''
  feat_191: ''
  feat_192: ''
  feat_193: ''
  feat_194: ''
  feat_195: ''
  feat_196: ''
  feat_197: ''
  feat_198: ''
  feat_199: ''
  feat_200: ''
  feat_201: ''
  feat_202: ''
  feat_203: ''
  feat_204: ''
  feat_205: ''
  feat_206: ''
  feat_207: ''
  feat_208: ''
  feat_209: ''
  feat_210: ''
  feat_211: ''
  feat_212: ''
  feat_213: ''
  feat_214: ''
  feat_215: ''
  feat_216: ''
  feat_217: ''
  feat_218: ''
  feat_219: ''
  feat_220: ''
  feat_221: ''
  feat_222: ''
  feat_223: ''
  feat_224: ''
  feat_225: ''
  feat_226: ''
  feat_227: ''
  feat_228: ''
  feat_229: ''
  feat_230: ''
  feat_231: ''
  feat_232: ''
  feat_233: ''
  feat_234: ''
  feat_235: ''
  feat_236: ''
  feat_237: ''
  feat_238: ''
  feat_239: ''
  feat_240: ''
  feat_241: ''
  feat_242: ''
  feat_243: ''
  feat_244: ''
  feat_245: ''
  feat_246: ''
  feat_247: ''
  feat_248: ''
  feat_249: ''
  feat_250: ''
  feat_251: ''
  feat_252: ''
  feat_253: ''
  feat_254: ''
  feat_255: ''
  feat_256: ''
  feat_257: ''
  feat_258: ''
  feat_259: ''
  feat_260: ''
  feat_261: ''
  feat_262: ''
  feat_263: ''
  feat_264: ''
  feat_265: ''
  feat_266: ''
  feat_267: ''
  feat_268: ''
  feat_269: ''
  feat_270: ''
  feat_271: ''
  feat_272: ''
  feat_273: ''
  feat_274: ''
  feat_275: ''
  feat_276: ''
  feat_277: ''
  feat_278: ''
  feat_279: ''
  feat_280: ''
  feat_281: ''
  feat_282: ''
  feat_283: ''
  feat_284: ''
  feat_285: ''
  feat_286: ''
  feat_287: ''
  feat_288: ''
  feat_289: ''
  feat_290: ''
  feat_291: ''
  feat_292: ''
  feat_293: ''
  feat_294: ''
  feat_295: ''
  feat_296: ''
  feat_297: ''
  feat_298: ''
  feat_299: ''
  feat_300: ''
  feat_301: ''
  feat_302: ''
  feat_303: ''
  feat_304: ''
  feat_305: ''
  feat_306: ''
  feat_307: ''
  feat_308: ''
  feat_309: ''
  feat_310: ''
  feat_311: ''
  feat_312: ''
  feat_313: ''
  feat_314: ''
  feat_315: ''
  feat_316: ''
  feat_317: ''
  feat_318: ''
  feat_319: ''
  feat_320: ''
  feat_321: ''
  feat_322: ''
  feat_323: ''
  feat_324: ''
  feat_325: ''
  feat_326: ''
  feat_327: ''
  feat_328: ''
  feat_329: ''
  feat_330: ''
  feat_331: ''
  feat_332: ''
  feat_333: ''
  feat_334: ''
  feat_335: ''
  feat_336: ''
  feat_337: ''
  feat_338: ''
  feat_339: ''
  feat_340: ''
  feat_341: ''
  feat_342: ''
  feat_343: ''
  feat_344: ''
  feat_345: ''
  feat_346: ''
  feat_347: ''
  feat_348: ''
  feat_349: ''
  feat_350: ''
  feat_351: ''
  feat_352: ''
  feat_353: ''
  feat_354: ''
  feat_355: ''
  feat_356: ''
  feat_357: ''
  feat_358: ''
  feat_359: ''
  feat_360: ''
  feat_361: ''
  feat_362: ''
  feat_363: ''
  feat_364: ''
  feat_365: ''
  feat_366: ''
  feat_367: ''
  feat_368: ''
  feat_369: ''
  feat_370: ''
  feat_371: ''
  feat_372: ''
  feat_373: ''
  feat_374: ''
  feat_375: ''
  feat_376: ''
  feat_377: ''
  feat_378: ''
  feat_379: ''
  feat_380: ''
  feat_381: ''
  feat_382: ''
  feat_383: ''
  feat_384: ''
  feat_385: ''
  feat_386: ''
  feat_387: ''
  feat_388: ''
  feat_389: ''
  feat_390: ''
  feat_391: ''
  feat_392: ''
  feat_393: ''
  feat_394: ''
  feat_395: ''
  feat_396: ''
  feat_397: ''
  feat_398: ''
  feat_399: ''
  feat_400: ''
  feat_401: ''
  feat_402: ''
  feat_403: ''
  feat_404: ''
  feat_405: ''
  feat_406: ''
  feat_407: ''
  feat_408: ''
  feat_409: ''
  feat_410: ''
  feat_411: ''
  feat_412: ''
  feat_413: ''
  feat_414: ''
  feat_415: ''
  feat_416: ''
  feat_417: ''
  feat_418: ''
  feat_419: ''
  feat_420: ''
  feat_421: ''
  feat_422: ''
  feat_423: ''
  feat_424: ''
  feat_425: ''
  feat_426: ''
  feat_427: ''
  feat_428: ''
  feat_429: ''
  feat_430: ''
  feat_431: ''
  feat_432: ''
  feat_433: ''
  feat_434: ''
  feat_435: ''
  feat_436: ''
  feat_437: ''
  feat_438: ''
  feat_439: ''
  feat_440: ''
  feat_441: ''
  feat_442: ''
  feat_443: ''
  feat_444: ''
  feat_445: ''
  feat_446: ''
  feat_447: ''
  feat_448: ''
  feat_449: ''
  feat_450: ''
  feat_451: ''
  feat_452: ''
  feat_453: ''
  feat_454: ''
  feat_455: ''
  feat_456: ''
  feat_457: ''
  feat_458: ''
  feat_459: ''
  feat_460: ''
  feat_461: ''
  feat_462: ''
  feat_463: ''
  feat_464: ''
  feat_465: ''
  feat_466: ''
  feat_467: ''
  feat_468: ''
  feat_469: ''
  feat_470: ''
  feat_471: ''
  feat_472: ''
  feat_473: ''
  feat_474: ''
  feat_475: ''
  feat_476: ''
  feat_477: ''
  feat_478: ''
  feat_479: ''
  feat_480: ''
  feat_481: ''
  feat_482: ''
  feat_483: ''
  feat_484: ''
  feat_485: ''
  feat_486: ''
  feat_487: ''
  feat_488: ''
  feat_489: ''
  feat_490: ''
  feat_491: ''
  feat_492: ''
  feat_493: ''
  feat_494: ''
  feat_495: ''
  feat_496: ''
  feat_497: ''
  feat_498: ''
  feat_499: ''
  feat_500: ''
  feat_501: ''
  feat_502: ''
  feat_503: ''
  feat_504: ''
  feat_505: ''
  feat_506: ''
  feat_507: ''
  feat_508: ''
  feat_509: ''
  feat_510: ''
  feat_511: ''
  frame_number: Timepoint (unit = frames)
  start_y: ''
  start_x: ''
  zarr_path: ''
  dataset: Name of dataset
  model_manifest_name: ''
  run_name: ''
  resolution_level: ''
  end_y: ''
  end_x: ''
  crop_size_y: ''
  crop_size_x: ''
  position: Zarr file position (FOV) of the corresponding segmentation or patch (crop)
locations:
  20250319_20X:
    fmsid: 51b767a2ac0b4640b41c179b19530bf6
    path: null
    s3uri: null
  20250428_20X:
    fmsid: 7f54e0bedd494741a3ee142b941a2e7e
    path: null
    s3uri: null
  20250611_20X:
    fmsid: 3d91e3aad6ab459887e9f3dfb6cf570b
    path: null
    s3uri: null
  20250618_20X:
    fmsid: 3ac6c5f115274765821f860fb2582280
    path: null
    s3uri: null
  20250714_20X:
    fmsid: 90ac796ad85f4bbd9278d7cf96fd2fa0
    path: null
    s3uri: null
  20250813_20X:
    fmsid: 9899f88faf6a4c22bafb78a193da633f
    path: null
    s3uri: null
  20250818_20X:
    fmsid: 5b4ce14c7a3842c387a86e1fc9ef3d37
    path: null
    s3uri: null
  20250827_20X:
    fmsid: 4533310636be44baa08889aaf261306e
    path: null
    s3uri: null
  20250908_20X:
    fmsid: 139f9524b1674504bdbb4aea41a41e09
    path: null
    s3uri: null
  20251029_20X:
    fmsid: ec6799eb3abb46e299f13dcbc8d09e6a
    path: null
    s3uri: null
  20251119_20X:
    fmsid: c9d0be0baa674df58d596a16659377d3
    path: null
    s3uri: null
  20250326_20X:
    fmsid: 2f8aad2fb2944496bee04d25cf732806
    path: null
    s3uri: null
  20250402_20X:
    fmsid: 8f22780d22ca4ceaba9faeca9b2ce721
    path: null
    s3uri: null
  20250409_20X:
    fmsid: 63b684269e7d445694a8f8ec8ffdf899
    path: null
    s3uri: null
  20250604_20X:
    fmsid: 011c1504a9a2410c83d100f5cee9d33c
    path: null
    s3uri: null
  20250716_20X:
    fmsid: 6ff8743cfeaf48768b812efccaf90e0c
    path: null
    s3uri: null
  20250728_20X:
    fmsid: 2bab5a70d9614034ab9dbaa77ea3db3d
    path: null
    s3uri: null
  20251001_20X:
    fmsid: 0d7d27ab309849518f9425f171d86a7d
    path: null
    s3uri: null
  20260114_20X:
    fmsid: 2a6a8bc3005d49639bcbec0cbc507e58
    path: null
    s3uri: null
  20260121_20X:
    fmsid: 4d58100bd7484f5bbda87a7d209da888
    path: null
    s3uri: null
  20260126_20X:
    fmsid: fadc4d4ca7be4649b4a5ef9153c364df
    path: null
    s3uri: null
  20260128_20X:
    fmsid: e7519411e11945e08d6d952ad9cbc4c3
    path: null
    s3uri: null
  20260202_20X:
    fmsid: 880e3086c3b04162929554a559ed61ff
    path: null
    s3uri: null
  20260204_20X:
    fmsid: 9ecf48154c8447aab0189d116c0f20b4
    path: null
    s3uri: null
  20260209_20X:
    fmsid: 5a3070f4f83f4c16b9cfd03cab0ae1cf
    path: null
    s3uri: null
  20260211_20X:
    fmsid: 2af3673d88bc4176979aec007b9b8845
    path: null
    s3uri: null
  20260216_20X:
    fmsid: bb87fb72ecb048eea19fa42c7d437d60
    path: null
    s3uri: null
  20260225_20X:
    fmsid: 46e463a34c9f4c819bdc60ed7b77f75d
    path: null
    s3uri: null
  20260302_20X:
    fmsid: 56acb7bb782f42059a7d770a3ad00fa2
    path: null
    s3uri: null
  20260304_20X:
    fmsid: fb4a55bf288c4499a5c78a6b7d5d77ed
    path: null
    s3uri: null
  20260309_20X:
    fmsid: 6c5856ff5ccf40158a3e70f4333f4a67
    path: null
    s3uri: null
  20260325_20X:
    fmsid: 1296c638b952469a9553d05c6416a8bc
    path: null
    s3uri: null
