name: diffae_training_dataframe_resolution_1_exclude_cell_piling_test_workflow
workflow: create_diffae_training_dataframe
parameters:
  resolution_level: 1
  z_slice_offsets:
  - 4
  - 11
  include_cell_piling: false
locations:
  training:
    fmsid: 7ca79d8744b04ac3bdaf8b90b2ef6c59
    s3uri: null
  validation:
    fmsid: 7ea052af923141c3bcfd9de8b0c8c41d
    s3uri: null
