name: diffae_training_dataframe_resolution_1_test_workflow
workflow: create_diffae_training_dataframe
parameters:
  resolution_level: 1
locations:
  training:
    fmsid: c31f7e8c75294e0694fe2fbb970db569
    s3uri: null
  validation:
    fmsid: f65666ec82164c95bd193e5dc808c5bd
    s3uri: null
