name: drift_vector_field_polar_theta_grid
workflow: generate_flow_field
parameters:
  model_manifest_name: diffae_baseline
  run_name: latent_512
  crop_pattern: grid
  kernels:
  - column: polar_theta
    name: periodic
    bandwidth: 0.15
    period: 3.141592653589793
  bin_widths: [0.05]
  num_init_samples_for_root_solver: 250
  lower_percentile_for_filtering_fpts: 5.0
  upper_percentile_for_filtering_fpts: 95.0
locations:
  20250409_20X:
    fmsid: dbef5be6b8bc439caf5d6208b69d35ce
    path: null
    s3uri: null
  20251001_20X:
    fmsid: 5fe2196706ee4b11b965200410abb4ae
    path: null
    s3uri: null
