name: drift_fixed_points_grid_based_polar_r_polar_theta_rho_latent_512_bwScale0_kbScale-1
workflow: generate_flow_field
parameters:
  model_manifest_name: diffae_baseline
  run_name: latent_512
  patch_type: grid_based
  kernels:
  - column: polar_theta
    name: periodic
    bandwidth: 0.075
    period: 3.141592653589793
  - column: polar_r
    name: gaussian
    bandwidth: 0.075
    period: null
  - column: rho
    name: gaussian
    bandwidth: 0.075
    period: null
  bin_widths: [0.05, 0.05, 0.05]
  num_init_samples_for_root_solver: 250
  lower_percentile_for_filtering_fpts: 5.0
  upper_percentile_for_filtering_fpts: 95.0
columns: {}
locations:
  20250618_20X:
    fmsid: 1eb086bf73c94e75887a94a469447da2
    path: null
    s3uri: null
  20250319_20X:
    fmsid: 1e1430dd984b42e383a2f7586191809f
    path: null
    s3uri: null
  20250611_20X:
    fmsid: 9dd4051a433240a2ae47f359730cdd16
    path: null
    s3uri: null
  20250618_20X-20250611_20X:
    fmsid: 1d6f8421479248ae84f25ec0b347a36b
    path: null
    s3uri: null
