name: drift_fixed_points_grid_based_polar_r_polar_theta_rho_latent_512_bwScale1_kbScale-1
workflow: generate_flow_field
parameters:
  model_manifest_name: diffae_baseline
  run_name: latent_512
  patch_type: grid_based
  kernels:
  - column: polar_theta
    name: periodic
    bandwidth: 0.075
    period: 3.141592653589793
  - column: polar_r
    name: gaussian
    bandwidth: 0.075
    period: null
  - column: rho
    name: gaussian
    bandwidth: 0.075
    period: null
  bin_widths: [0.1, 0.1, 0.1]
  num_init_samples_for_root_solver: 250
  lower_percentile_for_filtering_fpts: 5.0
  upper_percentile_for_filtering_fpts: 95.0
columns: {}
locations:
  20250618_20X:
    fmsid: 23229f006f7940d3a928f49a6fe7c394
    path: null
    s3uri: null
  20250319_20X:
    fmsid: d245e3bc1b514934853d04d33b08df8f
    path: null
    s3uri: null
  20250611_20X:
    fmsid: 8e2d8d14603b4dbb9413d565d4c297a4
    path: null
    s3uri: null
