name: drift_fixed_points_grid_based_polar_r_polar_theta_rho_latent_512_bwScale0_kbScale1
workflow: generate_flow_field
parameters:
  model_manifest_name: diffae_baseline
  run_name: latent_512
  patch_type: grid_based
  kernels:
  - column: polar_theta
    name: periodic
    bandwidth: 0.3
    period: 3.141592653589793
  - column: polar_r
    name: gaussian
    bandwidth: 0.3
    period: null
  - column: rho
    name: gaussian
    bandwidth: 0.3
    period: null
  bin_widths: [0.05, 0.05, 0.05]
  num_init_samples_for_root_solver: 250
  lower_percentile_for_filtering_fpts: 5.0
  upper_percentile_for_filtering_fpts: 95.0
columns: {}
locations:
  20250618_20X:
    fmsid: e434b8add5cc47d5b967d54157055e71
    path: null
    s3uri: null
  20250319_20X:
    fmsid: 1981ef08d24a4f849e9a1aae73298b81
    path: null
    s3uri: null
  20250611_20X:
    fmsid: 092332c9df964093a106c65a46c04203
    path: null
    s3uri: null
  20250618_20X-20250611_20X:
    fmsid: 67e1229f6100458e92071e0e504b989d
    path: null
    s3uri: null
