name: drift_fixed_points_polar_r_rho_grid_based
workflow: generate_flow_field
parameters:
  model_manifest_name: diffae_baseline
  run_name: latent_512
  patch_type: grid_based
  kernels:
  - column: polar_r
    name: gaussian
    bandwidth: 0.15
    period: null
  - column: rho
    name: gaussian
    bandwidth: 0.15
    period: null
  bin_widths: [0.05, 0.05]
  num_init_samples_for_root_solver: 250
  lower_percentile_for_filtering_fpts: 5.0
  upper_percentile_for_filtering_fpts: 95.0
locations:
  20250409_20X:
    fmsid: 3e8f5e5a452b406bace49311f8ee2c60
    path: null
    s3uri: null
  20251001_20X:
    fmsid: 892f40d442fa40bcb6fa3f3d4ae530f8
    path: null
    s3uri: null
