name: drift_fixed_points_polar_r_rho_grid
workflow: generate_flow_field
parameters:
  model_manifest_name: diffae_baseline
  run_name: latent_512
  crop_pattern: grid
  kernels:
  - column: polar_r
    name: gaussian
    bandwidth: 0.15
    period: null
  - column: rho
    name: gaussian
    bandwidth: 0.15
    period: null
  bin_widths: [0.05, 0.05]
  num_init_samples_for_root_solver: 250
  lower_percentile_for_filtering_fpts: 5.0
  upper_percentile_for_filtering_fpts: 95.0
locations:
  20250409_20X:
    fmsid: 6d8c4b0887b548f3a052ddf92c1189cf
    path: null
    s3uri: null
  20251001_20X:
    fmsid: efb10d99784140eea298e1213cecf24a
    path: null
    s3uri: null
