name: drift_vector_field_grid_based_polar_r_polar_theta_rho_latent_512_bwScale1_kbScale3
workflow: generate_flow_field
parameters:
  model_manifest_name: diffae_baseline
  run_name: latent_512
  patch_type: grid_based
  kernels:
  - column: polar_theta
    name: periodic
    bandwidth: 1.2
    period: 3.141592653589793
  - column: polar_r
    name: gaussian
    bandwidth: 1.2
    period: null
  - column: rho
    name: gaussian
    bandwidth: 1.2
    period: null
  bin_widths: [0.1, 0.1, 0.1]
  num_init_samples_for_root_solver: 250
  lower_percentile_for_filtering_fpts: 5.0
  upper_percentile_for_filtering_fpts: 95.0
columns: {}
locations:
  20250618_20X:
    fmsid: 6b0e651fea674bb28b2b28fef97d9f00
    path: null
    s3uri: null
  20250319_20X:
    fmsid: 62f89e4d4777470e9ff3b0ff7c76e189
    path: null
    s3uri: null
  20250611_20X:
    fmsid: 5e51d0b3942341d6b19f11587b3bc8c9
    path: null
    s3uri: null
  20250618_20X-20250611_20X:
    fmsid: 08bf1a991a994695b9d69865521fdee7
    path: null
    s3uri: null
