name: drift_vector_field_grid_based_polar_r_polar_theta_rho_latent_512_bwScale3_kbScale3
workflow: generate_flow_field
parameters:
  model_manifest_name: diffae_baseline
  run_name: latent_512
  patch_type: grid_based
  kernels:
  - column: polar_theta
    name: periodic
    bandwidth: 1.2
    period: 3.141592653589793
  - column: polar_r
    name: gaussian
    bandwidth: 1.2
    period: null
  - column: rho
    name: gaussian
    bandwidth: 1.2
    period: null
  bin_widths: [0.4, 0.4, 0.4]
  num_init_samples_for_root_solver: 250
  lower_percentile_for_filtering_fpts: 5.0
  upper_percentile_for_filtering_fpts: 95.0
columns: {}
locations:
  20250618_20X:
    fmsid: 938d7455620f413e8b9c718618343267
    path: null
    s3uri: null
  20250319_20X:
    fmsid: 9d515555863c4ffab3e1ac8d48dc2068
    path: null
    s3uri: null
  20250611_20X:
    fmsid: 36b5f1bbd29c4bd386463a3653fd38f0
    path: null
    s3uri: null
  20250618_20X-20250611_20X:
    fmsid: bcd33f7973184a3d8ab0e2064182ce74
    path: null
    s3uri: null
