name: drift_fixed_points_polar_r_polar_theta_rho_grid_based
workflow: generate_flow_field
parameters:
  model_manifest_name: diffae_baseline
  run_name: latent_512
  patch_type: grid_based
  kernels:
  - column: polar_theta
    name: periodic
    bandwidth: 0.15
    period: 3.141592653589793
  - column: polar_r
    name: gaussian
    bandwidth: 0.15
    period: null
  - column: rho
    name: gaussian
    bandwidth: 0.15
    period: null
  bin_widths: [0.05, 0.05, 0.05]
  num_init_samples_for_root_solver: 250
  lower_percentile_for_filtering_fpts: 5.0
  upper_percentile_for_filtering_fpts: 95.0
columns:
  stability: Stability classification of a fixed point
  polar_theta_fixed_point: Vector field fixed point location in theta
  polar_r_fixed_point: Vector field fixed point location in r
  rho_fixed_point: Vector field fixed point location in rho
  dataset: Name of dataset
  shear_stress: Shear stress value [dyn/cm^2]
locations:
  20250319_20X:
    fmsid: c3f6148218764e7f970f7b8cc1e58cb2
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/drift_fixed_points_polar_r_polar_theta_rho_grid_based/20250319_0d94f8d3054e4e8c99af07dd92774798.parquet
  20250326_20X:
    fmsid: 8c85b56d244840ddb2bed52e540b19a6
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/drift_fixed_points_polar_r_polar_theta_rho_grid_based/20250326_eb97addf262c44c5a6117ad1d4acc353.parquet
  20250402_20X:
    fmsid: 75a2f3d19a7747bbb8d8c74299f4eacb
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/drift_fixed_points_polar_r_polar_theta_rho_grid_based/20250402_90e37b7d8f1440efa84995b4697fb269.parquet
  20250409_20X:
    fmsid: 877398edeef749e9bf5079edcf7dfa8e
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/drift_fixed_points_polar_r_polar_theta_rho_grid_based/20250409_df6b2a02bbc94c6f957923add524eac1.parquet
  20250428_20X:
    fmsid: ce9ea2ef949444d1ad27ea3ff6338bf2
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/drift_fixed_points_polar_r_polar_theta_rho_grid_based/20250428_056aa027ba9f4ccd98367563552f7edd.parquet
  20250604_20X:
    fmsid: 574ced6033ec4724a9bfbe8ab151a90a
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/drift_fixed_points_polar_r_polar_theta_rho_grid_based/20250604_3f08ef7a2e0e450d963352dae4bf17dc.parquet
  20250611_20X:
    fmsid: b6ace668a5e049a7b256921f33db831b
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/drift_fixed_points_polar_r_polar_theta_rho_grid_based/20250611_a32615d530ae42c29d159cc058601879.parquet
  20250618_20X:
    fmsid: 8b66bec9e17e4a3ba317186840d6b9b5
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/drift_fixed_points_polar_r_polar_theta_rho_grid_based/20250618_f81e9bdf048e462e9755d7cbf5d21c37.parquet
  20250716_20X:
    fmsid: 06168ffae1fe441088da6d625014048b
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/drift_fixed_points_polar_r_polar_theta_rho_grid_based/20250716_328c62ecc91248eab2268e546892453e.parquet
  20250813_20X:
    fmsid: 743065501e8a483c8c30cefe9b4a9270
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/drift_fixed_points_polar_r_polar_theta_rho_grid_based/20250813_6ab0f70bd43f4de987a789905dbfb95c.parquet
  20250908_20X:
    fmsid: 5cf99b05e3eb41b0bff69e3b4a66582b
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/drift_fixed_points_polar_r_polar_theta_rho_grid_based/20250908_b5d434bdebce4053b2d90198541b6b59.parquet
  20251001_20X:
    fmsid: 0ebc532a8cd54ebab7d019cdd81302d0
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/drift_fixed_points_polar_r_polar_theta_rho_grid_based/20251001_271124f03a16409499e8a84b0030cb15.parquet
  20251029_20X:
    fmsid: 25dc45a134584a088b94bd8c5cb0f380
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/drift_fixed_points_polar_r_polar_theta_rho_grid_based/20251029_441aed50cff54667afce891eb3a1a8db.parquet
  20251119_20X:
    fmsid: 36a750e508da4dd3ba4e6b8c80a759a1
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/drift_fixed_points_polar_r_polar_theta_rho_grid_based/20251119_d6449a79a6264466aa225af0cdef78c7.parquet
  20260114_20X:
    fmsid: 04495d7b3bf849e198839a4200db52dc
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/drift_fixed_points_polar_r_polar_theta_rho_grid_based/20260114_4b693bb8eedb4e0ba0cb9ab4ae07b1a2.parquet
  20260121_20X:
    fmsid: b2b39ccdeb684e8eaa9f48b78bf36b7b
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/drift_fixed_points_polar_r_polar_theta_rho_grid_based/20260121_ff75e124720b4a3aa035025a05ced25f.parquet
  20260126_20X:
    fmsid: a54170444031456caf943aba0e9b3517
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/drift_fixed_points_polar_r_polar_theta_rho_grid_based/20260126_aed19d79c1a34707925cfa8393424c45.parquet
  20260128_20X:
    fmsid: 4d6277468efa4955892d81ff829b48cf
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/drift_fixed_points_polar_r_polar_theta_rho_grid_based/20260128_00bd94ea6d7e4b46bc16a55e35de589d.parquet
  20260202_20X:
    fmsid: 717e3a03455a478ab39d715de2cbbc43
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/drift_fixed_points_polar_r_polar_theta_rho_grid_based/20260202_fcb18a65bb734ff6ae718e1eee4894d6.parquet
  20260204_20X:
    fmsid: c769b0a2a13c4b938e9eb8d601aa291b
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/drift_fixed_points_polar_r_polar_theta_rho_grid_based/20260204_ac1fddfd7452481e83317c8fbdd59dd6.parquet
  20260209_20X:
    fmsid: 3922c452e722473c814685164ce6c510
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/drift_fixed_points_polar_r_polar_theta_rho_grid_based/20260209_3700e11f893e4f378db450ea91bd92d6.parquet
  20260211_20X:
    fmsid: 2b874a4a8db04e7184f1114fb0c6cf6f
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/drift_fixed_points_polar_r_polar_theta_rho_grid_based/20260211_20b76dc8d0ca488ba88816793830f6ec.parquet
  20260216_20X:
    fmsid: 67bbaf4f035a4e88baf795b4ce3903f0
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/drift_fixed_points_polar_r_polar_theta_rho_grid_based/20260216_ed3743a1ee4c4cb096f5af90e3ebb9bd.parquet
  20260225_20X:
    fmsid: 9fa56d8952ae4c52b9ed94304145ce40
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/drift_fixed_points_polar_r_polar_theta_rho_grid_based/20260225_50afe3cb17cf4be099dc44e47f7a4ae4.parquet
  20260302_20X:
    fmsid: a2809ed40e1d45c5bd84e1a32e94576d
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/drift_fixed_points_polar_r_polar_theta_rho_grid_based/20260302_e9cfa3b0b24447f7bba000af3b012427.parquet
  20260304_20X:
    fmsid: 349cafb22fb8498e96ccfcc683f54bf1
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/drift_fixed_points_polar_r_polar_theta_rho_grid_based/20260304_56c81f459d8e46eabd74cc2147b85f49.parquet
  20260309_20X:
    fmsid: 8c4636720ac347c98f61127fcbfdd290
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/drift_fixed_points_polar_r_polar_theta_rho_grid_based/20260309_1a52b127112347d4b805eb64d0b86757.parquet
  20260325_20X:
    fmsid: da5548c467754876b0a0f62896df85f2
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/drift_fixed_points_polar_r_polar_theta_rho_grid_based/20260325_d1f28b79cf574775b529d83626183abc.parquet
