name: drift_fixed_points_grid_based_polar_r_polar_theta_rho_latent_512_bwScale2_kbScale-1
workflow: generate_flow_field
parameters:
  model_manifest_name: diffae_baseline
  run_name: latent_512
  patch_type: grid_based
  kernels:
  - column: polar_theta
    name: periodic
    bandwidth: 0.075
    period: 3.141592653589793
  - column: polar_r
    name: gaussian
    bandwidth: 0.075
    period: null
  - column: rho
    name: gaussian
    bandwidth: 0.075
    period: null
  bin_widths: [0.2, 0.2, 0.2]
  num_init_samples_for_root_solver: 250
  lower_percentile_for_filtering_fpts: 5.0
  upper_percentile_for_filtering_fpts: 95.0
columns: {}
locations:
  20250618_20X:
    fmsid: 774ffcd0bd2841bc957601ee526bac1a
    path: null
    s3uri: null
  20250319_20X:
    fmsid: 89536fc496af46d583ee6ea92b31b776
    path: null
    s3uri: null
  20250611_20X:
    fmsid: fb1c94dd36834c0a9cc9a4d6f08a7259
    path: null
    s3uri: null
  20250618_20X-20250611_20X:
    fmsid: 67aee747c8b74f55ae29bc8cb79ca7cc
    path: null
    s3uri: null
