name: drift_fixed_points_grid_based_polar_r_polar_theta_rho_latent_512_bwScale-1_kbScale0
workflow: generate_flow_field
parameters:
  model_manifest_name: diffae_baseline
  run_name: latent_512
  patch_type: grid_based
  kernels:
  - column: polar_theta
    name: periodic
    bandwidth: 0.15
    period: 3.141592653589793
  - column: polar_r
    name: gaussian
    bandwidth: 0.15
    period: null
  - column: rho
    name: gaussian
    bandwidth: 0.15
    period: null
  bin_widths: [0.025, 0.025, 0.025]
  num_init_samples_for_root_solver: 250
  lower_percentile_for_filtering_fpts: 5.0
  upper_percentile_for_filtering_fpts: 95.0
columns: {}
locations:
  20250618_20X:
    fmsid: f977e332a52f4353a55b69224e20a64e
    path: null
    s3uri: null
  20250319_20X:
    fmsid: a7486f047dde4c539291b6aa9e6e9786
    path: null
    s3uri: null
  20250611_20X:
    fmsid: 8ad2420ffa204a4488b45fc89b59d39e
    path: null
    s3uri: null
