name: drift_fixed_points_grid_based_polar_r_polar_theta_rho_latent_512_bwScale2_kbScale2
workflow: generate_flow_field
parameters:
  model_manifest_name: diffae_baseline
  run_name: latent_512
  patch_type: grid_based
  kernels:
  - column: polar_theta
    name: periodic
    bandwidth: 0.6
    period: 3.141592653589793
  - column: polar_r
    name: gaussian
    bandwidth: 0.6
    period: null
  - column: rho
    name: gaussian
    bandwidth: 0.6
    period: null
  bin_widths: [0.2, 0.2, 0.2]
  num_init_samples_for_root_solver: 250
  lower_percentile_for_filtering_fpts: 5.0
  upper_percentile_for_filtering_fpts: 95.0
columns: {}
locations:
  20250618_20X:
    fmsid: ef15552db39e4df28b1125e135ed22f6
    path: null
    s3uri: null
  20250319_20X:
    fmsid: 093b0ff7e0b14c439fa505e470783a2d
    path: null
    s3uri: null
  20250611_20X:
    fmsid: c942cf3c27714365a51014c25cb848fd
    path: null
    s3uri: null
