name: drift_fixed_points_grid_based_polar_r_polar_theta_rho_latent_512_bwScale1_kbScale2
workflow: generate_flow_field
parameters:
  model_manifest_name: diffae_baseline
  run_name: latent_512
  patch_type: grid_based
  kernels:
  - column: polar_theta
    name: periodic
    bandwidth: 0.6
    period: 3.141592653589793
  - column: polar_r
    name: gaussian
    bandwidth: 0.6
    period: null
  - column: rho
    name: gaussian
    bandwidth: 0.6
    period: null
  bin_widths: [0.1, 0.1, 0.1]
  num_init_samples_for_root_solver: 250
  lower_percentile_for_filtering_fpts: 5.0
  upper_percentile_for_filtering_fpts: 95.0
columns: {}
locations:
  20250618_20X:
    fmsid: 55bbc401292a4928bae4fcf106c546bf
    path: null
    s3uri: null
  20250319_20X:
    fmsid: a8ce3048c4f044df9d8677e6095c59d0
    path: null
    s3uri: null
  20250611_20X:
    fmsid: b4f21c5759924629bb793a9cf2e2a855
    path: null
    s3uri: null
  20250618_20X-20250611_20X:
    fmsid: 87f26f02f8bc4ecdb340a86855c07df2
    path: null
    s3uri: null
