name: grid_based_features_unfiltered
workflow: calculate-pca-features
parameters:
  model_manifest_name: diffae_baseline_exclude_cell_piling
  run_name: 20251110_latent_512
  crop_pattern: grid
  filtered: false
columns:
  frame_number: ''
  start_y: ''
  start_x: ''
  zarr_path: ''
  dataset: Name of dataset
  model_manifest_name: ''
  run_name: ''
  resolution_level: ''
  end_y: ''
  end_x: ''
  crop_size_y: ''
  crop_size_x: ''
  position: ''
  crop_index: ''
  pc_1: ''
  pc_2: ''
  pc_3: ''
  pc_4: ''
  pc_5: ''
  pc_6: ''
  pc_7: ''
  pc_8: ''
  pc_9: ''
  pc_10: ''
  pc_11: ''
  pc_12: ''
  pc_13: ''
  pc_14: ''
  pc_15: ''
  pc_16: ''
  pc_17: ''
  pc_18: ''
  pc_19: ''
  pc_20: ''
  pc_21: ''
  pc_22: ''
  pc_23: ''
  pc_24: ''
  pc_25: ''
  pc_26: ''
  pc_27: ''
  pc_28: ''
  pc_29: ''
  pc_30: ''
  pc_31: ''
  pc_32: ''
  pc_33: ''
  pc_34: ''
  pc_35: ''
  pc_36: ''
  pc_37: ''
  pc_38: ''
  pc_39: ''
  pc_40: ''
  pc_41: ''
  pc_42: ''
  pc_43: ''
  pc_44: ''
  pc_45: ''
  pc_46: ''
  pc_47: ''
  pc_48: ''
  pc_49: ''
  pc_50: ''
  pc_51: ''
  pc_52: ''
  pc_53: ''
  pc_54: ''
  pc_55: ''
  pc_56: ''
  pc_57: ''
  pc_58: ''
  pc_59: ''
  pc_60: ''
  pc_61: ''
  pc_62: ''
  pc_63: ''
  pc_64: ''
  pc_65: ''
  pc_66: ''
  pc_67: ''
  pc_68: ''
  pc_69: ''
  pc_70: ''
  pc_71: ''
  pc_72: ''
  pc_73: ''
  pc_74: ''
  pc_75: ''
  pc_76: ''
  pc_77: ''
  pc_78: ''
  pc_79: ''
  pc_80: ''
  pc_81: ''
  pc_82: ''
  pc_83: ''
  pc_84: ''
  pc_85: ''
  pc_86: ''
  pc_87: ''
  pc_88: ''
  pc_89: ''
  pc_90: ''
  pc_91: ''
  pc_92: ''
  pc_93: ''
  pc_94: ''
  pc_95: ''
  pc_96: ''
  pc_97: ''
  pc_98: ''
  pc_99: ''
  pc_100: ''
  pc_101: ''
  pc_102: ''
  pc_103: ''
  pc_104: ''
  pc_105: ''
  pc_106: ''
  pc_107: ''
  pc_108: ''
  pc_109: ''
  pc_110: ''
  pc_111: ''
  pc_112: ''
  pc_113: ''
  pc_114: ''
  pc_115: ''
  pc_116: ''
  pc_117: ''
  pc_118: ''
  pc_119: ''
  pc_120: ''
  pc_121: ''
  pc_122: ''
  pc_123: ''
  pc_124: ''
  pc_125: ''
  pc_126: ''
  pc_127: ''
  pc_128: ''
  pc_129: ''
  pc_130: ''
  pc_131: ''
  pc_132: ''
  pc_133: ''
  pc_134: ''
  pc_135: ''
  pc_136: ''
  pc_137: ''
  pc_138: ''
  pc_139: ''
  pc_140: ''
  pc_141: ''
  pc_142: ''
  pc_143: ''
  pc_144: ''
  pc_145: ''
  pc_146: ''
  pc_147: ''
  pc_148: ''
  pc_149: ''
  pc_150: ''
  pc_151: ''
  pc_152: ''
  pc_153: ''
  pc_154: ''
  pc_155: ''
  pc_156: ''
  pc_157: ''
  pc_158: ''
  pc_159: ''
  pc_160: ''
  pc_161: ''
  pc_162: ''
  pc_163: ''
  pc_164: ''
  pc_165: ''
  pc_166: ''
  pc_167: ''
  pc_168: ''
  pc_169: ''
  pc_170: ''
  pc_171: ''
  pc_172: ''
  pc_173: ''
  pc_174: ''
  pc_175: ''
  pc_176: ''
  pc_177: ''
  pc_178: ''
  pc_179: ''
  pc_180: ''
  pc_181: ''
  pc_182: ''
  pc_183: ''
  pc_184: ''
  pc_185: ''
  pc_186: ''
  pc_187: ''
  pc_188: ''
  pc_189: ''
  pc_190: ''
  pc_191: ''
  pc_192: ''
  pc_193: ''
  pc_194: ''
  pc_195: ''
  pc_196: ''
  pc_197: ''
  pc_198: ''
  pc_199: ''
  pc_200: ''
  pc_201: ''
  pc_202: ''
  pc_203: ''
  pc_204: ''
  pc_205: ''
  pc_206: ''
  pc_207: ''
  pc_208: ''
  pc_209: ''
  pc_210: ''
  pc_211: ''
  pc_212: ''
  pc_213: ''
  pc_214: ''
  pc_215: ''
  pc_216: ''
  pc_217: ''
  pc_218: ''
  pc_219: ''
  pc_220: ''
  pc_221: ''
  pc_222: ''
  pc_223: ''
  pc_224: ''
  pc_225: ''
  pc_226: ''
  pc_227: ''
  pc_228: ''
  pc_229: ''
  pc_230: ''
  pc_231: ''
  pc_232: ''
  pc_233: ''
  pc_234: ''
  pc_235: ''
  pc_236: ''
  pc_237: ''
  pc_238: ''
  pc_239: ''
  pc_240: ''
  pc_241: ''
  pc_242: ''
  pc_243: ''
  pc_244: ''
  pc_245: ''
  pc_246: ''
  pc_247: ''
  pc_248: ''
  pc_249: ''
  pc_250: ''
  pc_251: ''
  pc_252: ''
  pc_253: ''
  pc_254: ''
  pc_255: ''
  pc_256: ''
  pc_257: ''
  pc_258: ''
  pc_259: ''
  pc_260: ''
  pc_261: ''
  pc_262: ''
  pc_263: ''
  pc_264: ''
  pc_265: ''
  pc_266: ''
  pc_267: ''
  pc_268: ''
  pc_269: ''
  pc_270: ''
  pc_271: ''
  pc_272: ''
  pc_273: ''
  pc_274: ''
  pc_275: ''
  pc_276: ''
  pc_277: ''
  pc_278: ''
  pc_279: ''
  pc_280: ''
  pc_281: ''
  pc_282: ''
  pc_283: ''
  pc_284: ''
  pc_285: ''
  pc_286: ''
  pc_287: ''
  pc_288: ''
  pc_289: ''
  pc_290: ''
  pc_291: ''
  pc_292: ''
  pc_293: ''
  pc_294: ''
  pc_295: ''
  pc_296: ''
  pc_297: ''
  pc_298: ''
  pc_299: ''
  pc_300: ''
  pc_301: ''
  pc_302: ''
  pc_303: ''
  pc_304: ''
  pc_305: ''
  pc_306: ''
  pc_307: ''
  pc_308: ''
  pc_309: ''
  pc_310: ''
  pc_311: ''
  pc_312: ''
  pc_313: ''
  pc_314: ''
  pc_315: ''
  pc_316: ''
  pc_317: ''
  pc_318: ''
  pc_319: ''
  pc_320: ''
  pc_321: ''
  pc_322: ''
  pc_323: ''
  pc_324: ''
  pc_325: ''
  pc_326: ''
  pc_327: ''
  pc_328: ''
  pc_329: ''
  pc_330: ''
  pc_331: ''
  pc_332: ''
  pc_333: ''
  pc_334: ''
  pc_335: ''
  pc_336: ''
  pc_337: ''
  pc_338: ''
  pc_339: ''
  pc_340: ''
  pc_341: ''
  pc_342: ''
  pc_343: ''
  pc_344: ''
  pc_345: ''
  pc_346: ''
  pc_347: ''
  pc_348: ''
  pc_349: ''
  pc_350: ''
  pc_351: ''
  pc_352: ''
  pc_353: ''
  pc_354: ''
  pc_355: ''
  pc_356: ''
  pc_357: ''
  pc_358: ''
  pc_359: ''
  pc_360: ''
  pc_361: ''
  pc_362: ''
  pc_363: ''
  pc_364: ''
  pc_365: ''
  pc_366: ''
  pc_367: ''
  pc_368: ''
  pc_369: ''
  pc_370: ''
  pc_371: ''
  pc_372: ''
  pc_373: ''
  pc_374: ''
  pc_375: ''
  pc_376: ''
  pc_377: ''
  pc_378: ''
  pc_379: ''
  pc_380: ''
  pc_381: ''
  pc_382: ''
  pc_383: ''
  pc_384: ''
  pc_385: ''
  pc_386: ''
  pc_387: ''
  pc_388: ''
  pc_389: ''
  pc_390: ''
  pc_391: ''
  pc_392: ''
  pc_393: ''
  pc_394: ''
  pc_395: ''
  pc_396: ''
  pc_397: ''
  pc_398: ''
  pc_399: ''
  pc_400: ''
  pc_401: ''
  pc_402: ''
  pc_403: ''
  pc_404: ''
  pc_405: ''
  pc_406: ''
  pc_407: ''
  pc_408: ''
  pc_409: ''
  pc_410: ''
  pc_411: ''
  pc_412: ''
  pc_413: ''
  pc_414: ''
  pc_415: ''
  pc_416: ''
  pc_417: ''
  pc_418: ''
  pc_419: ''
  pc_420: ''
  pc_421: ''
  pc_422: ''
  pc_423: ''
  pc_424: ''
  pc_425: ''
  pc_426: ''
  pc_427: ''
  pc_428: ''
  pc_429: ''
  pc_430: ''
  pc_431: ''
  pc_432: ''
  pc_433: ''
  pc_434: ''
  pc_435: ''
  pc_436: ''
  pc_437: ''
  pc_438: ''
  pc_439: ''
  pc_440: ''
  pc_441: ''
  pc_442: ''
  pc_443: ''
  pc_444: ''
  pc_445: ''
  pc_446: ''
  pc_447: ''
  pc_448: ''
  pc_449: ''
  pc_450: ''
  pc_451: ''
  pc_452: ''
  pc_453: ''
  pc_454: ''
  pc_455: ''
  pc_456: ''
  pc_457: ''
  pc_458: ''
  pc_459: ''
  pc_460: ''
  pc_461: ''
  pc_462: ''
  pc_463: ''
  pc_464: ''
  pc_465: ''
  pc_466: ''
  pc_467: ''
  pc_468: ''
  pc_469: ''
  pc_470: ''
  pc_471: ''
  pc_472: ''
  pc_473: ''
  pc_474: ''
  pc_475: ''
  pc_476: ''
  pc_477: ''
  pc_478: ''
  pc_479: ''
  pc_480: ''
  pc_481: ''
  pc_482: ''
  pc_483: ''
  pc_484: ''
  pc_485: ''
  pc_486: ''
  pc_487: ''
  pc_488: ''
  pc_489: ''
  pc_490: ''
  pc_491: ''
  pc_492: ''
  pc_493: ''
  pc_494: ''
  pc_495: ''
  pc_496: ''
  pc_497: ''
  pc_498: ''
  pc_499: ''
  pc_500: ''
  pc_501: ''
  pc_502: ''
  pc_503: ''
  pc_504: ''
  pc_505: ''
  pc_506: ''
  pc_507: ''
  pc_508: ''
  pc_509: ''
  pc_510: ''
  pc_511: ''
  pc_512: ''
  polar_r: ''
  polar_theta: ''
  rho: ''
locations:
  20250319_20X:
    fmsid: 7503e28fd4774e5ba3f086e34182960c
    path: null
    s3uri: null
  20250326_20X:
    fmsid: e38f950478b14d6c8ae933164ed50cf4
    path: null
    s3uri: null
  20250402_20X:
    fmsid: 37417d00700542fa992cbbb0f396af88
    path: null
    s3uri: null
  20250409_20X:
    fmsid: 8b411f4c5fd54f7e87a2d14934572a98
    path: null
    s3uri: null
  20250428_20X:
    fmsid: 26eabfdfc954417da4565f325875578d
    path: null
    s3uri: null
  20250604_20X:
    fmsid: 4e0e7fb645104541a997f3668764ca80
    path: null
    s3uri: null
  20250611_20X:
    fmsid: 49f7cfda3db2497ebf569d68a3af368a
    path: null
    s3uri: null
  20250618_20X:
    fmsid: dc7ef99eeb9940eda60bdf27cc7379ec
    path: null
    s3uri: null
  20250714_20X:
    fmsid: 66d1f54c2a0c409e956a23388e18f6c6
    path: null
    s3uri: null
  20250716_20X:
    fmsid: 6f4bff6ed19145e4b919676a079f593e
    path: null
    s3uri: null
  20250728_20X:
    fmsid: bd27ff16ac474acf97ef7da1ba6624df
    path: null
    s3uri: null
  20250813_20X:
    fmsid: f4349d2cd1d24020b1b870a1da6bf9a8
    path: null
    s3uri: null
  20250818_20X:
    fmsid: eb6a982869b74f519ba04af6eda40620
    path: null
    s3uri: null
  20250827_20X:
    fmsid: b55072ede65646d7a478882d08d4a796
    path: null
    s3uri: null
  20250908_20X:
    fmsid: 89f1869010b64231bf5b74037cc21e5e
    path: null
    s3uri: null
  20251001_20X:
    fmsid: 1ad23fe0c1b348fca2eea931bbb5e981
    path: null
    s3uri: null
  20251029_20X:
    fmsid: 9c0567daa7304c98b4f2ba7c2dbc8d22
    path: null
    s3uri: null
  20251119_20X:
    fmsid: 81e1ffba169d43fc979358b402e751bb
    path: null
    s3uri: null
  20260114_20X:
    fmsid: 0bc90e893fc9494fb2c9d85c466fae9e
    path: null
    s3uri: null
  20260121_20X:
    fmsid: 834e16e603fe409184ff25c299ad758d
    path: null
    s3uri: null
  20260126_20X:
    fmsid: bf67a758dd6349b4a0226eea9a894161
    path: null
    s3uri: null
  20260128_20X:
    fmsid: e6618751a5a948f59442f572dcd30670
    path: null
    s3uri: null
  20260202_20X:
    fmsid: 0af8c57d790c445aba15b53843ee7561
    path: null
    s3uri: null
  20260204_20X:
    fmsid: 6f85bb6c393544a9b233f98b06a296bd
    path: null
    s3uri: null
  20260209_20X:
    fmsid: 256e8eb7cd8245fe8a58609b6d5aba14
    path: null
    s3uri: null
  20260211_20X:
    fmsid: 3d2523a544a84b1cae75c0b2f540e765
    path: null
    s3uri: null
  20260216_20X:
    fmsid: 49ad3e1def374a0689f8159953de3465
    path: null
    s3uri: null
  20260225_20X:
    fmsid: d6d4418cf2d5402e8c24d097b94e8f20
    path: null
    s3uri: null
  20260302_20X:
    fmsid: b5c801bc1abe466ca72fca8345abe7ea
    path: null
    s3uri: null
  20260304_20X:
    fmsid: 96c0e55a011d4e9890411dbe56c49af4
    path: null
    s3uri: null
  20260309_20X:
    fmsid: c4b7cc583ead436b9270cea15d7c310a
    path: null
    s3uri: null
  20260325_20X:
    fmsid: eeda7a87bdcd4a0383b9ebd039bba25a
    path: null
    s3uri: null
