name: incoherent_migration_annotations
workflow: manual_annotations
parameters: {}
locations:
  incoherent_mig_20250319_20X_P2:
    fmsid: null
    path: "//allen/aics/users/chantelle.leveille/annotations/mixed_mig/12.2 shear stress 20250319_20X_P2-annotations.csv"
    s3uri: null
  incoherent_mig_20250319_20X_P3:
    fmsid: null
    path: "//allen/aics/users/chantelle.leveille/annotations/mixed_mig/12.2 shear stress 20250319_20X_P3-annotations.csv"
    s3uri: null
  incoherent_mig_20250813_20X_P0:
    fmsid: null
    path: "//allen/aics/users/chantelle.leveille/annotations/mixed_mig/14.65 shear stress 20250813_20X_P0-annotations.csv"
    s3uri: null
  incoherent_mig_20250813_20X_P1:
    fmsid: null
    path: "//allen/aics/users/chantelle.leveille/annotations/mixed_mig/14.65 shear stress 20250813_20X_P1-annotations.csv"
    s3uri: null
  incoherent_mig_20250813_20X_P4:
    fmsid: null
    path: "//allen/aics/users/chantelle.leveille/annotations/mixed_mig/14.65 shear stress 20250813_20X_P4-annotations.csv"
    s3uri: null
