name: merged_segmentation_features
workflow: merge_segmentation_feature_tables
parameters: {}
columns:
  frame_number: Timepoint (unit = frames)
  track_id: Track ID assigned by the tracking algorithm
  reference_index: ''
  matched_query_label: ''
  optimized_metric_value: ''
  matching_method: ''
  dataset: Name of dataset
  position: Zarr file position (FOV) of the corresponding segmentation or patch (crop)
  zarr_path: Path to Zarr file for image that patch (crop) comes from
  filepath_segmentation_image: ''
  label: Cell segmentation ID (different from track ID, and may change between timepoints)
  centroid: ''
  area_px_squared: ''
  perimeter_px: ''
  solidity: ''
  major_axis_length: ''
  minor_axis_length: ''
  eccentricity: ''
  orientation: ''
  cell_fluorescence_mean_au: ''
  cell_fluorescence_std_au: ''
  cell_fluorescence_median_au: ''
  cell_fluorescence_min_au: ''
  cell_fluorescence_pct25_au: ''
  cell_fluorescence_pct75_au: ''
  cell_fluorescence_max_au: ''
  neighboring_cell_labels: ''
  edge_labels: ''
  node_labels: ''
  node_pair_labels: ''
  edge_fluorescence_au: ''
  node_fluorescence_au: ''
  is_edge_segmentation: ''
  nuclei_segmentation_labels: ''
  nuclei_seg_in_cdh5_seg_frac: ''
  nuc_seg_intens_means_EGFP: ''
  nuc_seg_intens_means_BF: ''
  nuc_seg_intens_stds_EGFP: ''
  nuc_seg_intens_stds_BF: ''
  nuc_seg_intens_medians_EGFP: ''
  nuc_seg_intens_medians_BF: ''
  nuc_seg_intens_pct25s_EGFP: ''
  nuc_seg_intens_pct25s_BF: ''
  nuc_seg_intens_pct75s_EGFP: ''
  nuc_seg_intens_pct75s_BF: ''
  nuc_seg_intens_maxs_EGFP: ''
  nuc_seg_intens_maxs_BF: ''
  nuc_seg_intens_mins_EGFP: ''
  nuc_seg_intens_mins_BF: ''
  nuclei_seg_with_most_overlap_0: ''
  nuc_with_most_overlap_0_centroid_Y: ''
  nuc_with_most_overlap_0_centroid_X: ''
  nuclei_seg_with_most_overlap_1: ''
  nuc_with_most_overlap_1_centroid_Y: ''
  nuc_with_most_overlap_1_centroid_X: ''
  total_nuclei_count_at_T: ''
  nuclei_seg_with_most_overlap_2: ''
  nuc_with_most_overlap_2_centroid_Y: ''
  nuc_with_most_overlap_2_centroid_X: ''
  nuclei_seg_with_most_overlap_3: ''
  nuc_with_most_overlap_3_centroid_Y: ''
  nuc_with_most_overlap_3_centroid_X: ''
  nuclei_seg_with_most_overlap_4: ''
  nuc_with_most_overlap_4_centroid_Y: ''
  nuc_with_most_overlap_4_centroid_X: ''
  nuclei_seg_with_most_overlap_5: ''
  nuc_with_most_overlap_5_centroid_Y: ''
  nuc_with_most_overlap_5_centroid_X: ''
  shear_stress_regime: Experimentalist categorization of the shear stress response
  time_resolution_minutes: Time resolution of the timelapse in minutes
  time_minutes: Time in minutes since the start of the timelapse
  time_hours: Time in hours since the start of the timelapse
  num_unique_tracks_per_timeframe: ''
  gaussian_sigma_for_area_smoothing: ''
  smoothed_area_normd: ''
  smoothed_area_normd_diff: ''
  num_unique_tracks_before_filtering_at_T: Number of unique tracks that are present at the timepoint
    of interest before filtering
  track_duration: Number of timepoints in the track
  alignment: ''
  alignment_deg: ''
  orientation_deg: ''
  nematic_order: ''
  aspect_ratio: ''
  pixel_size_xy_in_um: Size of a pixel in the XY dimensions in microns
  area_um_squared: ''
  perimeter_um: ''
  edge_fluorescence_mean_au: ''
  edge_fluorescence_std_au: ''
  node_fluorescence_mean_au: ''
  node_fluorescence_std_au: ''
  edge_and_node_fluorescence_mean_au: ''
  edge_and_node_fluorescence_std_au: ''
  number_of_neighbors: ''
  image_size_x: Size of the whole image in the X dimension in pixels
  image_size_y: Size of the whole image in the Y dimension in pixels
  cdh5_channel_index_in_zarr: Index of the CDH5 channel in the Zarr file
  brightfield_channel_index_zarr: Index of the brightfield channel in the Zarr file
  num_nuclei_with_most_overlap: ''
  centroid_y: ''
  centroid_x: ''
  nuclei_position_x: ''
  nuclei_position_y: ''
  nuclei_position_distance: ''
  nuclei_position_angle: ''
  nuclei_position_angle_deg: ''
  crop_size: Size of the crop in pixels at resolution level 0
  start_x_resolution_0: X-coordinate of upper left corner of patch (crop) in pixels (zarr resolution
    level 0)
  start_y_resolution_0: Y-coordinate of upper left corner of patch (crop) in pixels (zarr resolution
    level 0)
  end_x_resolution_0: X-coordinate of lower right corner of patch (crop) in pixels (zarr resolution
    level 0)
  end_y_resolution_0: Y-coordinate of lower right corner of patch (crop) in pixels (zarr resolution
    level 0)
  bbox_is_in_bounds: ''
  diffae_resolution_level_to_use: DiffAE feature resolution level used to downsample resolution 0 coordinates
  num_nuclei_in_crop: Number of label-free predicted nuclei in a crop/cell-centered patch
  all_labels_in_crop: List of all segmentation labels found within a crop/cell-centered patch
  min_track_duration: ''
  is_greater_than_min_track_duration: ''
  max_smoothed_area_normd_change: ''
  is_less_than_max_smoothed_area_normd_change: ''
  is_included: ''
  num_valid_tp_per_track: ''
  min_num_valid_tp_per_track: ''
  has_more_than_min_num_valid_points_per_track: ''
  num_unique_tracks_after_filtering_at_T: Number of unique tracks that pass filtering criteria at the
    timepoint of interest
  auto_bf_scope_error: ''
  auto_bf_temp_artifact: ''
  auto_gfp_scope_error: ''
  bf_scope_error: ''
  cell_piling: ''
  gfp_scope_error: ''
  not_steady_state: ''
  shear_stress: Shear stress value in dyn/cm^2
  time_hours_since_flow_start: Time in hours since cells first experienced a shear stress
locations:
  20250319_20X:
    fmsid: 299ccaacef4f4fc695a2946b3fb02b2d
    path: null
    s3uri: null
  20250326_20X:
    fmsid: 50ef4439584b447894b1ae1395a4f0b9
    path: null
    s3uri: null
  20250409_20X:
    fmsid: 6dbb401d04bd407f81d7c731495924ab
    path: null
    s3uri: null
  20250428_20X:
    fmsid: 0c776eaf93a046d9b1980da9721b074e
    path: null
    s3uri: null
  20250604_20X:
    fmsid: 10f52b9fc6d9455ebfcd1c210e923fa5
    path: null
    s3uri: null
  20250611_20X:
    fmsid: f75c425682c441f9a243937b7ef863d7
    path: null
    s3uri: null
  20250618_20X:
    fmsid: 2aefa957f4094a51b55162a14e38bc2f
    path: null
    s3uri: null
  20250714_20X:
    fmsid: 17688feadc49443f9bd5cd013f71b2ec
    path: null
    s3uri: null
  20250716_20X:
    fmsid: 69d93bc74d694ed1bce7fbd1ea5f24a9
    path: null
    s3uri: null
  20250728_20X:
    fmsid: 183af3dc18c3475fae1ab3ae3f40e368
    path: null
    s3uri: null
  20250813_20X:
    fmsid: 86464f7a5b214d0e8c0c3685b323ffec
    path: null
    s3uri: null
  20250818_20X:
    fmsid: fba2195690624c11909dc35adc131320
    path: null
    s3uri: null
  20250827_20X:
    fmsid: 08a34dbd7269458ba058b0994c67e6f3
    path: null
    s3uri: null
  20251001_20X:
    fmsid: 5dec6c57504348a68c2edd4518771007
    path: null
    s3uri: null
  20250402_20X:
    fmsid: 9437154209024ae88b45eeef5e67a4d1
    path: null
    s3uri: null
  20260114_20X:
    fmsid: 9e4c9174e4164ee1b4181f3fe7f51198
    path: null
    s3uri: null
  20260121_20X:
    fmsid: f6ec2d38c2af4431984ccd8fbded0b65
    path: null
    s3uri: null
  20260126_20X:
    fmsid: 8e608442730a40fdbbc7d74489a8cdf6
    path: null
    s3uri: null
  20260128_20X:
    fmsid: ed0f8e6350854642b60b174628f565b3
    path: null
    s3uri: null
  20260202_20X:
    fmsid: d63e6ba5ce7542f49a26669775353c1c
    path: null
    s3uri: null
  20260204_20X:
    fmsid: 64dac1b28ecc43a5851e752c9c7f2645
    path: null
    s3uri: null
  20260209_20X:
    fmsid: 3be3d856929443dfa284e3808c692024
    path: null
    s3uri: null
  20260211_20X:
    fmsid: 6b953a2045a64837b453cf3dd569693f
    path: null
    s3uri: null
  20260216_20X:
    fmsid: 9b296e8c18a047e8844ee7f5f984fbca
    path: null
    s3uri: null
  20260225_20X:
    fmsid: 76705439b72a45aa9dcf4f108b79cf2f
    path: null
    s3uri: null
  20260302_20X:
    fmsid: 85a242344b834bd9b02bb31c5d0b306d
    path: null
    s3uri: null
  20260304_20X:
    fmsid: 1f254c02103847078bec935fb41560e9
    path: null
    s3uri: null
