name: merged_segmentation_features
workflow: merge_segmentation_feature_tables
parameters: {}
columns:
  frame_number: Timepoint (unit = frames)
  track_id: Track ID assigned by the tracking algorithm
  reference_index: ''
  matched_query_label: ''
  optimized_metric_value: ''
  matching_method: ''
  dataset: Name of dataset
  position: Zarr file position (FOV) of the corresponding segmentation or patch (crop)
  zarr_path: Path to Zarr file for image that patch (crop) comes from
  filepath_segmentation_image: ''
  label: Cell segmentation ID (different from track ID, and may change between timepoints)
  centroid: Centroid of the cell segmentation in (Y,X) pixel coordinates
  area_px_squared: Area of the cell segmentation in pixels squared
  perimeter_px: Perimeter of the cell segmentation in pixels
  solidity: Solidity of the cell (ratio of the cell area to the area of its convex hull)
  major_axis_length: Length of the minor axis of an ellipse fit to the cell segmentation
  minor_axis_length: Length of the minor axis of an ellipse fit to the cell segmentation
  eccentricity: Eccentricity of ellipse fit to cell segmentation (focal distance divided by major axis)
  orientation: Orientation of the cell in radians from 0 (along +x axis) to pi (along -x axis)
  cell_fluorescence_mean_au: Mean of mEGFP-tagged VE-cadherin fluorescence (a.u.) in cytoplasmic region
    of cell segmentation
  cell_fluorescence_std_au: Standard deviation of mEGFP-tagged VE-cadherin fluorescence (a.u.) in cytoplasmic
    region of cell segmentation
  cell_fluorescence_median_au: Median of mEGFP-tagged VE-cadherin fluorescence (a.u.) in cytoplasmic
    region of cell segmentation
  cell_fluorescence_min_au: Minimum  of mEGFP-tagged VE-cadherin fluorescence (a.u.) in cytoplasmic
    region of cell segmentation
  cell_fluorescence_pct25_au: 25th percentile of mEGFP-tagged VE-cadherin fluorescence (a.u.) in cytoplasmic
    region of cell segmentation
  cell_fluorescence_pct75_au: 75th percentile of mEGFP-tagged VE-cadherin fluorescence (a.u.) in cytoplasmic
    region of cell segmentation
  cell_fluorescence_max_au: Maximum of mEGFP-tagged VE-cadherin fluorescence (a.u.) in cytoplasmic region
    of cell segmentation
  neighboring_cell_labels: Cell segmentation labels of adjacent cell segmentations
  edge_labels: ''
  node_labels: ''
  node_pair_labels: ''
  edge_fluorescence_au: Fluorescence values along boundary between 2 cell segmentations in a.u. (excluding
    pixels at nodes)
  node_fluorescence_au: Fluorescence values at junctions between 3 or more cell segmentations in a.u
  is_edge_segmentation: True if segmentation touches edge of the image, False otherwise
  nuclei_segmentation_labels: ''
  nuclei_seg_in_cdh5_seg_frac: ''
  nuc_seg_intens_means_EGFP: ''
  nuc_seg_intens_means_BF: ''
  nuc_seg_intens_stds_EGFP: ''
  nuc_seg_intens_stds_BF: ''
  nuc_seg_intens_medians_EGFP: ''
  nuc_seg_intens_medians_BF: ''
  nuc_seg_intens_pct25s_EGFP: ''
  nuc_seg_intens_pct25s_BF: ''
  nuc_seg_intens_pct75s_EGFP: ''
  nuc_seg_intens_pct75s_BF: ''
  nuc_seg_intens_maxs_EGFP: ''
  nuc_seg_intens_maxs_BF: ''
  nuc_seg_intens_mins_EGFP: ''
  nuc_seg_intens_mins_BF: ''
  nuclei_seg_with_most_overlap_0: ''
  nuc_with_most_overlap_0_centroid_Y: ''
  nuc_with_most_overlap_0_centroid_X: ''
  nuclei_seg_with_most_overlap_1: ''
  nuc_with_most_overlap_1_centroid_Y: ''
  nuc_with_most_overlap_1_centroid_X: ''
  total_nuclei_count_at_T: Total number of nuclei present at the timepoint of interest
  nuclei_seg_with_most_overlap_2: ''
  nuc_with_most_overlap_2_centroid_Y: ''
  nuc_with_most_overlap_2_centroid_X: ''
  nuclei_seg_with_most_overlap_3: ''
  nuc_with_most_overlap_3_centroid_Y: ''
  nuc_with_most_overlap_3_centroid_X: ''
  nuclei_seg_with_most_overlap_4: ''
  nuc_with_most_overlap_4_centroid_Y: ''
  nuc_with_most_overlap_4_centroid_X: ''
  nuclei_seg_with_most_overlap_5: ''
  nuc_with_most_overlap_5_centroid_Y: ''
  nuc_with_most_overlap_5_centroid_X: ''
  shear_stress_regime: Experimentalist categorization of the shear stress response
  time_resolution_minutes: Time resolution of the timelapse in minutes
  time_minutes: Time in minutes since the start of the timelapse
  time_hours: Time in hours since the start of the timelapse
  num_unique_tracks_per_timeframe: ''
  gaussian_sigma_for_area_smoothing: ''
  smoothed_area_normd: ''
  smoothed_area_normd_diff: Change in Gaussian-smoothed cell segmentation area in pixels squared
  num_unique_tracks_before_filtering_at_T: Number of unique tracks that are present at the timepoint
    of interest before filtering
  track_duration: Number of timepoints in the track
  alignment: Alignment of the cell relative to flow in radians from 0 (parallel) to pi (perpendicular)
  alignment_deg: Alignment of the cell relative to flow in degrees from 0 (parallel) to 90 (perpendicular)
  orientation_deg: Orientation of the cell in degrees from 0 (along +x axis) to 180 (along -x axis)
  nematic_order: Nematic order of ellipse fit to cell segmentation from -1 (perpendicular) to 1 (parallel)
  aspect_ratio: Aspect ratio of ellipse fit to cell segmentation (major axis divided by minor axis)
  pixel_size_xy_in_um: Size of a pixel in the XY dimensions in microns
  area_um_squared: Area of the cell segmentation in microns squared
  perimeter_um: Perimeter of the cell segmentation in microns
  edge_fluorescence_mean_au: Mean fluorescence (a.u.) at junctions between 2 cell segmentations (edge)
  edge_fluorescence_std_au: Standard deviation of fluorescence (a.u.) at junctions between 2 cell segmentations
    (edge)
  node_fluorescence_mean_au: Mean fluorescence (a.u.) at junctions between 3 or more cell segmentations
    (node)
  node_fluorescence_std_au: Standard deviation of fluorescence (a.u.) at junctions between 3 or more
    cell segmentations (node)
  edge_and_node_fluorescence_mean_au: Mean fluorescence (a.u.) of cell segmentation edges and nodes
  edge_and_node_fluorescence_std_au: Standard deviation of fluorescence (a.u.) of cell segmentation
    edges and nodes
  number_of_neighbors: Number of unique cell segmentations that are adjacent to this one
  image_size_x: Size of the whole image in the X dimension in pixels
  image_size_y: Size of the whole image in the Y dimension in pixels
  cdh5_channel_index_in_zarr: Index of the CDH5 channel in the Zarr file
  brightfield_channel_index_zarr: Index of the brightfield channel in the Zarr file
  num_nuclei_with_most_overlap: ''
  centroid_y: Centroid Y coordinate in pixels
  centroid_x: Centroid X coordinate in pixels
  nuclei_position_x: X coordinate of the label-free nuclei prediction centroid in pixels
  nuclei_position_y: Y coordinate of the label-free nuclei prediction centroid in pixels
  nuclei_position_distance: Distance between nucleus centroid and cell segmentation centroid in pixels
  nuclei_position_angle: Angle of nucleus centroid from cell centroid relative to flow in radians with
    0 along +x and pi/-pi along -x
  nuclei_position_angle_deg: Angle of nucleus centroid from cell centroid relative to flow in degrees
    with 0 along +x and 180/-180 along -x
  crop_size: Size of the crop in pixels at resolution level 0
  start_x_resolution_0: X-coordinate of upper left corner of patch (crop) in pixels (zarr resolution
    level 0)
  start_y_resolution_0: Y-coordinate of upper left corner of patch (crop) in pixels (zarr resolution
    level 0)
  end_x_resolution_0: X-coordinate of lower right corner of patch (crop) in pixels (zarr resolution
    level 0)
  end_y_resolution_0: Y-coordinate of lower right corner of patch (crop) in pixels (zarr resolution
    level 0)
  bbox_is_in_bounds: True if crop/cell-centered patch fits in to the larger image without being clipped
  diffae_resolution_level_to_use: DiffAE feature resolution level used to downsample resolution 0 coordinates
  num_nuclei_in_crop: Number of label-free predicted nuclei in a crop/cell-centered patch
  all_labels_in_crop: List of all segmentation labels found within a crop/cell-centered patch
  min_track_duration: Minimum number of timepoints for a track to be kept
  is_greater_than_min_track_duration: True if track duration exceeds minimum threshold, False otherwise
  max_smoothed_area_normd_change: Max change in the normalized smoothed cell segmentation area before
    being considered invalid
  is_less_than_max_smoothed_area_normd_change: True if change in Gaussian-smoothed cell segmentation
    area is less than threshold, False otherwise
  is_included: True if track passes all filtering criteria and is included in final dataset, False otherwise
  num_valid_tp_per_track: Number of timepoints in track that pass all segmentation-based filters
  min_num_valid_tp_per_track: Minimum number of timepoints that pass all other filters for a track to
    be kept
  has_more_than_min_num_valid_points_per_track: True if track has sufficient number of timepoints passing
    all other filters, False otherwise
  num_unique_tracks_after_filtering_at_T: Number of unique tracks that pass filtering criteria at the
    timepoint of interest
  auto_bf_scope_error: True if timepoint was automatically flagged with brightfield channel error, False
    otherwise
  auto_bf_temp_artifact: True if timepoint was automatically flagged with brightfield channel suddenly
    becoming too bright or too dark, False otherwise
  auto_gfp_scope_error: True if timepoint was automatically flagged with 488 channel (VE-cadherin-mEGFP)
    error, False otherwise
  bf_scope_error: True if timepoint was manually determined with brightfield channel error, False otherwise
  cell_piling: True if there is considered to be cell piling at this timepoint, False otherwise
  gfp_scope_error: True if timepoint was manually determined with 488 channel (VE-cadherin-mEGFP) error,
    False otherwise
  not_steady_state: True if cells have not yet reached steady state, False if they have
  shear_stress: Shear stress value in dyn/cm^2
  time_hours_since_flow_start: Time in hours since cells first experienced a shear stress
locations:
  20250319_20X:
    fmsid: 299ccaacef4f4fc695a2946b3fb02b2d
    path: null
    s3uri: null
  20250326_20X:
    fmsid: 50ef4439584b447894b1ae1395a4f0b9
    path: null
    s3uri: null
  20250409_20X:
    fmsid: 6dbb401d04bd407f81d7c731495924ab
    path: null
    s3uri: null
  20250428_20X:
    fmsid: 0c776eaf93a046d9b1980da9721b074e
    path: null
    s3uri: null
  20250604_20X:
    fmsid: 10f52b9fc6d9455ebfcd1c210e923fa5
    path: null
    s3uri: null
  20250611_20X:
    fmsid: f75c425682c441f9a243937b7ef863d7
    path: null
    s3uri: null
  20250618_20X:
    fmsid: 2aefa957f4094a51b55162a14e38bc2f
    path: null
    s3uri: null
  20250714_20X:
    fmsid: 17688feadc49443f9bd5cd013f71b2ec
    path: null
    s3uri: null
  20250716_20X:
    fmsid: 69d93bc74d694ed1bce7fbd1ea5f24a9
    path: null
    s3uri: null
  20250728_20X:
    fmsid: 183af3dc18c3475fae1ab3ae3f40e368
    path: null
    s3uri: null
  20250813_20X:
    fmsid: 86464f7a5b214d0e8c0c3685b323ffec
    path: null
    s3uri: null
  20250818_20X:
    fmsid: fba2195690624c11909dc35adc131320
    path: null
    s3uri: null
  20250827_20X:
    fmsid: 08a34dbd7269458ba058b0994c67e6f3
    path: null
    s3uri: null
  20251001_20X:
    fmsid: 5dec6c57504348a68c2edd4518771007
    path: null
    s3uri: null
  20250402_20X:
    fmsid: 9437154209024ae88b45eeef5e67a4d1
    path: null
    s3uri: null
  20260114_20X:
    fmsid: 9e4c9174e4164ee1b4181f3fe7f51198
    path: null
    s3uri: null
  20260121_20X:
    fmsid: f6ec2d38c2af4431984ccd8fbded0b65
    path: null
    s3uri: null
  20260126_20X:
    fmsid: 8e608442730a40fdbbc7d74489a8cdf6
    path: null
    s3uri: null
  20260128_20X:
    fmsid: ed0f8e6350854642b60b174628f565b3
    path: null
    s3uri: null
  20260202_20X:
    fmsid: d63e6ba5ce7542f49a26669775353c1c
    path: null
    s3uri: null
  20260204_20X:
    fmsid: 64dac1b28ecc43a5851e752c9c7f2645
    path: null
    s3uri: null
  20260209_20X:
    fmsid: 3be3d856929443dfa284e3808c692024
    path: null
    s3uri: null
  20260211_20X:
    fmsid: 6b953a2045a64837b453cf3dd569693f
    path: null
    s3uri: null
  20260216_20X:
    fmsid: 9b296e8c18a047e8844ee7f5f984fbca
    path: null
    s3uri: null
  20260225_20X:
    fmsid: 76705439b72a45aa9dcf4f108b79cf2f
    path: null
    s3uri: null
  20260302_20X:
    fmsid: 85a242344b834bd9b02bb31c5d0b306d
    path: null
    s3uri: null
  20260304_20X:
    fmsid: 1f254c02103847078bec935fb41560e9
    path: null
    s3uri: null
