name: nuclei_labelfree_segmentation
workflow: get_nuclei_measured_features
parameters: {}
columns:
  dataset: Name of dataset
  position: Zarr file position (FOV) of the corresponding segmentation or patch (crop)
  frame_number: Timepoint [frames]
  cdh5_segmentation_label: Label ID for the CDH5 cell segmentation
  nuclei_segmentation_labels: List of labels from label-free nuclei predictions that
    overlap with the cell segmentation
  nuclei_seg_in_cdh5_seg_frac: List of fractions of label-free nuclei prediction that
    overlap with the cell segmentation
  nuclei_with_most_overlap_0: ID of nuclei prediction that overlaps most with cell
    segmentation (index 0, multiple nuclei recorded in additional columns)
  nuclei_with_most_overlap_0_centroid_Y: Centroid Y coordinate of nuclei prediction
    that overlaps most with cell segmentation (index 0, multiple nuclei recorded in
    additional columns)
  nuclei_with_most_overlap_0_centroid_X: Centroid X coordinate of nuclei prediction
    that overlaps most with cell segmentation (index 0, multiple nuclei recorded in
    additional columns)
  nuclei_with_most_overlap_1: ID of nuclei prediction that overlaps most with cell
    segmentation (index 1, multiple nuclei recorded in additional columns)
  nuclei_with_most_overlap_1_centroid_Y: Centroid Y coordinate of nuclei prediction
    that overlaps most with cell segmentation (index 1, multiple nuclei recorded in
    additional columns)
  nuclei_with_most_overlap_1_centroid_X: Centroid X coordinate of nuclei prediction
    that overlaps most with cell segmentation (index 1, multiple nuclei recorded in
    additional columns)
  total_nuclei_count_at_T: Total number of nuclei present at the timepoint of interest
  nuclei_with_most_overlap_2: ID of nuclei prediction that overlaps most with cell
    segmentation (index 2, multiple nuclei recorded in additional columns)
  nuclei_with_most_overlap_2_centroid_Y: Centroid Y coordinate of nuclei prediction
    that overlaps most with cell segmentation (index 2, multiple nuclei recorded in
    additional columns)
  nuclei_with_most_overlap_2_centroid_X: Centroid X coordinate of nuclei prediction
    that overlaps most with cell segmentation (index 2, multiple nuclei recorded in
    additional columns)
  nuclei_with_most_overlap_3: ID of nuclei prediction that overlaps most with cell
    segmentation (index 3, multiple nuclei recorded in additional columns)
  nuclei_with_most_overlap_3_centroid_Y: Centroid Y coordinate of nuclei prediction
    that overlaps most with cell segmentation (index 3, multiple nuclei recorded in
    additional columns)
  nuclei_with_most_overlap_3_centroid_X: Centroid X coordinate of nuclei prediction
    that overlaps most with cell segmentation (index 3, multiple nuclei recorded in
    additional columns)
  nuclei_with_most_overlap_4: ID of nuclei prediction that overlaps most with cell
    segmentation (index 4, multiple nuclei recorded in additional columns)
  nuclei_with_most_overlap_4_centroid_Y: Centroid Y coordinate of nuclei prediction
    that overlaps most with cell segmentation (index 4, multiple nuclei recorded in
    additional columns)
  nuclei_with_most_overlap_4_centroid_X: Centroid X coordinate of nuclei prediction
    that overlaps most with cell segmentation (index 4, multiple nuclei recorded in
    additional columns)
  nuclei_with_most_overlap_5: ID of nuclei prediction that overlaps most with cell
    segmentation (index 5, multiple nuclei recorded in additional columns)
  nuclei_with_most_overlap_5_centroid_Y: Centroid Y coordinate of nuclei prediction
    that overlaps most with cell segmentation (index 5, multiple nuclei recorded in
    additional columns)
  nuclei_with_most_overlap_5_centroid_X: Centroid X coordinate of nuclei prediction
    that overlaps most with cell segmentation (index 5, multiple nuclei recorded in
    additional columns)
  nuclei_with_most_overlap_6: ID of nuclei prediction that overlaps most with cell
    segmentation (index 6, multiple nuclei recorded in additional columns)
  nuclei_with_most_overlap_6_centroid_Y: Centroid Y coordinate of nuclei prediction
    that overlaps most with cell segmentation (index 6, multiple nuclei recorded in
    additional columns)
  nuclei_with_most_overlap_6_centroid_X: Centroid X coordinate of nuclei prediction
    that overlaps most with cell segmentation (index 6, multiple nuclei recorded in
    additional columns)
locations:
  20250319_20X:
    fmsid: d25304a964df4a10aa918b11bf9d54bf
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/nuclei_labelfree_segmentation/20250319_0d94f8d3054e4e8c99af07dd92774798.parquet
  20250326_20X:
    fmsid: 9dd4400ee1df4bedafc3c459e3d486f1
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/nuclei_labelfree_segmentation/20250326_eb97addf262c44c5a6117ad1d4acc353.parquet
  20250409_20X:
    fmsid: d48850e6b4ef4f3988c73c17e94c9160
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/nuclei_labelfree_segmentation/20250409_df6b2a02bbc94c6f957923add524eac1.parquet
  20250428_20X:
    fmsid: f69d9330cdec44c898a6fd8f74a660ac
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/nuclei_labelfree_segmentation/20250428_056aa027ba9f4ccd98367563552f7edd.parquet
  20250604_20X:
    fmsid: a183569c5ecf4fa3b2ffa7632b70fce1
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/nuclei_labelfree_segmentation/20250604_3f08ef7a2e0e450d963352dae4bf17dc.parquet
  20250611_20X:
    fmsid: 19ae0466da174bf490b418e3b2194982
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/nuclei_labelfree_segmentation/20250611_a32615d530ae42c29d159cc058601879.parquet
  20250618_20X:
    fmsid: 6c4304f93fbe41f582f7527509bc582e
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/nuclei_labelfree_segmentation/20250618_f81e9bdf048e462e9755d7cbf5d21c37.parquet
  20250714_20X:
    fmsid: 80cfaf66553b4e8aa428f6e899e6940c
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/nuclei_labelfree_segmentation/20250714_0a0462b7d33848c8826105ab6f78787d.parquet
  20250716_20X:
    fmsid: 511f1983c6b54722b983408762283019
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/nuclei_labelfree_segmentation/20250716_328c62ecc91248eab2268e546892453e.parquet
  20250728_20X:
    fmsid: 3a95f2c0b2d0421f93a99d8d1885d6cd
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/nuclei_labelfree_segmentation/20250728_b07652734b1b43178f4bc704abd7b95b.parquet
  20250813_20X:
    fmsid: 4f4a298ad0ac4dd5a482b2a22ea2f033
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/nuclei_labelfree_segmentation/20250813_6ab0f70bd43f4de987a789905dbfb95c.parquet
  20250818_20X:
    fmsid: f9c95582ca184cac9ec7974dfed19088
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/nuclei_labelfree_segmentation/20250818_1f895d9188df43e0a10b379cf23a879c.parquet
  20250827_20X:
    fmsid: b13ce3a614024ea286cc2d2bc6389c3b
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/nuclei_labelfree_segmentation/20250827_c96180b30a224a48bac3b6d8fe1ffbb4.parquet
  20251001_20X:
    fmsid: 2c7656034b6e4b9487f22fa8e37f2557
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/nuclei_labelfree_segmentation/20251001_271124f03a16409499e8a84b0030cb15.parquet
  20250402_20X:
    fmsid: b040bb386f6144db986e17fa2dfe6f2e
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/nuclei_labelfree_segmentation/20250402_90e37b7d8f1440efa84995b4697fb269.parquet
  20260114_20X:
    fmsid: 49e6859d821346269c0591253fd30351
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/nuclei_labelfree_segmentation/20260114_4b693bb8eedb4e0ba0cb9ab4ae07b1a2.parquet
  20260121_20X:
    fmsid: 3389d85860164d0f811b8afb5e055c80
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/nuclei_labelfree_segmentation/20260121_ff75e124720b4a3aa035025a05ced25f.parquet
  20260126_20X:
    fmsid: 2dc47ea0488e4eb9b7ff4e066d8d2dee
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/nuclei_labelfree_segmentation/20260126_aed19d79c1a34707925cfa8393424c45.parquet
  20260128_20X:
    fmsid: 5a28aadc37dd41fbb03606ebabf3afab
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/nuclei_labelfree_segmentation/20260128_00bd94ea6d7e4b46bc16a55e35de589d.parquet
  20260202_20X:
    fmsid: a315e35990354f299c8aa2406a26d915
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/nuclei_labelfree_segmentation/20260202_fcb18a65bb734ff6ae718e1eee4894d6.parquet
  20260204_20X:
    fmsid: 0c0447fb9f584d3b9aeeaca432183315
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/nuclei_labelfree_segmentation/20260204_ac1fddfd7452481e83317c8fbdd59dd6.parquet
  20260209_20X:
    fmsid: 33f41ff5ee2f4df68456e4d94a48eda8
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/nuclei_labelfree_segmentation/20260209_3700e11f893e4f378db450ea91bd92d6.parquet
  20260211_20X:
    fmsid: 7128a084e3464ad483baec22ac906d89
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/nuclei_labelfree_segmentation/20260211_20b76dc8d0ca488ba88816793830f6ec.parquet
  20260216_20X:
    fmsid: cfdb69cfd78a4de4b36085cc3ebc96b5
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/nuclei_labelfree_segmentation/20260216_ed3743a1ee4c4cb096f5af90e3ebb9bd.parquet
  20260225_20X:
    fmsid: 3877cefc8c214f60b1cf77d6488766e0
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/nuclei_labelfree_segmentation/20260225_50afe3cb17cf4be099dc44e47f7a4ae4.parquet
  20260302_20X:
    fmsid: 63d5264cb65f473cbd869c1c7584f1e6
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/nuclei_labelfree_segmentation/20260302_e9cfa3b0b24447f7bba000af3b012427.parquet
  20260304_20X:
    fmsid: a118497d31c046a184d6aa2527518242
    path: null
    s3uri: s3://allencell-internal-quilt/endo_stg/nuclei_labelfree_segmentation/20260304_56c81f459d8e46eabd74cc2147b85f49.parquet
