name: optical_flow_bf_tracked
workflow: compute_optical_flow_feats
parameters:
  crop_pattern: tracked
  channel: BF
  max_dt: 1
  intensity_percentile: 0
  attachment: 2.5
  ema_alphas: [0.1]
  speed_threshold: 1.0
columns:
  start_x: ''
  position: Zarr file position (FOV) of the corresponding segmentation or patch (crop)
  frame_number: Timepoint (unit = frames)
  end_y: ''
  track_id: ''
  start_y: ''
  end_x: ''
  dataset: Name of dataset
  crop_index: ''
  track_duration: ''
  is_included: ''
  duration_minutes: ''
  timepoint: ''
  optical_flow_mean_speed_dt1: ''
  optical_flow_mean_unit_vector_dt1: ''
  optical_flow_std_speed_dt1: ''
  optical_flow_mean_angle_dt1: ''
  optical_flow_angle_std_dt1: ''
  optical_flow_mean_u_dt1: ''
  optical_flow_mean_v_dt1: ''
  optical_flow_std_u_dt1: ''
  optical_flow_std_v_dt1: ''
  speed_above_1_count_dt1: ''
  optical_flow_mean_unit_vector_fast_dt1: ''
  optical_flow_radial_coherence_dt1: ''
  optical_flow_radial_coherence_weighted_dt1: ''
  ema005_optical_flow_mean_unit_vector_dt1: ''
  ema005_optical_flow_mean_unit_vector_fast_dt1: ''
  ema01_optical_flow_mean_unit_vector_dt1: ''
  ema01_optical_flow_mean_unit_vector_fast_dt1: ''
  ema02_optical_flow_mean_unit_vector_dt1: ''
  ema02_optical_flow_mean_unit_vector_fast_dt1: ''
  ema01_optical_flow_radial_coherence_dt1: ''
  ema01_optical_flow_radial_coherence_weighted_dt1: ''
locations:
  20250319_20X:
    fmsid: 5fa14282d27f4d2090fc86cf7ea9eb67
    path: null
    s3uri: null
  20250428_20X:
    fmsid: 214e5f18e77842638dc8ebc7621af395
    path: null
    s3uri: null
  20250611_20X:
    fmsid: 9c6ed36769a243c89a993fef26da9162
    path: null
    s3uri: null
  20250618_20X:
    fmsid: 0b01328556c847c2b33824f08348d087
    path: null
    s3uri: null
  20250714_20X:
    fmsid: e3e5d0855020422bb30a050b20993b08
    path: null
    s3uri: null
  20250813_20X:
    fmsid: 96710a1b4d8a42edad0d404c2dd5429e
    path: null
    s3uri: null
  20250818_20X:
    fmsid: d7e400cf47e04f378683e9f4383750e9
    path: null
    s3uri: null
  20250827_20X:
    fmsid: 0cede489d4104609a14ad1e112ad95a5
    path: null
    s3uri: null
