name: registered_live_fixed
workflow: register_paired_images
parameters:
  resolution_level: 1
locations:
  20250214_pairedFixation:
    fmsid: 019f48cb1a304dcb8c5071135040894d
    path: null
    s3uri: null
