name: registered_live_fixed
workflow: register_paired_images
parameters:
  resolution_level: 1
locations:
  20250214_pairedFixation:
    fmsid: a39521cee371430e82d84fc08ac9c1c5
    path: null
    s3uri: null
  20251126_pairedFixation:
    fmsid: 64ef42a2368a4531b3b49767cc3e06da
    path: null
    s3uri: null
  20251125_pairedFixation:
    fmsid: 092eef18b78049ca974fcf5e73449e4b
    path: null
    s3uri: null
