from collections.abc import Callable
from pathlib import Path

import fire
import numpy as np
import pandas as pd
from sklearn.pipeline import Pipeline

from src.endo_pipeline.configs import (
    ModelManifest,
    dynamics_io,
    get_timelapse_model_manifests,
    load_dataset_config,
    load_model_config,
)
from src.endo_pipeline.io import get_output_path
from src.endo_pipeline.library.analyze.diffae_features import (
    compute_extrapolated_vector_field,
    get_callable_vector_field,
    get_traj_and_diff,
    get_traj_by_flow,
    model_data_comparison_one_dataset,
)
from src.endo_pipeline.library.analyze.diffae_manifest import (
    fit_pca,
    get_manifest_for_dynamics_workflows,
    get_pc_column_names,
)
from src.endo_pipeline.library.analyze.kramersmoyal import get_kramers_moyal
from src.endo_pipeline.library.analyze.numerics import get_bins
from src.endo_pipeline.library.visualize import viz_base


def _ddd_model_analysis(
    dataset_name: str,
    sde_model: list[Callable],
    stationary_data: pd.DataFrame,
    shear: float,
    pc_axes: list[int],
    bins: list[np.ndarray],
    fig_savedir: Path,
    config: dict,
) -> None:
    """
    Generate and save figures analyzing the data-driven dynamics model.
    This does the main analysis of the data-driven dynamics analysis workflow.

    Inputs:
    - dataset_name (str): name of the dataset
    - model (list[Callable]): list of callable functions
        representing the drift and diffusion estimates
        for the data-driven dynamics model
    - stationary_data: DataFrame, feature data for one dataset
        at one flow condition within that dataset, restricted to
        only the frames where the data are stationary
    - shear (float): shear stress value for the dataset
    - pc_axes (list[int]): list of principal components to analyze
        e.g., if pcs = [0,1], analyzing data projected onto
        the first two principal components
    - bins (list[np.ndarray]): list of bin edges for the histogram
        plots
    - fig_savedir (Path): directory to save figures
    - config (dict): configuration dictionary
        Loaded from dynamics_config.yaml
    - stationary_frames: list of int, optional, if provided,
    restrict data to only these frames
    (e.g., last 100 frames of each flow condition)
    as our cutoff for stationary data
        - if None, return all data
        - this may be hardcoded in the data config in the future


    Outputs:
    - None: saves figures to fig_savedir
        Figures include phase plane plots and histograms
        comparing model prediction (stationary FPE solution
        using drift and diffusion estimates) to data
    """
    # for phase plane plots, grid is fixed and
    # set in the config file dynamics_config.yaml
    pplane_xlim = config["plt_xlim"]["pplane"]
    pplane_ylim = config["plt_ylim"]["pplane"]
    num_pts_pplane = config["num_pts_pplane"]

    pplane_xvec = np.linspace(pplane_xlim[0], pplane_xlim[1], num_pts_pplane + 1)
    pplane_yvec = np.linspace(pplane_ylim[0], pplane_ylim[1], num_pts_pplane + 1)

    # call main model analysis function
    fig1, _, fig2, _ = model_data_comparison_one_dataset(
        sde_model,
        stationary_data,
        shear,
        pc_axes,
        bins,
        pplane_xvec,
        pplane_yvec,
    )

    # add title to histogram plots

    sup_title = f"{dataset_name}, {shear} dyn/cm$^2$ \n {fig2.texts[0].get_text()}"
    fig2.suptitle(sup_title, fontsize=fig2.texts[0].get_fontsize(), y=1.15)

    # save figures
    viz_base.save_plot(fig1, fig_savedir / f"{dataset_name}_ddff_phase_portrait_shear_{int(shear)}")
    viz_base.save_plot(
        fig2, fig_savedir / f"{dataset_name}_ddff_stationary_dist_shear_{int(shear)}"
    )
    return


def _get_and_analyze_ddd(
    model_manifest: ModelManifest,
    pca: Pipeline,
    kernel_params: dict | None,
    fig_savedir: Path,
    dynamics_config: dict,
) -> None:
    """
    Get and analyze data-driven dynamics for a given dataset.
    Wrapper function for _ddd_model_analysis, called by main.

    Inputs:
    - model_manifest (ModelManifest): model manifest object
        for a given dataset and deep learning model
    - pca (Pipeline): fit PCA object
        Used to project data into PCA space
    - kernel_params (dict): parameters for kernel method
        Used to compute drift and diffusion estimates
        Keys:
        - "kernel": kernel function to use
            See library.analyze.kramersmoyal.km_kernels
        - "bandwidth": bandwidth for kernel function
    - fig_savedir (Path): directory to save figures
    - dynamics_config (dict): configuration dictionary
        Loaded from dynamics_config.yaml

    Outputs:
    - None: saves figures generated by ddd_model_analysis
        to directory fig_savedir
    """
    # unpack relevant parameters from config:

    # which PCs to analyze (2D)
    pc_axes = dynamics_config["pcs_to_analyze"]
    # time step (in minutes)
    dt = dynamics_config["dt"]

    # bin limits for ddff and histogram
    # fixed across all datasets
    bin_xlim = dynamics_config["plt_xlim"]["hist"]
    bin_ylim = dynamics_config["plt_ylim"]["hist"]
    num_bins_hist = dynamics_config["num_bins_hist"]
    # get bins edges and centers
    bins, centers = get_bins(num_bins_hist, bin_limits=[bin_xlim, bin_ylim])

    # load DiffAE feature data from this one dataset
    # projected onto principal component axes as defined
    # by fit PCA object pca. Restrict to stationary frames if provided
    df_proj = get_manifest_for_dynamics_workflows(model_manifest, pca=pca)

    # get pc columns for axes of interest
    pc_column_names = get_pc_column_names(df_proj, pc_axes)

    # split out data by flow condition
    df_by_flow, shear_list = get_traj_by_flow(
        df_proj, load_dataset_config(model_manifest.dataset_name)
    )
    num_flow = len(shear_list)

    # get drift and diffusion estimates
    # for each flow condition
    # and analyze the data-driven dynamics model

    for j in range(num_flow):
        # get list of per-crop trajectories and list
        # of the corresponding displacement vectors
        traj_list, d_traj_list = get_traj_and_diff(df_by_flow[j], pc_column_names)

        # get drift and diffusion estimates (Kramers-Moyal coefficients)
        drift_km, diff_km = get_kramers_moyal(
            traj_list,
            d_traj_list,
            bins,
            dt,
            kernel_params=kernel_params,
        )

        # extrapolate nans in drift and diffusion estimates
        drift_dict = compute_extrapolated_vector_field(drift_km, centers, interpolator="nearest")
        diffusion_dict = compute_extrapolated_vector_field(diff_km, centers, interpolator="nearest")

        # turn into callable vector fields
        # have to have shear as a parameter
        # (dummy variable)
        def drift_(x: np.ndarray, u: float, vector_dict: dict = drift_dict) -> np.ndarray:
            drift = get_callable_vector_field(vector_dict, for_solve_ivp=False)
            return drift(x)

        def diffusion_(x: np.ndarray, u: float, vector_dict: dict = diffusion_dict) -> np.ndarray:
            diffusion = get_callable_vector_field(vector_dict, for_solve_ivp=False)
            return diffusion(x)

        # call main model analysis function
        # for the data driven dynamics workflow
        _ddd_model_analysis(
            model_manifest.dataset_name,
            [drift_, diffusion_],
            df_by_flow[j],
            shear_list[j],
            pc_axes,
            bins,
            fig_savedir,
            dynamics_config,
        )


def main(dynamics_config_name: str = "default", model_name: str = "diffae_04_10") -> None:
    """
    Get and visualize data-driven flow fields for all datasets in the manifest.

    Includes model summary and comparison to data as used in, e.g.,
    `cellsmap.analyses.workflows.stochastic_dynamics.dynamics_summarize`.
    """
    #### Load manifest data and fit PCA ####
    # make save directory for workflow outputs
    # (set in config file dynamics_config.yaml)
    print("\n", "*** Running workflow using config: ", dynamics_config_name, "\n")
    dynamics_config = dynamics_io.load_dynamics_config(dynamics_config_name)

    # get output subdirectory for figures that workflow outputs
    # (set in config file dynamics_config.yaml)
    # if directory does not exist, get_output_path function will create it
    fig_savedir = get_output_path(
        "stochastic_dynamics", dynamics_config_name, model_name, "figs", include_timestamp=False
    )

    # fit PCA to reference timepoints of
    # reference datasets
    pca = fit_pca(model_name=model_name)

    #### Get data driven flow fields (kernel method) ####
    # load inputs from dynamics_config.yaml
    kramers_moyal_config = dynamics_config["kramers_moyal"]
    kernel_params = None
    if "kernel_params" in kramers_moyal_config:
        kernel_params = kramers_moyal_config["kernel_params"]

    #################### Load model manifest data ###################
    # get model config from model name
    model_config = load_model_config(model_name)

    # filter out datasets that are not timelapse
    # and load model manifests
    model_manifest_list = get_timelapse_model_manifests(model_config)

    for model_manifest in model_manifest_list:
        print(f"Computing drift and diffusion fields for dataset {model_manifest.dataset_name}")

        _get_and_analyze_ddd(
            model_manifest,
            pca,
            kernel_params,
            fig_savedir,
            dynamics_config,
        )


if __name__ == "__main__":
    fire.Fire(main)
