name: 20250227_paired20X
original_path: //allen/programs/allencell/data/proj0/40a/c58/7ca/53c/c3c/178/c48/155/684/78a/35/20250227_GE00007101_20X_ZSTACK_SLDY/20250227_GE00007101_20X_zstacks_SLDY.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250227_3578a684155c48178c3c53c7cac5840a
fmsid: 3578a684155c48178c3c53c7cac5840a
barcode: GE00007101
cell_lines: [AICS-126]
live_or_fixed_sample: live
microscope: 3i
shear_stress_regime: 24hr_low
use_cases: []
pixel_size_xy_in_um: 0.382
duration: 1
time_interval_in_minutes: -1.0
flow: [[0, -1, 0]]
488_channel_index: 0
brightfield_channel_index: 1
n_total_positions: 10
notes: ''
nuclear_label_free_seg_path: null
nuclear_seg_manifest_fmsid: ''
diffae_manifest_fmsid: fd79709d90864162b2aef5817946a9d4
