name: 20250319_20X
original_path: //allen/programs/allencell/data/proj0/798/774/d92/07d/9af/8c9/e4e/054/8d3/94f/0d/20250319_GE00007419_20X_SLDY/20250319_GE00007419_20X_Timelapsee.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250319_0d94f8d3054e4e8c99af07dd92774798
fmsid: 0d94f8d3054e4e8c99af07dd92774798
barcode: GE00007419
cell_lines: [AICS-126]
live_or_fixed_sample: live
microscope: 3i
shear_stress_regime: intermediate
use_cases: []
pixel_size_xy_in_um: 0.382
duration: 542
time_interval_in_minutes: 5.0
flow: [[0, 576, 12.2]]
488_channel_index: 0
brightfield_channel_index: 1
n_nuclear_seg_manifest_fmsid: ''
n_total_positions: 6
notes: Stopped imaging prior to 48 hours because cells were very packed
nuclear_label_free_seg_path: null
diffae_manifest_fmsid: f68469a1a7f948dc92d20693a59b1aeb
valid_timepoints:
  start: [117]
  stop: [336]
cell_mean_features: c79efb6d0f754e719b71221d7ea3c17f
