name: 20250509_20X_IF7
original_path: //allen/programs/allencell/data/proj0/6ce/a46/c2b/993/e1f/d8b/749/b24/18b/a62/c9/20250509_GE00007878_20X_sldy/20250509_GE00007878_20X_sldy.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250509_c9a6218bb24749d8be1f993c2ba466ce
fmsid: c9a6218bb24749d8be1f993c2ba466ce
barcode: GE00007878
cell_lines: [AICS-126]
live_or_fixed_sample: fixed
microscope: 3i
shear_stress_regime: 24hr_intermediate
use_cases: [immunofluorescence]
pixel_size_xy_in_um: 0.382
duration: 1
time_interval_in_minutes: -1.0
flow: [[0, -1, 10.96]]
405_channel_index: 0
488_channel_index: 1
561_channel_index: 2
640_channel_index: 3
brightfield_channel_index: 4
n_total_positions: 2
notes: image content NucViolet,EGFP_CDH5,SOX17,SMAD1,BF
nuclear_label_free_seg_path: null
nuclear_seg_manifest_fmsid: ''
diffae_manifest_fmsid: e14b9497286d47c595921767e52f19e9
diffae_tracking_integration_fmsid: ''
