name: 20250509_20X_IF8
original_path: //allen/programs/allencell/data/proj0/769/598/cd5/148/2e1/099/945/d93/157/64e/8f/20250509_GE00007879_20X_sldy/20250509_GE00007879_20X_sldy.sldy
zarr_path: //allen/aics/endothelial/morphological_features/image_data/converted_zarrs/20250509_8f64e157d939450992e1148cd5598769
fmsid: 8f64e157d939450992e1148cd5598769
barcode: GE00007879
cell_lines: [AICS-126]
live_or_fixed_sample: fixed
microscope: 3i
shear_stress_regime: intermediate
use_cases: [immunofluorescence]
pixel_size_xy_in_um: 0.382
duration: 1
time_interval_in_minutes: -1.0
flow: [[0, -1, 10.96]]
405_channel_index: 0
488_channel_index: 1
561_channel_index: 2
640_channel_index: 3
brightfield_channel_index: 4
n_total_positions: 2
notes: image content NucViolet,EGFP_CDH5,SOX17,NR2F2,BF
nuclear_label_free_seg_path: null
nuclear_seg_manifest_fmsid: ''
diffae_manifest_fmsid: 61e57753a9fa4c63903791346c399e9a
diffae_tracking_integration_fmsid: ''
