name: registered_live_fixed
workflow: register_paired_images
parameters: {}
locations:
  20250214_pairedFixation:
    path: //allen/aics/endothelial/morphological_features/IF_integration/live_fixed_resolution_1/20250214_070e32c7355a40a288df2e68ae19adbc_P{{position}}_combined_paired_bf.ome.tiff
