experiment_name: endo_time
run_name: mae_bf
task_name: train
tags:
- dev
train: true
test: false
checkpoint:
  ckpt_path: "//allen/aics/assay-dev/users/Benji/CurrentProjects/im2im_dev/cyto-dl/logs/train/runs/endo_time/mae_bf/2024-08-13_16-40-08/checkpoints/epoch_899.ckpt"
  weights_only: null
  strict: true
seed: 12345
data:
  _target_: cyto_dl.datamodules.multidim_image.make_multidim_image_dataloader
  batch_size: 1
  pin_memory: true
  num_workers: 8
  spatial_dims: 2
  shuffle: False
  dict_meta:
    path: //allen/aics/assay-dev/computational/data/endothileal_cell_data/Timelapse_20x_dataset/full_movie_track_test/zarr/bf.ome.zarr
    channel: 3
  out_key: raw
  transforms: 
    - _target_: cyto_dl.image.transforms.clip.Clip
    - _target_: monai.transforms.NormalizeIntensity
    - _target_: monai.transforms.ToTensor
      dtype: float16
    - _target_: monai.transforms.GridSplit
      grid: [3, 18]
      size: [512, 512]

model:
  _target_: cyto_dl.models.contrastive.Contrastive
  anchor_key: raw
  backbone:
    _target_: cyto_dl.nn.vits.MAE_ViT
    spatial_dims: 2
    base_patch_size:
    - 16
    - 16
    num_patches:
    - 32
    - 32
    emb_dim: 256
    encoder_layer: 16
    encoder_head: 8
    decoder_layer: 4
    decoder_dim: 128
    mask_ratio: 0
    use_crossmae: true
    learnable_pos_embedding: false
    features_only: True

  task_head: 
  optimizer:
    generator:
      _partial_: true
      _target_: torch.optim.AdamW
      weight_decay: 0.05
  lr_scheduler:
    generator:
      _partial_: true
      _target_: torch.optim.lr_scheduler.OneCycleLR
      max_lr: 0.0001
      epochs: ${trainer.max_epochs}
      steps_per_epoch: 1
      pct_start: 0.1

callbacks:
  csv_saver:
    _target_: cellsmap.model_features.utils.csv_saver.MAESaver
    save_dir: ${paths.output_dir}
    meta_keys: ['T']
logger:
trainer:
  _target_: lightning.Trainer
  default_root_dir: ${paths.output_dir}
  min_epochs: 1
  max_epochs: 1000
  accelerator: gpu
  devices:
  - 0
  precision: 16
  check_val_every_n_epoch: 10
  deterministic: false
  detect_anomaly: false
  max_time: null
  gradient_clip_val: 5
paths:
  root_dir: ${oc.env:PROJECT_ROOT, './'}
  data_dir: ${paths.root_dir}/data/
  log_dir: ${paths.root_dir}/logs/
  output_dir:
extras:
  ignore_warnings: true
  enforce_tags: true
  print_config: true
  precision:
    _target_: torch.set_float32_matmul_precision
    precision: medium
persist_cache: true
