name: pca_reference_new
description: Reference datasets used to compute principal component axes (included in model training)
datasets:
- 20250618_20X # 6 dyn / cm2
- 20250611_20X # 20 dyn / cm2
- 20250818_20X # 0 dyn / cm2
