name: perturbation
description: Datasets for perturbation experiments (CDH5 Ex2 deletion) and their controls
datasets:
- 20250908_20X # CDH5 Ex2 deletion under low shear stress
- 20251022_20X # isogenic control under low shear stress
- 20251029_20X # CDH5 Ex2 deletion under low shear stress
- 20251105_20X # isogenic control under low shear stress
- 20251119_20X # CDH5 Ex2 deletion under low shear stress
- 20250618_20X # 6 dyn / cm2 rep 1
- 20250402_20X # 6 dyn / cm2
- 20250409_20X # 6 dyn / cm2
