
[{
  name: "default",
  output_subdir: "dynamics_output",
  PCs_to_analyze: [0,1],
  datasets_to_skip: ['20241016_20X','20241210_20X','20241217_20X'],
  Nbins_kramers_moyal: [35,25],
  dt: 5,
  polynomial_lib: {"drift_x": 3, 
                    "drift_param": 3, 
                    "diffusion_x": 0,
                    "diffusion_param": 3},
  plt_xlim: {"pplane": [-4,4], "hist": [-5,5]},
  plt_ylim: {"pplane": [-3.5,2.5], "hist": [-4,3.5]},
  Nbins_hist: [50,50],
  Nbins_landscape: [60,60],
  shear_range: [4,30],
  N_shear_fpt: 60,
  N_shear_landscape: 15,
  downsample_quiver: 10,
},
]