
[{name: "default",
  pcs_to_analyze: [0,1],
  datasets_to_skip: ['20241022_20X_mito','20241203_20X','20241217_20X','20250402_20X'],
  dt: 5,
  kramers_moyal: {"num_bins": [75,60],
                  "kernel_params": {"bandwidth": 0.075,
                                    "kernel": 'gaussian',
                                    },
                  },
  polynomial_lib: {"drift_feats": 4,
                    "drift_param": 6,
                    "diffusion_feats": 4,
                    "diffusion_param": 6},
  plt_xlim: {"pplane": [-1,1], "hist": [-1.25,1.25]},
  plt_ylim: {"pplane": [-0.5,0.75], "hist": [-0.6,0.75]},
  num_pts_pplane: 50,
  num_bins_hist: [50,50],
  num_bins_landscape: [60,60],
  shear_range: [4,30],
  num_shear_fpt: 60,
  num_shear_landscape: 15,
  downsample_quiver: 10,
  norm_vectors: 'False',
},
{name: "pc3",
  pcs_to_analyze: [0,2],
  datasets_to_skip: ['20241022_20X_mito','20241203_20X','20241217_20X','20250402_20X'],
  dt: 5,
  kramers_moyal: {"num_bins": [75,60],
                  "kernel_params": {"bandwidth": 0.08,
                                    "kernel": 'gaussian',
                                    },
                  },
  polynomial_lib: {"drift_feats": 3,
                    "drift_param": 4,
                    "diffusion_feats": 3,
                    "diffusion_param": 4},
  plt_xlim: {"pplane": [-1,1], "hist": [-1.25,1.25]},
  plt_ylim: {"pplane": [-0.5,0.7], "hist": [-0.6,0.8]},
  num_pts_pplane: 50,
  num_bins_hist: [50,50],
  num_bins_landscape: [60,60],
  shear_range: [4,30],
  num_shear_fpt: 60,
  num_shear_landscape: 15,
  downsample_quiver: 10,
  norm_vectors: 'False',
},
]
