from endo_pipeline.cli import CropPattern, Datasets
from endo_pipeline.settings.dynamics_workflows import HISTOGRAM_THRESHOLD_FOR_MASKING


def main(
    crop_pattern: CropPattern = "grid",
    datasets: Datasets | None = None,
    global_limits: bool = True,
    mask_threshold: float | None = HISTOGRAM_THRESHOLD_FOR_MASKING,
) -> None:
    """
    Analyze and visualize DiffAE feature dynamics in 2D.

    This workflow computes and visualizes the dynamics of DiffAE features
    pairwise in 2D for the crop-based features generated by the model specified
    via the `DEFAULT_MODEL_MANIFEST_NAME` and `DEFAULT_RUN_NAME` settings.

    The specific features to analyze and visualize are defined in the settings
    via the DYNAMICS_COLUMN_NAMES variable, and the default dataset to analyze
    is defined via the DEFAULT_DATASET_DYNAMICS_VIS variable.

    The workflow can also be run on a custom set of datasets using the
    `--datasets` command-line argument, but will only run on datasets that are
    present in the dataframe. If no datasets are provided, the workflow will run
    on the default dataset specified in the constant
    `DEFAULT_DATASET_DYNAMICS_VIS`.

    For each dataset in the specified collection, the workflow performs the
    following steps:
        1. Loads the grid-based crop feature dataframe, projects
            features into PCA space, and perform any additional feature
            transformations (e.g., computing polar coordinates, rescaling polar
            angle).
        2. Splits the dataframe by flow conditions based on shear stress.
        3. For each flow condition, loops over pairwise combinations of
           features:
            a. Estimates 2D drift coefficients (Kramers-Moyal) for each pair of
                features using a kernel-based estimation method with appropriate
                kernels for each variable.
            b. Plots contours of these estimated drift coefficients.

    Parameters
    ----------
    crop_pattern
        The crop pattern to get features for.
    datasets
        Specific datasets to run the workflow on.
    global_limits
        Whether to use global limits for all datasets when plotting drift
        contours.
    mask_threshold
        Threshold for masking low-confidence regions of drift estimates based on
        histogram of data points. If None, no masking is applied.
    """

    import logging

    import matplotlib.pyplot as plt
    import numpy as np

    from endo_pipeline.cli import DEMO_MODE
    from endo_pipeline.configs import (
        TimepointAnnotation,
        get_datasets_in_collection,
        load_dataset_config,
    )
    from endo_pipeline.io import get_output_path, load_dataframe
    from endo_pipeline.library.analyze.diffae_dataframe_utils import (
        filter_dataframe_by_annotations,
        get_traj_and_diff,
        split_dataset_by_flow,
    )
    from endo_pipeline.library.analyze.kramers_moyal.km_computation import (
        get_kernel_density_estimate,
        get_kramers_moyal_coeffs,
    )
    from endo_pipeline.library.analyze.kramers_moyal.km_kernels import KramersMoyalKernel
    from endo_pipeline.library.analyze.numerics.binning import get_bins
    from endo_pipeline.library.visualize.diffae_features.dynamics_viz import (
        plot_and_save_drift_contours,
        plot_and_save_drift_quiver,
    )
    from endo_pipeline.library.visualize.diffae_features.feature_viz import get_label_for_column
    from endo_pipeline.manifests import load_dataframe_manifest
    from endo_pipeline.settings.column_names import ColumnName as Column
    from endo_pipeline.settings.dynamics_workflows import (
        BIN_LIMIT_PERCENTILE_CUTOFF,
        BIN_LIMITS_DYNAMICS,
        BIN_LIMITS_THETA_RESCALED,
        BIN_WIDTHS_DYNAMICS,
        DEFAULT_DATASETS_DYNAMICS_VIS,
        DYNAMICS_COLUMN_NAMES,
        KERNEL_BANDWIDTHS_DYNAMICS,
        KERNEL_NAMES_DYNAMICS,
        METADATA_COLUMNS_TO_KEEP,
        RESCALE_THETA,
        TRACK_METADATA_COLUMNS_TO_KEEP,
    )
    from endo_pipeline.settings.flow_field_3d import TIME_STEP_IN_MINUTES
    from endo_pipeline.settings.workflow_defaults import (
        DEFAULT_MODEL_MANIFEST_NAME,
        DEFAULT_MODEL_RUN_NAME,
    )

    logger = logging.getLogger(__name__)

    # get labels for provided set of feature columns
    column_names = list(DYNAMICS_COLUMN_NAMES)
    columns_to_compute = [*METADATA_COLUMNS_TO_KEEP, *column_names]
    variable_labels_dict = {
        col: get_label_for_column(col).replace("polar ", "") for col in column_names
    }

    # unpack default bin widths and limits for each column, adjusting limits if rescaling theta
    global_bin_limits_dict = BIN_LIMITS_DYNAMICS.copy()
    if RESCALE_THETA:
        global_bin_limits_dict[Column.DiffAEData.POLAR_ANGLE] = BIN_LIMITS_THETA_RESCALED
    polar_angle_period = (
        global_bin_limits_dict[Column.DiffAEData.POLAR_ANGLE][1]
        - global_bin_limits_dict[Column.DiffAEData.POLAR_ANGLE][0]
    )

    # get dataframe manifest for grid-based crop features
    if crop_pattern == "tracked":
        logger.warning(
            "Crop pattern [ tracked ] is temporarily not supported for this workflow. "
            "Defaulting to [ grid ] crop pattern."
        )
        crop_pattern = "grid"

    dataframe_manifest_name = (
        f"{DEFAULT_MODEL_MANIFEST_NAME}_{DEFAULT_MODEL_RUN_NAME}_{crop_pattern}_pca_filtered"
    )
    dataframe_manifest = load_dataframe_manifest(dataframe_manifest_name)

    # Use provided datasets or default if none provided.
    dataset_names = datasets or get_datasets_in_collection(DEFAULT_DATASETS_DYNAMICS_VIS)

    if DEMO_MODE:
        logger.warning("DEMO MODE: limiting to first dataset only")
        dataset_names = dataset_names[:1]

    # loop over datasets in collection, compute 2D drift coefficients for each
    # pairwise combination of polar coordinates, and plot contours of drift coefficients
    for dataset_name in dataset_names:
        if dataset_name not in dataframe_manifest.locations:
            logger.warning(
                "No location found in dataframe manifest [ %s ] for dataset [ %s ], skipping visualization.",
                dataframe_manifest_name,
                dataset_name,
            )
            continue

        fig_savedir = get_output_path(__file__, crop_pattern, dataset_name)
        dataset_config = load_dataset_config(dataset_name)

        # load dataframe and perform additional filtering (remove
        # non-steady-state timepoints based on annotations), computing
        # only the columns needed for flow field estimation and analysis to save memory.
        df = load_dataframe(dataframe_manifest.locations[dataset_name], delay=True)
        # start with default metadata columns to keep
        if crop_pattern == "tracked":
            # also keep track ID and track length columns for tracked crops
            columns_to_compute = [*columns_to_compute, *TRACK_METADATA_COLUMNS_TO_KEEP]
        df_ = df[columns_to_compute].compute()
        df_steady_state = filter_dataframe_by_annotations(
            df_,
            dataset_config,
            timepoint_annotations=[TimepointAnnotation.NOT_STEADY_STATE],
        )

        df_by_flow, shear_stress_list = split_dataset_by_flow(df_steady_state, dataset_config)

        # compute on a per-shear stress condition basis
        for df_, shear_stress in zip(df_by_flow, shear_stress_list, strict=True):
            dataset_name_flow = f"{dataset_name}_shear_{int(shear_stress)}"
            fig_title = f"{dataset_name} ({shear_stress} dym/cm$^2$)"

            # loop over pairwise combinations of columns and plot drift contours
            for column_name_pair in [
                (Column.DiffAEData.POLAR_RADIUS, Column.DiffAEData.PC3_FLIPPED),  # r and rho
                (Column.DiffAEData.POLAR_RADIUS, Column.DiffAEData.POLAR_ANGLE),  # r and theta
                (Column.DiffAEData.PC3_FLIPPED, Column.DiffAEData.POLAR_ANGLE),  # rho and theta
            ]:
                # build kernels for each variable in the pair based on settings,
                # adjusting for periodicity if needed, and get bin edges and
                # centers for each variable in the pair. also get variable labels
                # and axis limits for plotting, adjusting limits if rescaling
                # theta and if not using global limits
                kernels = []
                bins_2d = []
                centers_2d = []
                column_labels_2d = []
                axes_limits_2d = []
                for column_name in column_name_pair:
                    kernels.append(
                        KramersMoyalKernel(
                            name=KERNEL_NAMES_DYNAMICS[column_name],
                            bandwidth=KERNEL_BANDWIDTHS_DYNAMICS[column_name],
                            period=(
                                polar_angle_period
                                if column_name == Column.DiffAEData.POLAR_ANGLE
                                else None
                            ),
                        )
                    )
                    column_labels_2d.append(variable_labels_dict[column_name])
                    if column_name == Column.DiffAEData.POLAR_ANGLE:
                        bins_, centers_ = get_bins(
                            bin_widths=(BIN_WIDTHS_DYNAMICS[column_name],),
                            bin_limits=[global_bin_limits_dict[column_name]],
                        )
                    else:
                        bins_, centers_ = get_bins(
                            bin_widths=(BIN_WIDTHS_DYNAMICS[column_name],),
                            data=df_[column_name].to_numpy(),
                            lower_percentile=BIN_LIMIT_PERCENTILE_CUTOFF,
                            upper_percentile=100 - BIN_LIMIT_PERCENTILE_CUTOFF,
                        )
                    # returned 1d bins are lists of length 1, so extract arrays
                    # from lists and append
                    bins_1d = bins_[0]
                    centers_1d = centers_[0]
                    bins_2d.append(bins_1d)
                    centers_2d.append(centers_1d)
                    # set axis limits to bin limits for each variable if not
                    # using global limits, otherwise use global limits from
                    # settings
                    axes_limits_2d.append(
                        (bins_1d[0], bins_1d[-1])
                        if not global_limits
                        else global_bin_limits_dict[column_name]
                    )

                # get 2D trajectories and differences for the pair of variables
                traj_2d, diff_2d = get_traj_and_diff(
                    df_, column_names=list(column_name_pair), polar_angle_period=polar_angle_period
                )

                drift, _ = get_kramers_moyal_coeffs(
                    traj_2d,
                    diff_2d,
                    bins=bins_2d,
                    dt=TIME_STEP_IN_MINUTES / 60,  # convert to unit hours
                    kernel=kernels,
                )

                # get 2D meshgrid of bin centers for plotting
                centers_mesh = np.meshgrid(*centers_2d, indexing="ij")

                # get histogram for masking low-confidence regions of drift
                # estimates, using same kernels as for drift estimation, and set
                # drift to nan in low-confidence regions
                if mask_threshold is not None:
                    hist_kde = get_kernel_density_estimate(
                        traj_2d,
                        bins=bins_2d,
                        kernel=kernels,
                    )
                    low_confidence_mask = hist_kde < mask_threshold
                    drift[low_confidence_mask] = np.nan

                filename_prefix = f"{dataset_name_flow}_{'_'.join(column_name_pair)}"
                # plot drift contours and save
                plot_and_save_drift_contours(
                    centers_mesh,
                    drift,
                    variable_labels=column_labels_2d,
                    axes_limits=axes_limits_2d,
                    fig_title=fig_title,
                    fig_savedir=fig_savedir,
                    filename_prefix=filename_prefix,
                )

                # plot quiver plot of drift and save
                plot_and_save_drift_quiver(
                    centers_mesh,
                    drift,
                    variable_labels=column_labels_2d,
                    axes_limits=axes_limits_2d,
                    fig_title=fig_title,
                    fig_savedir=fig_savedir,
                    filename_prefix=filename_prefix,
                )
                plt.close("all")


if __name__ == "__main__":
    from endo_pipeline.cli import workflow_cli

    workflow_cli(main)
