name: diffae_resolution_2_patch_32x32_2025-07-29_18-11-15
mlflow_run_id: 39b7a03b3f5e4cfc9a9a20da3cbd3ae5
manifest_fmsids: []
training_datasets:
- 20241120_20X
- 20250319_20X
train_manifest_fmsid: null
test_manifest_fmsid: null
