name: diffae_resolution_1_patch_128x128_latent_2_exclude_cell_piling
workflow: build_diffae_train_config
parameters:
  training_datasets:
  - 20250319_20X
  - 20250428_20X
  - 20250611_20X
  - 20250618_20X
  - 20250714_20X
  - 20250813_20X
  - 20250818_20X
  - 20250827_20X
  crop_size: 128
  latent_dim: 2
  resolution_level: 1
  include_cell_piling: false
locations:
  github_demo:
    mlflowid: null
    path: null
