name: nuc_pred_labelfree
workflow: retrain_cellpose
parameters: {}
locations:
  finetuned_20250419:
    mlflowid: null
    fmsid: null
    path: //allen/aics/users/serge.parent/cellsmap_labelfree_nuclei_model/20250419-18_13/CellPose_default_nuclei_model_finetuning/models/labelfree_nuc_pred_20250419-18_13
    s3uri: null
