"""
Convert Tiff to Zarr files.

#internal #zarr-conversion

This notebook compiles Tiffs for individual timepoints and compiles and converts
them into a single Zarr. Input and output paths are taken from the Tiff to Zarr
conversion CSV generated by the `build-tiff-to-zarr-csv` workflow. Make sure to
run that workflow before running this one.

IMPORTANT: This workflow MUST be run in a separate environment than the rest
of the pipeline due to dependency version conflicts. Create a separate
environment using:

```bash
# deactivate any current environment
deactivate

# create a new empty environment (make sure you are using Python 3.11+)
python3 -m venv .venv_tiff_to_zarr_conversion

# activate new environment
source .venv_tiff_to_zarr_conversion/bin/activate

# install specific dependencies into new environment
pip install -i https://pypi.python.org/simple \
    bioio==3.0.0 bioio-ome-tiff==1.4.0 bioio-ome-zarr==3.0.2 \
    tqdm==4.67.1 pandas==3.0.1
```

Set the path to the conversion CSV and then run this workflow using:

```bash
python src/endo_pipeline/workflows/convert_tiff_to_zarr.py path/to/csv nuclear_labelfree_seg
python src/endo_pipeline/workflows/convert_tiff_to_zarr.py path/to/csv cdh5_classic_seg
```

You may optionally select a batch by providing a batch index. By default, each
batch contains 16 rows (this can be changed in the workflow). If the batch index
does not include any rows, the workflow will exit early.

```bash
python src/endo_pipeline/workflows/convert_tiff_to_zarr.py path/to/csv nuclear_labelfree_seg 0
python src/endo_pipeline/workflows/convert_tiff_to_zarr.py path/to/csv cdh5_classic_seg 3
```
"""

import multiprocessing
import re
import sys
import warnings
from collections.abc import Sequence
from concurrent.futures import ProcessPoolExecutor
from pathlib import Path

import pandas as pd
from bioio import BioImage
from bioio_ome_zarr.writers import OMEZarrWriter  # type: ignore
from bioio_ome_zarr.writers.metadata import Channel  # type: ignore
from dask.array.core import PerformanceWarning
from tqdm import tqdm

VALIDATION_SAVE_INTERVAL_IN_FRAMES = 48
"""Interval between frames when saving validation images."""

CHANNEL_COLORS = {
    "VE-cadherin_mEGFP_maximum_intensity_projection": "ffffff",  # white
    "VE-cadherin_mEGFP_preprocessed": "ffffff",  # white
    "VE-cadherin_mEGFP_hysteresis_threshold": "00ffff",  # teal
    "VE-cadherin_mEGFP_initial_segmentation": "ff00ff",  # magenta
    "VE-cadherin_mEGFP_merged_segmentation": "ffff00",  # yellow
    "Nuclei_labelfree_segmentation": "ff0000",  # red
    "VE-cadherin_mEGFP_segmentation_split_by_nuclei": "00ff00",  # green
    "VE-cadherin_mEGFP_segmentation_split_by_nuclei_borders": "0000ff",  # blue
}
"""Mapping of channels to colors."""


def collected_individual_timepoint_paths(root: str) -> list[tuple[int, str]]:
    """Collect paths for individual timepoints matching pattern `_T###.ome.tif`."""

    timepoint_paths: list[tuple[int, str]] = []

    for path in Path(root).glob("*.ome.tif*"):
        match = re.search(r"_T(\d+)(_grid_segmentation)?\.ome\.tif", path.name)

        if match:
            timepoint_paths.append((int(match.group(1)), str(path)))

    if not timepoint_paths:
        raise ValueError(f"No matching files found under: {root}")

    return sorted(timepoint_paths, key=lambda path: path[0])


def write_timelapse_from_dir_explicit_levels_single(
    *,
    src_dir: str,
    out_store: str,
    source_zarr: str,
    level_shapes: Sequence[Sequence[int]],
    channel_name: str,
    dtype: str = "uint16",
) -> None:
    """Write individual timepoints into single OME Zarr at multiple levels."""

    img_raw_microscopy = BioImage(source_zarr)

    # because the grid segmentation only has a single resolution level, and
    # this resolution level is 1 and not 0, we have to adjust the resolution
    # level that the raw microscopy image data is being loaded at to determine
    # the correct physical pixel size metadata
    for resolution_level, shape in img_raw_microscopy.resolution_level_dims.items():
        raw_shape_y, raw_shape_x = shape[-2], shape[-1]
        initial_level_shape_y, initial_level_shape_x = level_shapes[0][-2], level_shapes[0][-1]
        if (raw_shape_y, raw_shape_x) == (initial_level_shape_y, initial_level_shape_x):
            img_raw_microscopy.set_resolution_level(resolution_level)
            break

    pps = [
        float(getattr(img_raw_microscopy.scale, k, 1.0) or 1.0) for k in ("T", "C", "Z", "Y", "X")
    ]

    # If validation image, need to adjust the timescale, since those are only
    # saved every 48 frames. Also need to rescale the destination time index
    if "cdh5_seg_validations" in out_store:
        pps[0] = pps[0] * VALIDATION_SAVE_INTERVAL_IN_FRAMES
        t_rescale = VALIDATION_SAVE_INTERVAL_IN_FRAMES
    else:
        t_rescale = 1

    # Define channel colors based on channel names, if more than one channel
    # is provided. Otherwise, default to white
    channel_name_split = channel_name.split("/")
    if len(channel_name_split) > 1:
        channels = [Channel(label=c, color=CHANNEL_COLORS[c]) for c in channel_name_split]
    else:
        channels = [Channel(label=channel_name, color="#ffffff")]

    writer = OMEZarrWriter(
        store=Path(out_store),
        level_shapes=level_shapes,
        dtype=dtype,
        zarr_format=2,
        physical_pixel_size=pps,
        channels=channels,
        axes_units=["minute", "channel", "micrometer", "micrometer", "micrometer"],
    )

    for t_index, path in collected_individual_timepoint_paths(src_dir):
        img = BioImage(path)
        writer.write_timepoints(
            data=img.get_image_dask_data(),
            start_T_src=0,
            start_T_dest=t_index // t_rescale,
            total_T=1,
        )


def convert_tiff_to_zarr_for_row(row):
    """Convert Tiffs to Zarr for single row in conversion CSV."""

    total_timepoints = row["duration"]

    if "grid_seg_zarr" in row["save_zarr_path"]:
        level_shapes = [
            (total_timepoints, 1, 1, 856, 872),
        ]
    elif "cdh5_seg_validations" in row["save_zarr_path"]:
        total_timepoints = total_timepoints // VALIDATION_SAVE_INTERVAL_IN_FRAMES
        level_shapes = [
            (total_timepoints, 8, 1, 1712, 1744),
            (total_timepoints, 8, 1, 856, 872),
            (total_timepoints, 8, 1, 428, 436),
        ]
    else:
        level_shapes = [
            (total_timepoints, 1, 1, 1712, 1744),
            (total_timepoints, 1, 1, 856, 872),
            (total_timepoints, 1, 1, 428, 436),
        ]

    write_timelapse_from_dir_explicit_levels_single(
        src_dir=row["tiff_seg_dir"],
        out_store=row["save_zarr_path"],
        level_shapes=level_shapes,
        source_zarr=row["original_zarr"],
        channel_name=row["channel_name"],
    )

    img = BioImage(row["save_zarr_path"])
    if img.shape[0] != total_timepoints:
        raise RuntimeError(f"Expected {total_timepoints} timepoints, got {img.shape[0]}")


if __name__ == "__main__":
    image_manifest_name = sys.argv[2]

    valid_image_manifests = (
        "nuclear_labelfree_seg",
        "cdh5_classic_seg",
        "grid_seg",
        "cdh5_seg_validations",
    )
    if image_manifest_name not in valid_image_manifests:
        print(f"Image manifest name must be one of: {valid_image_manifests}")
        exit()

    results_path = Path(sys.argv[1])
    convert_csv_path = results_path / f"tiff_to_zarr_conversion_{image_manifest_name}.csv"

    # Silence warnings from Dask
    warnings.simplefilter(action="ignore", category=PerformanceWarning)

    # If running in batches, get batch index and only load that batch from the
    # dataframe. If not, load the entire dataframe.
    if len(sys.argv) > 3:
        batch_index = int(sys.argv[3])
        batch_size = 16
        batch_start = int(batch_index) * batch_size + 1
        df = pd.read_csv(convert_csv_path, skiprows=range(1, batch_start), nrows=batch_size)

        if df.empty:
            print(f"No rows found at given batch index '{batch_index}'")
            exit()
    else:
        df = pd.read_csv(convert_csv_path)

    # Convert tiff to zarr for each row in dataframe.
    with ProcessPoolExecutor(mp_context=multiprocessing.get_context("spawn")) as executor:
        list(
            tqdm(
                executor.map(convert_tiff_to_zarr_for_row, df.to_dict("records")),
                total=len(df),
                desc="Converting Tiffs to Zarrs",
            )
        )
