name: run-linting-checks

on: [push]

env:
  UV_VERSION: 0.7.1 # same as .pre-commit-config.yaml

jobs:
  run-linting-checks:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout the repo
      uses: actions/checkout@v4

    - name: Set up uv
      uses: astral-sh/setup-uv@b75a909f75acd358c2196fb9a5f1299a9a8868a4 # 6.7.0
      with:
        version: ${{ env.UV_VERSION }}
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"

    - name: Check lockfile
      run: uv lock --check

    - name: Install dependencies
      run: uv sync --locked --only-group lint

    - name: Check with black
      run: uv run --no-sync black --check src

    - name: Check with isort
      run: uv run --no-sync isort --check src

    - name: Lint with ruff
      run: uv run --no-sync ruff check src

  type-check:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@b75a909f75acd358c2196fb9a5f1299a9a8868a4 # 6.7.0
        with:
          version: ${{ env.UV_VERSION }}
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies
        run: uv sync --locked

      - name: Check with mypy
        run: uv run --no-sync mypy src
